Fix random failures in test_max_files_per_second.
wazuh/wazuh-qa pull request #1099
Opened 2021-03-02 15:58 UTC by antoniomanuelfr

- This commit also fixes the path generation of the assets directory in
  Windows systems.

|Related issue|
|---|
|#1098|

## Description

As described in #1098, this PR aims to fix the random failures in the test `test_max_files_per_second`.
This PR also fixes the path generation of the `assets` directory in Windows.

## Configuration options

## Logs example

```
root@ubuntu1:/vagrant/wazuh-qa/tests/integration/test_fim# python3 -m pytest --html=../../../../reportes/reporte1/report.html test_files/test_max_files_per_second/
==================================================================== test session starts ====================================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: html-2.0.1, testinfra-5.0.0, metadata-1.11.0
collected 6 items                                                                                                                                           

test_files/test_max_files_per_second/test_max_files_per_second.py ......                                                                              [100%]

-------------------------------------------- generated html file: file:///vagrant/reportes/reporte1/report.html ---------------------------------------------
==================================================================== 6 passed in 43.21s =====================================================================
root@ubuntu1:/vagrant/wazuh-qa/tests/integration/test_fim# 

```

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs

2021-03-03 09:26 UTC, BraulioV requested changes

2021-03-03 09:26 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/__init__.py
> +        self._fim_mode = list()
```suggestion
        self._fim_mode = []
```

2021-03-03 09:26 UTC, BraulioV commented on tests/integration/conftest.py
> +        default=list(),
```suggestion
        default=[],
```

2021-03-03 09:26 UTC, BraulioV commented on mkdocs.yml
> +              - test max files per second: tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.md
```suggestion
              - tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.md
```
If there's only a test in this directory, you can just list its markdown.

2021-03-03 14:24 UTC, antoniomanuelfr commented
These are the result of the tier 1 integration tests in Jenkins
[agent_centos
[agent_windows_html_report_test_integration_B1382_20210303122816.zip](https://github.com/wazuh/wazuh-qa/files/6076578/agent_windows_html_report_test_integration_B1382_20210303122816.zip)
[agent_ubuntu_html_report_test_integration_B1382_20210303122816.zip](https://github.com/wazuh/wazuh-qa/files/6076577/agent_ubuntu_html_report_test_integration_B1382_20210303122816.zip)
_html_report_test_integration_B1382_20210303122816.zip](https://github.com/wazuh/wazuh-qa/files/6076574/agent_centos_html_report_test_integration_B1382_20210303122816.zip)
[agent_macos_html_report_test_integration_B1383_20210303122900.zip](https://github.com/wazuh/wazuh-qa/files/6076575/agent_macos_html_report_test_integration_B1383_20210303122900.zip)
[agent_solaris_html_report_test_integration_B1383_20210303122900.zip](https://github.com/wazuh/wazuh-qa/files/6076576/agent_solaris_html_report_test_integration_B1383_20210303122900.zip)

2021-03-05 07:17 UTC, BraulioV approved these changes

2021-03-09 11:06 UTC, Molter73 approved these changes
LGTM!

2021-03-09 11:53 UTC, merged