Create requirements file and update python dependencies
wazuh/wazuh-qa pull request #1124
Opened 2021-03-10 11:55 UTC by Rebits

|Related issue|
|---|
|Closes #1072 , Closes #1095|

## Description

A requirements file have been created, replacing `install_requires` in setup script. Also, setting up test environment documentation has been updated.

## Documentation

![setting_up](https://user-images.githubusercontent.com/11089305/110625310-8cfb6180-819f-11eb-969a-093f22cdbcb3.png)

2021-03-10 15:57 UTC, jmv74211 requested changes
You have to open an issue in wazuh CICD to install new requirements txt file during the provisioning.

2021-03-11 08:25 UTC, BraulioV requested changes

2021-03-11 08:25 UTC, BraulioV commented on docs/Dockerfile
> +COPY ../../requirements.txt /
```suggestion
COPY ../requirements.txt /
```

2021-03-11 08:25 UTC, BraulioV commented on docs/tests/integration/setting_up_test_environment.md
> +- Install Python and development tools
```suggestion
- Install Python and the development tools
```

2021-03-11 08:25 UTC, BraulioV commented on docs/tests/integration/setting_up_test_environment.md
> +- Download wazuh-qa repository , install requirements and package dependencies.
```suggestion
- Download wazuh-qa repository, install the requirements and the package dependencies.
```

2021-03-11 08:25 UTC, BraulioV commented on docs/tests/integration/setting_up_test_environment.md
> +- Download wazuh-qa repository , install requirements and package dependencies.
```suggestion
- Download wazuh-qa repository, install the requirements and the package dependencies.
```

2021-03-11 08:25 UTC, BraulioV commented on docs/tests/integration/setting_up_test_environment.md
> +# Install requirements
```suggestion
# Install the requirements
```

2021-03-11 08:25 UTC, BraulioV commented on docs/tests/integration/setting_up_test_environment.md
> +- Download wazuh-qa repository, install requirements and package dependencies.
```suggestion
- Download wazuh-qa repository, install the requirements and the package dependencies.
```

2021-03-11 08:25 UTC, BraulioV commented on requirements.txt
> +freezegun
You must set a version for these dependencies.

2021-03-12 10:20 UTC, BraulioV approved these changes

2021-03-12 14:50 UTC, jmv74211 approved these changes

2021-03-12 14:51 UTC, merged