Fixed size for all agent simulator module messages
wazuh/wazuh-qa pull request #1196
Opened 2021-04-05 10:12 UTC by Rebits

|Related issue|
|---|
|closes #1175    |

This PR adds a `fixed_message_size` attribute to the agent simulator. This allows set fixed size in KB for all agent messages. It is implemented by adding a string of character 'A'  at the end of the message.

In addition, the `simulate_agent` script has been modified to include this new parameter

2021-04-05 15:12 UTC, BraulioV requested changes

2021-04-05 15:12 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py
> +        self.fixed_message_size = fixed_message_size
This value can be stored in bytes to avoid computing it in the loop.

2021-04-06 07:05 UTC, spothound approved these changes

2021-04-06 07:17 UTC, BraulioV approved these changes

2021-04-06 07:17 UTC, merged