Add a new integration test to check the registry sync responses.
wazuh/wazuh-qa pull request #1216
Opened 2021-04-12 09:01 UTC by antoniomanuelfr

|Related issue|
|---|
|#1210 |

Closes #1210
## Description
This PR adds a new integration test to check all the changes introduced in https://github.com/wazuh/wazuh/pull/8143

## Tests

- [X] Proven that tests **pass** when they have to pass.
- [X] Proven that tests **fail** when they have to fail. If this test is executed in Windows agents pre 4.2, the agent will crash.

- [X] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [X] Python codebase is documented following the Google Style for Python docstrings.
- [X] The test is documented in wazuh-qa/docs.
- [X] `provision_documentation.sh` generate the docs without errors.

2021-04-13 09:03 UTC, BraulioV requested changes

2021-04-13 09:03 UTC, BraulioV commented on tests/integration/test_fim/test_synchronization/test_registry_responses_win32.py
> +        key_h = fim.RegOpenKeyEx(fim.registry_parser[key], key_path, 0, fim.KEY_ALL_ACCESS | fim.KEY_WOW64_64KEY)
Same here. Use variables with an easy name to interpret.

2021-04-13 09:03 UTC, BraulioV commented on tests/integration/test_fim/test_synchronization/test_registry_responses_win32.py
> +                                                  (':subkey2', ':value2')])
```suggestion
@pytest.mark.parametrize('tags_to_apply', [{'registry_sync_responses'}])
@pytest.mark.parametrize('key_name, value_name', [(':subkey1:', 'value1'), (':subkey2', ':value2')])
```

2021-04-16 10:02 UTC, BraulioV approved these changes

2021-04-19 10:16 UTC, jotacarma90 approved these changes

2021-05-05 13:35 UTC, merged