1119 vulnerability archlinux
wazuh/wazuh-qa pull request #1220
Opened 2021-04-13 08:53 UTC by spothound

|Related issue|
|---|
|Closes https://github.com/wazuh/wazuh-qa/issues/1119|

## Description

The following tests have been added for arch linux:

## Configuration options

## Logs example

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2021-04-14 08:12 UTC, BraulioV requested changes
GJ Paco! I requested some minor changes in the PR related to the docstrings but anything else... LGTM. Just one more request: update the docs of the Vulnerability Detector tests.

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +    """
```suggestion
    """Modify the Arch Linux JSON feed by setting a test tag value."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
```suggestion
    """Check if the feed is imported successfully by default."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +    """
```suggestion
    """Check if Vulnerability Detector behaves as expected while importing Arch Linux JSON feed with extra tags."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
> +    """
```suggestion
    """Modify the Arch Linux feed by setting a test field value."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
```suggestion
    """Check if the feed is imported successfully by default."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
> +    """
```suggestion
    """Check if Vulnerability Detector behaves as expected while importing Arch Linux feed with syntax errors."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
> +    """
```suggestion
    """Modify the Arch Linux feed by setting a test field value."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
```suggestion
    """Check if the feed is imported successfully by default."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
> +    """
```suggestion
    """Check if Vulnerability Detector behaves as expected when importing Arch Linux feed with wrong field values."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
> +    """
```suggestion
    """Modify the feed by removing a certain field and loading the new feed configuration."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
```suggestion
    """Check if the feed is imported successfully by default."""
```

2021-04-14 08:12 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
> +    """
```suggestion
    """Check if Vulnerability Detector behaves as expected when importing Arch Linux feed with missing fields."""
```

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_missing_tags_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_values_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_invalid_syntax_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +    """Check if the feed is imported successfully by default"""
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-14 08:20 UTC, spothound commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +    """
https://github.com/wazuh/wazuh-qa/pull/1220/commits/7d650dcd2fb56e9cb3bd2810661d798e8a64e60b

2021-04-23 15:39 UTC, BraulioV requested changes

2021-04-23 15:39 UTC, BraulioV commented on docs/tests/integration/test_vulnerability_detector/test_feeds/test_invalid_type_url_feeds.md
> +```
```suggestion
```

2021-04-23 15:39 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_feeds/archlinux/test_extra_tags_archlinux_feed.py
> +from wazuh_testing.tools import file
```suggestion
from wazuh_testing.tools import LOG_FILE_PATH, file
```

2021-04-23 15:39 UTC, BraulioV commented on tests/integration/test_vulnerability_detector/test_scan_results/test_archliux_inventory_archlinux_feed.py
> +    print(vulnerability)
```suggestion
```

2021-04-29 13:33 UTC, BraulioV approved these changes

2021-05-03 15:08 UTC, merged