Logcollector integration tests T0: Check log_format values
wazuh/wazuh-qa pull request #1290
Opened 2021-05-04 13:34 UTC by damarisg

| Related issue   |
| [1126 ](https://github.com/wazuh/wazuh-qa/issues/1226)             |

## Description

05.04 = - Validation with Json file. (Draft)
             - Problems with the environment.

## Configuration options

## Logs example

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2021-05-13 12:05 UTC, spothound reviewed
JUst a few changes asked from my part.

2021-05-13 12:05 UTC, spothound commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +#    iis_path = r'%SystemDrive%\inetpub\logs\LogFiles\W3SVC1\test.log'
?????

2021-05-17 14:26 UTC, BraulioV requested changes

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +                                error_message=logcollector.GENERIC_CALLBACK_ERROR_READING_FILE)
```suggestion
    if conf['log_format'] in log_format_windows_print_analyzing_info:
        # For this case you're only covering iis logs
        if conf['log_format'] == 'iis':
            log_callback = logcollector.callback_read_file(conf['location'])
        
    elif conf['log_format'] in log_format_not_print_reading_info:
        # Logs format that only shows when a specific file is read.
        log_callback = logcollector.callback_read_file(conf['location'])

    elif conf['log_format'] == 'multi-line:3':
        # It is necessary to reorganize the content of the file to compare it
        # with the generated output of the 'multiline' format.

        msg = ""
        with open(location) as file:
            for line in file:
                msg += line.rstrip('\n')
                msg += ' '
            log_callback = logcollector.callback_reading_file(conf['log_format'], msg.rstrip(' '))
    else:
        # Verify that the content of the parsed file is equal to the output generated in the logs.
        with open(location) as file:
            for line in file:
                log_callback = logcollector.callback_reading_file(conf['log_format'], line.rstrip('\n'))
    
    wazuh_log_monitor.start(timeout=5, callback=log_callback,
                            error_message=logcollector.GENERIC_CALLBACK_ERROR_READING_FILE)
```

This `if` block is a bit messy. Give it another round and refactor it to make it easier to understand. Also, take into account that some cases are not covered yet.

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +    """
Follow the standard for the docstings. Also, the `Args` and `Returns` fields are missing.

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +        return log_callback
```suggestion
    return log_callback
```

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +   """
Same here.

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +   """
Same here.

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +        file.remove_file(conf['location'])
```suggestion
    check_log_format_valid(conf)    
    modify_file(conf['location'], conf['log_format'], conf['valid_value'])
    if conf['valid_value']:
        check_log_format_value_invalid(conf)
    else:
        check_log_format_value_valid(conf)
    file.remove_file(conf['location'])
```

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +    """
Same here.

2021-05-17 14:26 UTC, BraulioV commented on tests/integration/test_logcollector/test_log_format/test_log_format_values.py
> +                check_log_format_values(conf)
This code-block can be simplified by unifying the common lines.

2021-05-21 10:56 UTC, BraulioV approved these changes

2021-05-21 11:03 UTC, spothound approved these changes
lgtm

2021-05-21 11:26 UTC, merged