Add test to check the behavior of test_max_fd_win_rt option.
wazuh/wazuh-qa pull request #1387
Opened 2021-05-28 09:32 UTC by antoniomanuelfr

|Related issue|
|---|
|#1386|

## Description
This PR aims to add a new integration test that checks the correct behavior of the option `max_fd_win_rt`
Closes #1386 

## Tests

- [X] Proven that tests **pass** when they have to pass.
- [X] Proven that tests **fail** when they have to fail.

- [X] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [X] Python codebase is documented following the Google Style for Python docstrings.
- [X] The test is documented in wazuh-qa/docs.
- [X] `provision_documentation.sh` generate the docs without errors.

2021-06-02 07:49 UTC, BraulioV requested changes

2021-06-02 07:49 UTC, BraulioV commented on tests/integration/test_fim/test_files/test_inotify/test_max_fd_rt.py
> +                              generate_params, change_internal_options, callback_realtime_added_directory
```suggestion
import wazuh_testing.fim as fim
```

2021-06-02 07:49 UTC, BraulioV commented on tests/integration/test_fim/test_files/test_inotify/test_max_fd_rt.py
> +# Fixtures
```suggestion
```

2021-06-02 07:49 UTC, BraulioV commented on tests/integration/test_fim/test_files/test_inotify/test_max_fd_rt.py
> +# Tests
```suggestion
```

2021-06-02 07:49 UTC, BraulioV commented on docs/tests/integration/test_fim/test_files/test_inotify/test_max_fd_rt.md
> +::: tests.integration.test_fim.test_files.test_inotify.test_max_fd_rt
Can you update the docs to look similar to this one https://github.com/wazuh/wazuh-qa/blob/master/docs/tests/integration/test_remoted/test_agent_communication/test_invalid_protocol_communication.md? This is the new format and we're migrating the existing docs to this one.

2021-06-14 08:30 UTC, spothound approved these changes

2021-06-14 09:54 UTC, BraulioV approved these changes

2021-06-15 08:28 UTC, spothound approved these changes
lgtm

2021-06-15 14:48 UTC, Molter73 approved these changes
LGTM!

2021-06-16 09:17 UTC, BraulioV approved these changes

2021-06-17 15:42 UTC, merged