Add unnified logging system tests for macOS
wazuh/wazuh-qa pull request #1392
Opened 2021-05-31 09:09 UTC by Rebits

|Related issue|
|---|
|Closes #1330 |

## Description

This PR adds new tools to test macOS unified logging system(ULS) events. Also, a basic test has been created to ensure Wazuh macOS agent sends correctly ULS events.

## Implementation

In order to gather Wazuh macOS ULS events sent by the agent, remoted simulator has been adapted to store sent events in a queue. 

![Untitled Diagram](https://user-images.githubusercontent.com/11089305/120169332-1ef39300-c200-11eb-90c6-6c51a16cf76f.png)

To generate ULS events in the agent host, we have created some functions `macos_os_log_message` and `macos_logger_message` that uses `logger` (https://www.unix.com/man-page/osx/1/logger/) and `os_log` (https://developer.apple.com/documentation/os/os_log) function respectively.

- **logger  ULS event**

![logger_message](https://user-images.githubusercontent.com/11089305/120169656-77c32b80-c200-11eb-8280-7e231c53f01d.png)

- **os_log event**

![custom_log_console](https://user-images.githubusercontent.com/11089305/120169659-785bc200-c200-11eb-8d2d-49c0d0dab0f5.png)

## Test results

### MacOS

![test_macos_results](https://user-images.githubusercontent.com/11089305/120167524-2154ed80-c1fe-11eb-96b0-8d3e68409fda.png)

## Documentation
![documentation-macos](https://user-images.githubusercontent.com/11089305/120167587-3598ea80-c1fe-11eb-9280-958f9eea7d13.png)

2021-05-31 10:22 UTC, spothound commented on deps/wazuh_testing/wazuh_testing/logcollector.py
> +    To run correctly `log_generator` is necessary to compile it. This is done in temporal folder, using `process_name`
```suggestion
    To correctly run  `log_generator` is necessary to compile it. This is done in a temporal folder, using `process_name`
```

2021-05-31 10:22 UTC, BraulioV requested changes

2021-05-31 10:22 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/logcollector.py
>  from wazuh_testing.tools import LOGCOLLECTOR_STATISTICS_FILE, monitoring
```suggestion
from wazuh_testing.tools import LOGCOLLECTOR_STATISTICS_FILE, WAZUH_PATH, monitoring
```

2021-05-31 10:22 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/logcollector.py
> +TEMPLATE_OSLOG_MESSAGE = 'Custom os_log event message'
```suggestion
TEMPLATE_MACOS_LOG_MESSAGE = 'Custom os_log event message'
```

2021-05-31 10:22 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/logcollector.py
> +                                           'tools/macos_log/log_generator.swift')
```suggestion
                                           'tools', 'macos_log', 'log_generator.swift')
```

2021-05-31 10:22 UTC, BraulioV commented on docs/tests/integration/test_logcollector/index.md
> +Wazuh macOS agent allows gather unnified logging system events. These tests ensure logcollector works correctly with this
```suggestion
Wazuh macOS agent allows gathering unified logging system events. These tests ensure logcollector works correctly with this
```

2021-05-31 10:22 UTC, BraulioV commented on docs/tests/integration/test_logcollector/test_macos/index.md
> +Wazuh macOS agent allow gather unnified logging system events. These tests ensure logcollector works correctly with this
```suggestion
Wazuh macOS agent allows gathering unified logging system events. These tests ensure logcollector works correctly with this
```

2021-05-31 10:22 UTC, BraulioV commented on docs/tests/integration/test_logcollector/test_macos/test_macos_format_basic.md
> +Check if `wazuh-logcollector` gather correctly unnified logging system events.
```suggestion
Check if `wazuh-logcollector` correctly gathers unified logging system events.
```

This typo is duplicated through the docs. You will need to change all of them.

2021-05-31 10:22 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/tools/manager_keys.py
> +sslmanager_key = """-----BEGIN PRIVATE KEY-----
This file can be moved to the `data` directory and load them in the `tools` module.

2021-05-31 10:22 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/logcollector.py
> +def macos_os_log_message(type, subsystem, category, process_name="custom_log"):
Be careful with the name of the functions. They don't represent what they're doing and also the name can be confusing.

2021-05-31 10:22 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/tools/remoted_sim.py
> +            binary_data(str): Binary data.
```suggestion
            binary_data (str): Binary data.
```
Also, this doc string... Is a bit obvious. Can you give more details about this variable?

2021-05-31 15:07 UTC, BraulioV requested changes

2021-05-31 15:07 UTC, BraulioV commented on tests/integration/test_logcollector/conftest.py
> +        get_connection_configuration (fixture): Dictionary with authd and remoted parameters.
`request` is missing

2021-05-31 15:07 UTC, BraulioV commented on deps/wazuh_testing/wazuh_testing/tools/__init__.py
> +_data_path = os.path.join(os.path.join(os.path.dirname(os.path.realpath(__file__)),'..'), 'data')
```suggestion
_data_path = os.path.join(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'), 'data')
```

2021-06-01 10:19 UTC, BraulioV approved these changes

2021-06-01 10:19 UTC, merged