CVEs alerts inventory for Vulnerability Detector - Vulnerability Detector Integration Tests implementation
wazuh/wazuh-qa pull request #1496
Opened 2021-06-24 17:14 UTC by MiguelazoDS

|Related issue|
|---|
|#1261|

## Description
This pull request implements the following set of test cases for Vulnerability Detector:
- test_scan_results: Includes tests that check vulnerabilities insertion and removal in: 
  - Log file
  - Alerts file
  - Vulnerabilities inventory database. 
- test_scan_types: Includes tests for **Baseline**, **Partial** and **Full** scans
- test_general_settings: Includes new settings **min_full_scan_interval** and **retry_interval**

These tests cover the new vulnerability detector functionalities as part of the epic [#7749](https://github.com/wazuh/wazuh/issues/7749). 
For more details, check the description of the epic [#1261](https://github.com/wazuh/wazuh-qa/issues/1261)

## Dod
`test_scan_types`

![types](https://user-images.githubusercontent.com/13010397/123296134-c22c8500-d4ec-11eb-873c-b60aa28dc67a.png)

`test_general_settings`

![general_settings](https://user-images.githubusercontent.com/13010397/123305302-551ded00-d4f6-11eb-8091-e0ad67a0f0cf.png)

`test_scan_results`

![scan_results](https://user-images.githubusercontent.com/13010397/123303139-daec6900-d4f3-11eb-9d92-93351b7a25e7.png)

## Tests

- [X] Proven that tests **pass** when they have to pass.
- [X] Proven that tests **fail** when they have to fail.

- [X] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [X] Python codebase is documented following the Google Style for Python docstrings.
- [X] The test is documented in wazuh-qa/docs.

2021-09-02 14:34 UTC, juliamagan requested changes

2021-09-02 14:34 UTC, juliamagan commented on deps/wazuh_testing/wazuh_testing/wazuh_db.py
> +            if len(data.split(' ')) > 1 and data.split(' ')[0] == 'ok':
```suggestion
            if len(data.split()) > 1 and data.split()[0] == 'ok':
```

`split` uses whitespaces by default

2021-11-09 19:18 UTC, DProvinciani commented on deps/wazuh_testing/wazuh_testing/vulnerability_detector.py
> +from wazuh_testing.tools import agent_simulator as ag
Fixed

2021-11-09 19:24 UTC, DProvinciani approved these changes
Looks good!

2021-11-09 19:24 UTC, merged