Modify integration tests for Vulnerability Detector: SUSE support dependencies
wazuh/wazuh-qa pull request #1583
Opened 2021-07-07 09:56 UTC by juanmanuelug

|Related issue|
|---|
|[#1526 ](https://github.com/wazuh/wazuh-qa/issues/1526)|

## Description

This PR modify the scan test for SUSE Linux Enterprise to take into account the dependencies of each package.

For `SLES 11, 12, 15` and `SLED 11, 12, 15`:

- [ ] Modify test_scan_result data for SUSE to add dependencies for each package.
- [x] Add function to insert dependencies to the vulnerability DB.
- [ ] Modify test_scan_result for SUSE to insert dependencies to the DB.
- [ ] Modify test_scan_result for SUSE to check if packages are not vulnerable.

## Test results

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2021-08-23 12:15 UTC, MarcelKemp requested changes

2021-08-23 12:15 UTC, MarcelKemp commented on deps/wazuh_testing/wazuh_testing/vulnerability_detector.py
> +                      operation="equals", operation_value="12.0", installed="0", package_id="0"):
With the latest changes, it is also necessary to insert the `target` to the "`dependencies`" and "`pkgs_deps`" tables.

2021-08-23 12:15 UTC, MarcelKemp commented on tests/integration/test_vulnerability_detector/test_scan_results/data/suse_vulnerabilities.json
> +                        "1": {
This second dependency is exactly the same as the first. It is necessary?

2021-08-23 12:15 UTC, MarcelKemp commented on tests/integration/test_vulnerability_detector/test_scan_results/test_suse_inventory_suse_feed.py
> +                                 operation_value=dependency['operation_value'], package_id=id)
The `installed` and `target` parameters are missing.

2021-08-23 12:15 UTC, MarcelKemp commented on tests/integration/test_vulnerability_detector/test_scan_results/test_suse_inventory_suse_feed.py
> +                if deps['name'] in packg['name']:
The `installed` flag already checks for this condition, so it is not necessary and can also be misleading.

2021-09-06 11:17 UTC, alromeros approved these changes
LGTM

2021-09-06 11:22 UTC, MarcelKemp approved these changes

2021-09-06 11:25 UTC, merged