Fix `test_agentd_state_config.py` for Windows
wazuh/wazuh-qa pull request #1592
Opened 2021-07-12 15:51 UTC by juliamagan

|Related issue|
|---|
|Closes #1588|

## Description

After research #1493, we could see that some `agentd` tests were failing. In issue #1521 we specified which tests were failing and why. Then we created different issues for each error.
This test was failing because it wasn't managing Windows' errors correctly. Then, the test wasn't setting the `local_internal_options.conf` properly, and also, it was trying to connect the agent to a non-existent manager.

The test might keep failing because of issue https://github.com/wazuh/wazuh/issues/8746.

## Tests results

```
================================================= test session starts =================================================
platform win32 -- Python 3.7.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.0 -- C:\Python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.4', 'Platform': 'Windows-10-10.0.14393-SP0', 'Packages': {'pytest': '6.2.2', 'py': '1.10.0', '
pluggy': '0.13.0'}, 'Plugins': {'html': '2.0.1', 'metadata': '1.8.0', 'testinfra': '5.0.0'}}
rootdir: C:\Windows\system32\wazuh-qa\tests\integration, configfile: pytest.ini
plugins: html-2.0.1, metadata-1.8.0, testinfra-5.0.0
collected 6 items

tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Negative state interval] PASSED [ 16
%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Undefined state interval value] PASS
ED [ 33%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[State interval option dont exist] PA
SSED [ 50%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Zero state interval] PASSED  [ 66%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Too big state interval] PASSED [ 83%
]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Default state interval] PASSED [100%
]

================================================= 6 passed in 19.13s ==================================================
```

## Tests

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.

2021-07-14 18:06 UTC, Rebits requested changes
Great job, but some changes are required.

2021-07-14 18:06 UTC, Rebits commented on tests/integration/test_agentd/test_agentd_state_config.py
> +                control_service('start', 'wazuh-agentd')
```suggestion
                control_service('start')
```

2021-07-14 18:06 UTC, Rebits commented on tests/integration/test_agentd/test_agentd_state_config.py
> +            control_service('start', 'wazuh-agentd')
```suggestion
            control_service('start')
```

2021-07-14 18:06 UTC, Rebits commented on tests/integration/test_agentd/test_agentd_state_config.py
>      # Check if test require checking state file existance
```suggestion
    # Check if the test requires checking state file existence
```

2021-07-14 18:08 UTC, Rebits commented
It is necessary to index three logs results for Windows/Linux agents. This is required to ensure the tests' consistency.

2021-07-16 09:34 UTC, juliamagan commented on tests/integration/test_agentd/test_agentd_state_config.py
>      set_state_interval(5, internal_options)
We will fix it when we start with the refactor.

2021-07-16 11:58 UTC, juliamagan commented
## Test results after changes

<details>
<summary>Test Execution 1 </summary>

### Windows Agent

```
================================================= test session starts =================================================
platform win32 -- Python 3.7.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.0 -- C:\Python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.4', 'Platform': 'Windows-10-10.0.14393-SP0', 'Packages': {'pytest': '6.2.2', 'py': '1.10.0',
pluggy': '0.13.0'}, 'Plugins': {'html': '2.0.1', 'metadata': '1.8.0', 'testinfra': '5.0.0'}}
rootdir: C:\Windows\system32\wazuh-qa\tests\integration, configfile: pytest.ini
plugins: html-2.0.1, metadata-1.8.0, testinfra-5.0.0
collected 6 items

tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Negative state interval] PASSED [ 1
%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Undefined state interval value] PAS
ED [ 33%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[State interval option dont exist] P
SSED [ 50%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Zero state interval] PASSED  [ 66%]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Too big state interval] PASSED [ 83
]
tests\integration\test_agentd\test_agentd_state_config.py::test_agentd_state_config[Default state interval] PASSED [100
]

================================================= 6 passed in 19.46s ==================================================
```
</details>

<details>
<summary>Test Execution 2 </summary>

### Windows Agent

```

```
</details>

<details>
<summary>Test Execution 3 </summary>

### Windows Agent

```

```
</details>

2021-07-16 12:09 UTC, juliamagan commented on tests/integration/test_agentd/test_agentd_state_config.py
>      # Check if test require checking state file existance
Fixed in df5a2de

2021-07-16 12:10 UTC, juliamagan commented on tests/integration/test_agentd/test_agentd_state_config.py
> +            control_service('start', 'wazuh-agentd')
Fixed in 647d4be

2021-07-16 12:10 UTC, juliamagan commented on tests/integration/test_agentd/test_agentd_state_config.py
> +                control_service('start', 'wazuh-agentd')
Fixed in 647d4be

2021-07-16 12:10 UTC, juliamagan commented on tests/integration/test_agentd/test_agentd_state_config.py
> +def test_agentd_state_config(test_case: list, set_local_internal_options):
Fixed in 647d4be

2021-07-19 08:04 UTC, juliamagan commented
While testing, we found some false positives due to the test was faster checking if the service was running or not than Wazuh configuring and booting it. We have added a sleep to wait for Wazuh to configure and boot `agentd` in  e685319.

2021-07-19 08:22 UTC, Rebits commented
### Review 19/07/2021

After some testing in the local environment, it looks that these fixes solve false positives cases in this test.

#### R1
- [Linux Agent](https://github.com/wazuh/wazuh-qa/files/6839141/r1_agentd_state_config_agent_linux.log)
- [Windows Agent]

#### R2
- [Linux Agent](https://github.com/wazuh/wazuh-qa/files/6839142/r2_agentd_state_config_agent_linux.log)
- [Windows Agent]

#### R3
- [Linux Agent](https://github.com/wazuh/wazuh-qa/files/6839143/r3_agentd_state_config_agent_linux.log)
- [Windows Agent]

2021-07-19 08:36 UTC, Rebits approved these changes

2021-08-10 16:36 UTC, snaow commented
LGTM. 
Windows tests will fail due to the mentioned product issues. 
I will continue with the merge since the problem is known and it's already assigned in @wazuh/core roadmap.

2021-08-10 16:36 UTC, merged