Fix `test_fim/test_files/test_report_changes/test_disk_quota_values.py`
wazuh/wazuh-qa pull request #1613
Opened 2021-07-19 10:38 UTC by juliamagan

|Related issue|
|---|
|Closes #1582|

### Environment

|OS|
|:--:|
|CentOS 8, Windows, Solaris, MacOS|
### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | msi (Windows) | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi 
Agent | pkg (macOS) | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.pkg 
Agent | p5p (Solaris 11) | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent_v4.2.0-1.1493-sol11-i386.p5p​

### local_internal_options.conf

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Description

After research #1493, we could see that some `FIM` tests were failing. In issue #1539 we specified which tests were failing and why. Then we created different issues for each error. 
This test was failing because was assuming that the size of the tested folder was greater than the limit size. We needed to change the tested folder and then, create a file with a size greater than the limit size.

## Tests results

||CentOS 8 Server|CentOS 8 Agent|Windows Agent|Solaris Agent|MacOS Agent|
|:--:|:--:|:--:|:--:|:--:|:--:|
|R1|
|R2|
|R3|

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

2021-07-20 09:31 UTC, juliamagan commented
While testing changes, we found out that macOS and Solaris are skipping this test because they don't support `realtime` or `whodata`. 
Since we have changed how parameters are generated, we need to add a specific case where macOS and Solaris use a low-frequency option instead of `realtime`.

2021-07-23 08:31 UTC, Molter73 requested changes
The PR is looking good! There are a few minor style changes I would like to see implemented.

I also ran the test on Ubuntu 20.04, Centos 8 and Windows, all of them with 2 cores and 2GB of ram, all tests passed without any issue:

#### Ubuntu
- [R0](https://github.com/wazuh/wazuh-qa/files/6867485/disk_quota-0.zip) 🟢
- [R1](https://github.com/wazuh/wazuh-qa/files/6867486/disk_quota-1.zip) 🟢
- [R2](https://github.com/wazuh/wazuh-qa/files/6867487/disk_quota-2.zip) 🟢

#### Centos
- [R0](https://github.com/wazuh/wazuh-qa/files/6867503/disk_quota-0.zip) 🟢
- [R1](https://github.com/wazuh/wazuh-qa/files/6867504/disk_quota-1.zip) 🟢
- [R2](https://github.com/wazuh/wazuh-qa/files/6867505/disk_quota-2.zip) 🟢

#### Windows
- [R0](https://github.com/wazuh/wazuh-qa/files/6867510/disk-quota-0.zip) 🟢
- [R1](https://github.com/wazuh/wazuh-qa/files/6867511/disk-quota-1.zip) 🟢
- [R2](https://github.com/wazuh/wazuh-qa/files/6867512/disk-quota-2.zip) 🟢

2021-07-23 10:52 UTC, juliamagan commented on tests/integration/test_fim/test_files/test_report_changes/data/wazuh_disk_quota_values_conf.yaml
> +                value: DISK_QUOTA_LIMIT
Done in 0d18840

2021-07-23 10:52 UTC, juliamagan commented on tests/integration/test_fim/test_files/test_report_changes/test_disk_quota_values.py
> +    remove_file(os.path.join(temp_dir, 'test'))
Done in bdada00

2021-07-23 12:59 UTC, Molter73 approved these changes
LGTM!

The changes from my previous review to this one are merely cosmetic so the tests ran previously are still valid IMO.

2021-08-19 19:15 UTC, merged