Add test to scan all python packages used by Wazuh
wazuh/wazuh-qa pull request #1652
Opened 2021-07-26 20:35 UTC by Kondent

|Related issue|
|---|
|#1612|

## Description
This PR closes #1612.
I made a tool to check vulnerabilities in all python packages used by wazuh specified from a requirements file or directly from pip.

```python
⬦⬦⬦ ~/git/wazuh-qa/tests/system/security ⨘ python3 package_vuln_scan.py -h
usage: package_vuln_scan.py [-h] (-r INPUT | -p) -o OUTPUT

optional arguments:
  -h, --help  show this help message and exit
  -r INPUT    specify requirements file path.
  -p          enable pip scan mode.
  -o OUTPUT   specify output file.
```

2021-07-27 08:14 UTC, AdriiiPRodri requested changes
We should investigate the possibility of using safety as a library, this way we would avoid depending on subprocess and having to hardcode the safety executable into subprocess call.

In addition, we should move the security folder and leave it next to the system folder, not inside it.

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +from datetime import datetime
Optimize imports

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +                                        '--version'],
```suggestion
                                         '--version'],
```

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +    json_data = []
```suggestion
```

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +    """
Change comments to numpy format

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +    """
Change comments to numpy format

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +    """
Change comments to numpy format

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +    """
Change comments to numpy format

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +        'report_date': datetime.now().strftime('%d/%m/%Y - %H:%M:%S'),
For dates, use ISO 8601 format

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +                    line = re.sub('[<|>|~]', '=', line)
```suggestion
                    line = re.sub('[<|>~]', '=', line)
```

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +                        package_version = max(re.findall('[0-9]+[.]+[0-9]*[.]*[0-9]', line))
```suggestion
                        package_version = max(re.findall('\d+\.+\d*\.*\d', line))
```

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +def run_report(output_file_path, input_file_path):
Shadows name output_file_path and input_file_path

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +def prepare_input(pip_mode, input_file_path):
Shadows name pip_mode and input_file_path

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +INPUT_FILE_PATH_TMP = 'input_file_tmp.txt'
For any kind of temporary file, it is recommended to use the tempfile library.

2021-07-27 08:14 UTC, AdriiiPRodri commented on tests/system/security/package_vuln_scan.py
> +                        help='specify output file.')
By default, the script should provide the information through the standard output and if specified, it should be sent to a file

2021-07-27 08:28 UTC, AdriiiPRodri commented
It is possible that we can use a local database, we should investigate this option.

![image](https://user-images.githubusercontent.com/15522808/127122198-529eb98f-0432-4f8a-a772-9ddf810cf76b.png)

2021-07-28 18:46 UTC, Kondent commented
# UPDATE
**Pytest support added:** now this script is used by pytest in which it fails if exist a vulnerable package in the requirements.txt provided.
It also can be called with three parameters:
**--repo:** name of the repository under wazuh. Default: 'wazuh'.
**--branch:** repository branch. Default: 'master'.
**--path:** path to requirements.txt under repository. Default: 'framework/requirements.txt'


# Examples:
## Successful 
```console
⬦⬦⬦ ~/git/wazuh-qa/tests/security ⨘ python3 -m pytest --repo wazuh --branch master --path framework/requirements.txt --disable-warnings
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/kondent/git/wazuh-qa/tests/security
plugins: asyncio-0.15.1, html-3.1.1, metadata-1.11.0, cov-2.12.1
collected 1 item                                                                                                                                                                             

test_package_vuln_scan/test_package_vuln_scan.py .                                                                                                                                     [100%]

================================================================================ 1 passed, 1 warning in 1.03s ================================================================================
```
## Failed
```console
⬦⬦⬦ ~/git/wazuh-qa/tests/security ⨘ python3 -m pytest --repo wazuh-qa --branch master --path requirements.txt --disable-warnings
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/kondent/git/wazuh-qa/tests/security
plugins: asyncio-0.15.1, html-3.1.1, metadata-1.11.0, cov-2.12.1
collected 1 item                                                                                                                                                                             

test_package_vuln_scan/test_package_vuln_scan.py F                                                                                                                                     [100%]

========================================================================================== FAILURES ==========================================================================================
___________________________________________________________________________________ test_package_vuln_scan ___________________________________________________________________________________

pytestconfig = <_pytest.config.Config object at 0x7fa51a862e20>

    def test_package_vuln_scan(pytestconfig):
        branch = pytestconfig.getoption('branch')
        repo = pytestconfig.getoption('repo')
        path = pytestconfig.getoption('path')
        requirements_url = f'https://raw.githubusercontent.com/wazuh/{repo}/{branch}/{path}'
        urlretrieve(requirements_url, REQUIREMENTS_TEMP_FILE.name)
        result = report_for_pytest(REQUIREMENTS_TEMP_FILE.name)
        REQUIREMENTS_TEMP_FILE.close()
        export_report(result, REPORT_FILE)
>       assert loads(result)['vulnerabilities_found'] == 0, f'Vulnerables packages were found, full report at: ' \
                                                            f'{REPORT_FILE}'
E       AssertionError: Vulnerables packages were found, full report at: test_package_vuln_scan/report_file.json
E       assert 27 == 0

test_package_vuln_scan/test_package_vuln_scan.py:20: AssertionError
================================================================================== short test summary info ===================================================================================
FAILED test_package_vuln_scan/test_package_vuln_scan.py::test_package_vuln_scan - AssertionError: Vulnerables packages were found, full report at: test_package_vuln_scan/report_file.json
===================================================================================== 1 failed in 3.60s ======================================================================================
```
## report_file.json
<details>
  <summary>Click to expand</summary>

```json
{
    "report_date": "2021-07-28T15:25:53.503866",
    "vulnerabilities_found": 27,
    "packages": [
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<6.2.2",
            "vuln_description": "libImaging/TiffDecode.c in Pillow before 6.2.2 has a TIFF decoding integer overflow, related to realloc. See: CVE-2020-5310.",
            "safety_id": "37779"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<6.2.2",
            "vuln_description": "libImaging/FliDecode.c in Pillow before 6.2.2 has an FLI buffer overflow. See: CVE-2020-5313.",
            "safety_id": "37782"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<6.2.2",
            "vuln_description": "libImaging/SgiRleDecode.c in Pillow before 6.2.2 has an SGI buffer overflow.",
            "safety_id": "37780"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<6.2.2",
            "vuln_description": "libImaging/PcxDecode.c in Pillow before 6.2.2 has a PCX P mode buffer overflow.",
            "safety_id": "37781"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<6.2.3",
            "vuln_description": "In Pillow before 6.2.3 and 7.x before 7.0.1, there are two Buffer Overflows in libImaging/TiffDecode.c. See: CVE-2020-10379.",
            "safety_id": "38450"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<6.2.3",
            "vuln_description": "In libImaging/PcxDecode.c in Pillow before 6.2.3 and 7.x before 7.0.1, an out-of-bounds read can occur when reading PCX files where state->shuffle is instructed to read beyond state->buffer. See: CVE-2020-10378.",
            "safety_id": "38449"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<7.0.0",
            "vuln_description": "In libImaging/Jpeg2KDecode.c in Pillow before 7.0.0, there are multiple out-of-bounds reads via a crafted JP2 file. See: CVE-2020-10994.",
            "safety_id": "38451"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<8.0.1",
            "vuln_description": "Pillow 8.0.1 updates FreeType used in binary wheels to 2.10.4 to fix CVE-2020-15999.",
            "safety_id": "40264"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<8.1.0",
            "vuln_description": "Pillow 8.1.0 fixes TIFF OOB Write error. CVE-2020-35654 #5175.",
            "safety_id": "40265"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<8.1.0",
            "vuln_description": "Pillow 8.1.0 includes a fix for Read Overflow in PCX Decoding. CVE-2020-35653 #5174.",
            "safety_id": "40270"
        },
        {
            "package_name": "pillow",
            "package_version": "6.2.0",
            "package_affected_version": "<8.1.0",
            "vuln_description": "Pillow 8.1.0 includes a fix for SGI De [...]

2021-07-29 14:20 UTC, AdriiiPRodri requested changes

2021-07-29 14:20 UTC, AdriiiPRodri commented on tests/security/test_package_vuln_scan/package_vuln_scan.py
> +        output (json): information about packages and vulnerabilities.
This parameter is a string
```suggestion
        output (str): information about packages and vulnerabilities.
```

2021-07-29 14:20 UTC, AdriiiPRodri commented on tests/security/test_package_vuln_scan/package_vuln_scan.py
> +        pip_mode_pocess = subprocess.run([python_bin, '-m', 'pip', 'freeze'], stdout=subprocess.PIPE,
```suggestion
        pip_mode_process = subprocess.run([python_bin, '-m', 'pip', 'freeze'], stdout=subprocess.PIPE,
```

2021-07-29 14:36 UTC, AdriiiPRodri submitted a review, later dismissed
LGTM!

2021-09-02 08:51 UTC, Rebits requested changes

2021-09-02 08:51 UTC, Rebits commented on tests/security/test_package_vuln_scan/test_package_vuln_scan.py
> +import tempfile
Add the Wazuh header:

```
# Copyright (C) 2015-2021, Wazuh Inc.
# Created by Wazuh, Inc. <info@wazuh.com>.
# This program is free software; you can redistribute it and/or modify it under the terms of GPLv2
```

2021-09-02 08:51 UTC, Rebits commented on tests/security/test_package_vuln_scan/test_package_vuln_scan.py
> +import tempfile
Maybe `test_package_vuln_scan`  is not a very accurate name due to this tests check used python packages in a requirements file.  Maybe `test_python_packages_vuln_scan.py` is more descriptive.

2021-09-06 08:32 UTC, Rebits approved these changes
LGTM

2021-09-06 09:13 UTC, Rebits commented
| Local-3.9.6 	| Status 	| Report 	|
|---	|---	|---	|
| R1 	| :green_circle:  	|  	[R1](https://github.com/wazuh/wazuh-qa/files/7114753/R1.zip) |
| R2 	| :green_circle: 	|  	[R2](https://github.com/wazuh/wazuh-qa/files/7114754/R2.zip) |
| R3 	| :green_circle: 	|  	 [R3](https://github.com/wazuh/wazuh-qa/files/7114755/R3.zip) |

2021-09-06 09:13 UTC, Rebits submitted a review, later dismissed
LGTM

2021-09-10 16:12 UTC, Kondent commented
# PR UPDATE
In the last commit, I did some minor fixes to adapt this test and tool to wazuh-qa repository file structure.
Overall, what I did:
* What started as a script, is a module with a couple of functions now. Available under `tools` directory and it's used by pytest.
* Few names changed (test, functions, etc).
* Read.me fixed.
Regards,
Alexis

2021-09-14 07:58 UTC, AdriiiPRodri requested changes

2021-09-14 07:58 UTC, AdriiiPRodri commented on tests/scans/dependencies/README.md
> +### scanning wazuh-qa requirements file:
```suggestion
### Scanning wazuh-qa requirements file:
```

2021-09-14 07:58 UTC, AdriiiPRodri commented on tests/scans/dependencies/README.md
> +### scanning wazuh requirements file with a specific output path:
```suggestion
### Scanning wazuh requirements file with a specific output path:
```

2021-09-14 07:58 UTC, AdriiiPRodri commented on tests/scans/dependencies/test_dependencies.py
> +def test_python_dependencies_vuln_scan(pytestconfig):
We should add here a docstring with a short description for the test, something like this:

`Check that the specified dependencies do not have any known vulnerabilities`

2021-09-14 12:08 UTC, AdriiiPRodri requested changes
Missing docs/index.md changes

2021-09-14 13:14 UTC, Kondent commented
> Missing docs/index.md changes

Related PR https://github.com/wazuh/wazuh-qa/pull/1659 is already handling this so I think it's no needed, let me know if I'm wrong

2021-09-14 14:29 UTC, Kondent commented
> > Missing docs/index.md changes
> 
> Related PR #1659 is already handling this so I think it's no needed, let me know if I'm wrong

Added those changes here too. PR updated.

2021-09-15 13:30 UTC, Rebits requested changes
Minor changes are required

2021-09-15 13:30 UTC, Rebits commented on README.md
> +    - `security`: security tests used to verify Wazuh Python code and dependencies.
```suggestion
    - `scans`: security tests used to verify Wazuh Python code and dependencies.
```

2021-09-15 13:30 UTC, Rebits commented on tests/scans/dependencies/test_dependencies.py
> +    requirements_url = f'https://raw.githubusercontent.com/wazuh/{repo}/{branch}/{requirements_path}'
```suggestion
    requirements_url = f"https://raw.githubusercontent.com/wazuh/{repo}/{branch}/{requirements_path}"
```

2021-09-15 13:30 UTC, Rebits commented on tests/scans/dependencies/test_dependencies.py
> +                                                        f'{report_path}'
```suggestion
                                                        f"{report_path}"
```

2021-09-15 13:30 UTC, Rebits commented on tests/scans/dependencies/conftest.py
> +    parser.addoption("--report-path", action="store", default=DEFAULT_REPORT_PATH)
```suggestion
    parser.addoption('--requirements-path', action='store', default=DEFAULT_REQUIREMENTS_PATH)
    parser.addoption('--report-path', action='store', default=DEFAULT_REPORT_PATH)
```

2021-09-15 13:30 UTC, Rebits commented on tests/scans/conftest.py
> +    parser.addoption("--repo", action="store", default=DEFAULT_REPOSITORY)
```suggestion
    parser.addoption('--branch', action='store', default=DEFAULT_BRANCH)
    parser.addoption('--repo', action='store', default=DEFAULT_REPOSITORY)
```

2021-09-15 13:43 UTC, Rebits commented
| Local-3.9.6 	| Status 	| 
|---	|---	|
| R1 	| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7170523/r1.zip) 	| 
| R2 	| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7170525/r2.zip) 	|  	
| R3 	| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7170526/r3.zip) 	|

2021-09-24 13:06 UTC, AdriiiPRodri submitted a review, later dismissed
LGTM

2021-09-29 07:27 UTC, davidjiglesias approved these changes

2021-09-29 07:42 UTC, Rebits commented
| Local-3.9.6 	| Status 	| 
|---	|---	|
| R1 	| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7249795/R1.zip)| 
| R2 	| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7249796/R2.zip)	|  	
| R3 	| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7249797/R3.zip)|

2021-09-29 07:42 UTC, Rebits approved these changes
LGTM

2021-10-01 08:14 UTC, merged