Integrate QADOCS into wazuh-qa framework
wazuh/wazuh-qa pull request #1854
Opened 2021-09-08 11:43 UTC by roronoasins

|Related issue|
|---|
|#1800|

## Description

QADOCS use is required not only for users but the QA framework. We decided to include this tool within the QA framework so there are no path dependencies.

It has been moved from `docs/DocGenerator` to `deps/wazuh_testing/qa_docs` and is installed running the `deps/wazuh_testing/setup.py`(npm modules installation needed, now working if you manually install them. It has to be changed).
```
(docgen) luisgr@luisgr-pc:~/work/wazuh-qa/deps/wazuh_testing$ qa-docs -h
usage: qa-docs [-h] [-s] [-v] [-t] [-d] [-i INDEX_NAME] [-l INDEX_NAME] [-T TEST_INPUT] [-o OUTPUT_PATH]

optional arguments:
  -h, --help      show this help message and exit
  -s              Run a sanity check
  -v              Print version
  -t              Test configuration
  -d              Enable debug messages.
  -i INDEX_NAME   Indexes the data to elasticsearch.
  -l LAUNCH_APP   Indexes the data and launch the application.
  -T TEST_INPUT   Test name to parse.
  -o OUTPUT_PATH  Output directory path.

```
The new usage is specified [here](https://github.com/wazuh/wazuh-qa/issues/1800#issuecomment-913558884).  The [wiki](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-DocGenerator-tool) will be updated once this it is merged.

The entire changes in QADOCS are located in #1800.

2021-09-08 13:30 UTC, jmv74211 requested changes
Good job, but a lot of changes are required. We will see all this in a live review.

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
> +            warnings.warn(f"Ipanclude th '{path}' doesn´t exist", stacklevel=2)
Typo here

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
> +            print(test)
This is necessary?

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
> +        '''
Use `"` in all these comments

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
> +        complete_test_name = self.conf.test_name + ".py"
```suggestion
        complete_test_name = f"{self.conf.test_name}.py" 
```

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
> +        print("dentro de run")
Be careful with these messages, and above it is in Spanish

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/doc_generator.py
> +            print("runnin")
??

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/lib/config.py
> +            self.test_info = self._config_data['Test info']
What is this variable? Does it have a blank space? `self._config_data['Test info']`

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/lib/config.py
> +        brief: Reads from the config file the keys to be printed from test info
Use infinitive in all comments `Read`

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/lib/config.py
> +        if 'Module info' in self._config_data:
Never use this type of variable. Always use lowercase and no blanks. Use `module_info` not `Module info`

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/lib/config.py
> +    SINGLE_TEST = 2
Add line break in the end of file

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/qa_docs/lib/index_data.py
> +            with open(file) as f:
Try not to use single-letter variables. The name of the variable must always be representative of its content

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/scripts/qa_docs.py
> +    LOG_PATH = os.path.join(folder, os.path.splitext(os.path.basename(__file__))[0]+".log")
Use fstrings instead of `+`

2021-09-08 13:30 UTC, jmv74211 commented on deps/wazuh_testing/wazuh_testing/scripts/qa_docs.py
> +        main()
We have to review this script file

2021-09-08 13:30 UTC, jmv74211 commented on tests/integration/test_vulnerability_detector/test_scan_results/test_scan_nvd_feed.py
> -    """
Why you have removed these comments?

2021-09-09 08:55 UTC, snaow approved these changes

2021-09-09 08:56 UTC, jmv74211 approved these changes

2021-09-09 08:56 UTC, merged