Change test_max_files_pers_second.py to match Docu Schema 2.0
wazuh/wazuh-qa pull request #1919
Opened 2021-09-22 16:36 UTC by Deblintrake09

|Related issue|
|---|
| #1883 - [FIM Windows Agent](https://github.com/wazuh/wazuh-qa/issues/1883) |

## Description

As part of Issue #1883, the Test file documentation has been updated to match the documentation [Schema 2.0](https://github.com/wazuh/wazuh-qa/issues/1694).

All changes done are modifications to comments to comply with Schema 2.0

### Test Results 
| Results | Status| Date | By 
|--|--|--|--|
| [ResultsMaxFPS.zip](https://github.com/wazuh/wazuh-qa/files/7205198/ResultsMaxFPS.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 |
| [ResultsMaxFPS2.zip](https://github.com/wazuh/wazuh-qa/files/7205200/ResultsMaxFPS2.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 |
| [ResultsMaxFPS3.zip](https://github.com/wazuh/wazuh-qa/files/7205201/ResultsMaxFPS3.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 |

2021-09-24 18:39 UTC, danisan90 commented
--2021/09/24--
This are the test results for `test_fim\test_files\test_max_files_per_second\test_max_files_per_second.py` with `--fim_mode="realtime" --fim_mode="whodata"` in the branch `test_max_files_docu`:

### Test Results 
| Results | Status| Date | By 
|--|--|--|--|
|[ResultsMaxFPS](https://github.com/wazuh/wazuh-qa/files/7227775/ResultsMaxFPS.zip) | 🔴  | 2021/09/24 | @danisan90 |
|[ResultsMaxFPS2](https://github.com/wazuh/wazuh-qa/files/7227776/ResultsMaxFPS2.zip)| 🔴 |2021/09/24 | @danisan90 |
|[ResultsMaxFPS3](https://github.com/wazuh/wazuh-qa/files/7227779/ResultsMaxFPS3.zip) | 🔴 ||2021/09/24 | @danisan90 |


The tests `test_fim\test_files\test_max_files_per_second\test_max_files_per_second.py` where also executed in the branch `1873-4.2.1-fim-windows-agent`. This are the results with ` --fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"`:

### Test Results 
| Results | Status| Date | By 
|--|--|--|--|
|[ResultsMaxFPSb](https://github.com/wazuh/wazuh-qa/files/7227802/ResultsMaxFPSb.zip) | 🔴  | 2021/09/24 | @danisan90 |
|[ResultsMaxFPS2b](https://github.com/wazuh/wazuh-qa/files/7227805/ResultsMaxFPS2b.zip)| 🔴  | 2021/09/24 | @danisan90 |

2021-09-24 18:48 UTC, danisan90 requested changes
PR needs to be checked again due to failures in executions. Test result in this [comment.](https://github.com/wazuh/wazuh-qa/pull/1919#issuecomment-926844035)

2021-09-28 12:28 UTC, damarisg requested changes

2021-09-28 12:28 UTC, damarisg commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
> +    - Ubuntu Xenial
Add the Windows platforms with all os_versions versions, or remove all os_versions of Linux and Windows, and in the future, we will add it.

2021-09-28 12:28 UTC, damarisg commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
> +    -
Remove empty lines.

2021-09-28 12:28 UTC, damarisg commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
> +        4.2
This needs to be added in the future with more data because we don't know what the minimum supported version is.

2021-09-28 12:28 UTC, damarisg commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
>      """
Remove these lines.

2021-09-28 12:28 UTC, damarisg commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
> +        -
Remove empty lines.

2021-09-28 19:24 UTC, damarisg commented
Closed because it has some changes that are included in #1934.
For that reason, this PR is deprecated.

2021-09-28 19:24 UTC, closed without merging