Add cluster logs tests
wazuh/wazuh-qa pull request #2166
Opened 2021-11-03 14:00 UTC by Selutario

|Related issue|
|---|
| Closes #1940 |

## Description

This PR adds four new tests to analyze the cluster logs. Those tests are:
- **Test_cluster_connection:** It checks if all the nodes connect correctly to the master and if any worker disconnects at some point.
- **Test_cluster_error_logs:** Checks if the word `error` (case insensitive) appears in the cluster.log of any node. All errors are later attached in the `report.html`.
- **Test_cluster_logs_order:** Check in each worker that the logs for each task appear in the correct order. If any log is skipped or duplicated, the test fails. Useful for finding task overlapping or other similar problems. The logs found in case of error are attached in the report.html together with the expected logs, for each failed node.
- **Test_cluster_sync:** Checks if Integrity sync takes place multiple times in a row on a worker with the same number of files. This could mean that synchronization is not taking place, thus the test will fail.

## Configuration options

- `--artifacts_path`: Path where cluster logs can be found inside each node folder. It should follow the structure below:
    ```.
    ├── master
    │   └── logs
    │       └── cluster.log
    ├── worker_x
    │   └── logs
    │       └── cluster.log
    └── ...
    ```
- `--html=report.html`: Create a html report with the test results.
- `--self-contained-html`: Store all the necessary data for the report inside the html file.

## Logs example

A `report.html` can be created including the results of all these tests, together with the performance test developed in #2130:
![image](https://user-images.githubusercontent.com/23361101/140073717-a4cfb809-1671-4fc8-b1a2-02148cd11c18.png)

The error logs of the `test_cluster_error_logs` test are attached in the details section:
![image](https://user-images.githubusercontent.com/23361101/140073871-8c95ae26-6395-4827-a0ab-35a1e3f74ed6.png)

The same happens with the incorrect order logs of the `test_cluster_logs_order` test:
![image](https://user-images.githubusercontent.com/23361101/140073990-6b697c5d-91f2-42c7-947c-d7685fd6f833.png)

2022-01-17 08:43 UTC, AdriiiPRodri requested changes

2022-01-17 08:43 UTC, AdriiiPRodri commented on deps/wazuh_testing/wazuh_testing/tools/utils.py
> +            return self
```suggestion
        return self
```

2022-01-17 08:43 UTC, AdriiiPRodri commented on tests/performance/test_cluster/test_cluster_logs/test_cluster_connection/README.md
> +- Fail if any node disconnected after a successful connection.
```suggestion
- Fail if any node is disconnected after a successful connection.
```

2022-01-17 08:43 UTC, AdriiiPRodri commented on tests/performance/test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py
> +    return False
```suggestion
    return True if any(line in error_str for line in white_list) else False
```

2022-01-17 08:43 UTC, AdriiiPRodri commented on tests/performance/test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py
> +def error_in_white_list(error_str):
Missing docstring

2022-01-17 08:43 UTC, AdriiiPRodri commented on tests/performance/test_cluster/test_cluster_logs/test_cluster_logs_order/README.md
> +- Fail if the any log is printed when it shouldn't.
```suggestion
- Fail if any log is printed when it shouldn't.
```

2022-01-18 15:36 UTC, AdriiiPRodri submitted a review, later dismissed

2022-01-19 08:09 UTC, davidjiglesias approved these changes

2022-01-19 11:04 UTC, Rebits requested changes
Awesome job, but some changes are required.

2022-01-19 11:04 UTC, Rebits commented on tests/performance/test_cluster/test_cluster_logs/test_cluster_sync/README.md
> +The test needs to receive one parameter in order to be run. If said parameter is not specified, the test will fail. The required parameter is:
```suggestion
The test needs to receive one parameter in order to be run. If this parameter is not specified, the test will fail. The required parameter is:
```

2022-01-20 13:30 UTC, Selutario commented on tests/performance/test_cluster/README.md
> +python3 -m pytest . --artifacts_path='/home/selu/Descargas/cluster_performance/59' --n_agents=50000 --n_workers=10 --html=report.html --self-contained-html
Done!

2022-01-27 18:07 UTC, merged