Authd replacement configurations QA
wazuh/wazuh-qa pull request #2171
Opened 2021-11-04 12:51 UTC by palaciosjeremias

|Related issue|
|---|
|#2050|

## Description
As part of the epic https://github.com/wazuh/wazuh-qa/issues/2050, we created all the necessary changes to cope with the new feature developed in https://github.com/wazuh/wazuh/issues/9550.
In this PR we:
- Fixed legacy Wazuh-DB test cases that didn´t expect the new disconnection_time in **gobal.db**.
- Fixed legacy Authd tests that expected a raw replacement of the agent and now were rejected.
- Adapted all the **force_insert** and **force_time** configurations to the new **force** block .
- Reformulated key_hash test to check the correct parse of the **K** option in the enrollment message.
- Created a new test to validate the correct behavior of Authd with all the valid force **options** configuration (test_authd_force_options.py).
- Created a new test to validate the error handling of Authd with invalid force **options** (test_authd_force_options_invalid_config.py).

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the DocGenerator schema v2.0.
- [ ] DocGenerator sanity check is executed in the new code without errors.

2021-11-04 15:44 UTC, palaciosjeremias commented
Successful execution of authd tests: https://ci.wazuh.info/job/Test_integration/15012/
Successful execution of wazuhdb tests: https://ci.wazuh.info/job/Test_integration/15014/

2021-11-04 19:21 UTC, MiguelazoDS commented
DocGenerator sanity without errors.

![image](https://user-images.githubusercontent.com/13010397/140405901-5d1f393a-62de-4b88-99df-07cfc41d74fd.png)

2021-11-05 08:28 UTC, juliamagan requested changes

2021-11-05 08:28 UTC, juliamagan commented on tests/integration/test_authd/force_options/README.md
> +These tests aim to check the correct behavior of Authd under the different possible configurations of the force block.
This file shouldn't be here

2021-11-05 08:31 UTC, juliamagan commented
## 05/11/2021

### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.0-0.commitf39f878.x86_64.rpm|


## Testing

### tests/integration/test_authd

|  OS    | Local |Jenkins     | Notes
|---      |---    |---    |---  |
| PS1   | 🔵   | | 
| PS2   |  🔵   | | |
| PS3   |   🔵  |   | |


* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

2021-11-05 09:38 UTC, Rebits approved these changes
GJ, some changes should be implemented in order to improve readability or fit with the repository standards. Due to the urgency of this development, these changes should be implemented in a separate Issue/PR in which we could solve other `test_authd` module errors.

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/authd.py
> +    return result, err_msg
This function is a little hard to read and it has code repetition. In future revisions of this module we could use something like the following:

```suggestion
def get_authd_response_values(response):
    authd_response_dict = {}
    try: 
        response = response.split(sep=' ', maxsplit=1)
        status, message = response[0:1]
        
        authd_response_dict['status'] = status
        authd_response_dict['message'] = message
        
        if status == 'success':
            agent_key = message.split('\'')[1::2][0].split()
            id, name, ip, key = agent_key[0:4]
            authd_response_dict['id'] = id
            authd_response_dict['name'] = name
            authd_response_dict['ip'] = ip
            authd_response_dict['key'] = key
    except:
        raise IndexError(f"Authd response {response} does not contains expected values: {str(values)}")
    return authd_response_dict
    
        
def validate_authd_response(response, expected):
    """
    Validates if the different items of an Authd response are as expected. Any item inexistent in expected won't
    be validated.

    Args:
        response (str): The Authd response to be validated.
        expected (dict): Dictionary with the items to validate.
    """
    authd_response_dict = get_authd_response_values(response)

    result = 'success'
    err_msg = ''
    
    for expected_key in expected.keys():
        if expected_key == 'message':
            if re.match(expected[expected_key], authd_response_dict[message]) is None:
                return 'error', f"Invalid 'message': '{message}' received, '{expected['message']}' expected"
        elif expected_key in ['status', 'id', 'name', 'ip', 'key']:
            if expected_key == 'status':
                expected_value = 'OSSEC' if expected['status'] == 'success' else 'ERROR'
            else:
                expected_value = expected[expected_key]
            
            result, err_msg = validate_argument(authd_response_dict[expected_value], expected_value, expected_key)
        else:
            raise Exception('Invalid expected status')

    return result, err_msg
```

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/authd.py
> +        raise Exception('Unable to clean agents')
Maybe is more intuitive to move this to `wazuh_db` due this is not properly an authd related function.

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/authd.py
> +                       disconnection_time=0):
```suggestion
def insert_agent_in_db(id=1, name='TestAgent', ip='any', registration_time=0, connection_status=0,
                       disconnection_time=0):
```

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/authd.py
> +        raise Exception(f'Unable to add agent {id}')
Same that before, these functions could be useful for the rest of the modules and they are more related with `wazuh_db` module.

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/authd.py
> +        raise Exception(f'Unable to add agent {id}')
```suggestion
def insert_agent_in_db(id=1, name="TestAgent", ip="any", registration_time=0, connection_status=0,
                       disconnection_time=0):
    """
    Write agent in global.db
    """
    insert_command = f'global insert-agent {{"id":{id},"name":"{name}","ip":"{ip}","date_add":{registration_time}}}'
    update_command = f'global sql UPDATE agent SET connection_status = "{connection_status}",\
                       disconnection_time = "{disconnection_time}" WHERE id = {id};'
    try:
        query_wdb(insert_command)
        query_wdb(update_command)
    except Exception:
        raise Exception(f"Unable to add agent {id}")
```

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/authd.py
> +    keys_file.close()
Fixtures should be placed in `test_authd` conftest.

2021-11-05 09:38 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/tools/services.py
> +
```suggestion
```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/conftest.py
> +
```suggestion
```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/conftest.py
>  from wazuh_testing.tools import LOG_FILE_PATH, CLIENT_KEYS_PATH
```suggestion

from wazuh_testing.tools import LOG_FILE_PATH, CLIENT_KEYS_PATH
```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/force_options/test_authd_force_options.py
> +import pytest
```suggestion
import pytest

```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/force_options/test_authd_force_options.py
> +    group_name = file.split(".")[0]
```suggestion
    group_name = file.split('.')[0]
```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/force_options/test_authd_force_options.py
> +receiver_sockets_params = [(("localhost", 1515), 'AF_INET', 'SSL_TLSv1_2')]
```suggestion
receiver_sockets_params = [(('localhost', 1515), 'AF_INET', 'SSL_TLSv1_2')]
```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/force_options/test_authd_force_options_invalid_config.py
> +    group_name = file.split(".")[0]
```suggestion
    group_name = file.split('.')[0]
```

2021-11-05 09:38 UTC, Rebits commented on tests/integration/test_authd/force_options/test_authd_force_options_invalid_config.py
> +        control_service("restart", daemon=DAEMON_NAME)
```suggestion
        control_service('restart', daemon=DAEMON_NAME)
```

2021-11-05 15:27 UTC, DProvinciani commented
All the suggestions made by the reviewers, as they are not critical, will be implemented as part of the issue https://github.com/wazuh/wazuh-qa/issues/2184 after integrating this PR.

2021-11-05 23:44 UTC, snaow commented
LGTM. GJ Everyone.

2021-11-05 23:45 UTC, merged

2021-11-08 23:41 UTC, palaciosjeremias commented on deps/wazuh_testing/wazuh_testing/authd.py
> +    command = ""
Fixed