Implement Authd tests code improvements.
wazuh/wazuh-qa pull request #2192
Opened 2021-11-09 15:28 UTC by palaciosjeremias

|Related issue|
|---|
|#2184|

## Description
This PR implements all the pending suggestions from https://github.com/wazuh/wazuh-qa/pull/2171.
Basically:
- It fixes all the code style observations.
- Relocates **Authd.py** methods related to **Wazuh-db** into **wazuh-db.py**
- Relocates **Authd.py** fixtures into the **Authd** contest .
- Refactor **validate_authd_response()** logic to be more readable.
- Removes a deprecated README file with the test group definition.

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [X] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [X] Python codebase is documented following the Google Style for Python docstrings.
- [X] The test is documented in following the DocGenerator schema V2.0

2021-11-09 20:26 UTC, palaciosjeremias commented
Succesful execution of Authd tests on Jenkins:
https://ci.wazuh.info/job/Test_integration/15575/

2021-11-10 16:33 UTC, juliamagan requested changes

2021-11-10 16:33 UTC, juliamagan commented on tests/integration/test_authd/conftest.py
> +        name = agent['name'] if 'name' in agent else f'TestAgent{id}'
```suggestion
        name = agent['name'] if 'name' in agent else f"TestAgent{id}"
```

2021-11-10 16:33 UTC, juliamagan commented on tests/integration/test_authd/conftest.py
> +        keys_file.write(f'{id} {name} {ip} {key}\n')
```suggestion
        keys_file.write(f"{id} {name} {ip} {key}\n")
```

2021-11-10 16:37 UTC, juliamagan commented
# 10/11/2021

## Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.0-2192.authd.improve.x86_64.rpm|

## Testing

### tests/integration/test_authd

|  OS    | Local | Jenkins     | Notes
|---      |---    |---    |---  |
| PS1   |  ||
| PS2   |  |  |
| PS3   |  |  |   |

### tests/integration/test_wazuh_db

|  OS    | Local | Jenkins     | Notes
|---      |---    |---    |---  |
| PS1   |  | |
| PS2   |  |  |
| PS3   |   |  |

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

2022-01-27 18:09 UTC, merged