Remove expected `force` option from the received request in the `agent_enrollment` system tests
wazuh/wazuh-qa pull request #2289
Opened 2021-12-01 16:15 UTC by yanazaeva

|Related issue|
|---|
|#2283|

## Description

This closes #2282. The aim of this PR is to update the expected log in the `agent_enrollment` system test. Before 4.3.0 version the expected request contained an `int` type `force` field, but in 4.3.0, it is no longer necessary to specify this value as the default one, or the established one will be taken from the master. We will only receive this field if we manually specify it in the request.

2021-12-07 10:19 UTC, AdriiiPRodri approved these changes

2021-12-09 10:36 UTC, davidjiglesias approved these changes

2021-12-09 10:45 UTC, davidjiglesias requested changes
We need some further investigation about the second error. That timeout might be an indication that the agent is taking more time to restart in wazuh v4.3.0 than it should, or more than we are currently accepting.

2021-12-14 10:38 UTC, davidjiglesias approved these changes

2021-12-15 08:26 UTC, Rebits commented
### 15/12/21

| `test_agent_enrollment.py` | Report |
| --- | --- |
| R1|  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7717573/R1-2289.zip)
| R2|  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7717575/R2-2289.zip)
| R3| [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7717576/R3-2289.zip)

2021-12-15 08:26 UTC, Rebits approved these changes
LGTM

2021-12-16 15:03 UTC, merged