Fixed a flaw regarding subprocess calls
wazuh/wazuh-qa pull request #2360
Opened 2021-12-17 20:58 UTC by Kondent

|Related issue|
|---|
| #2330 |

## Description
* Wazuh main issue: https://github.com/wazuh/wazuh/issues/10144.
* Wazuh main PR: https://github.com/wazuh/wazuh/pull/10740.
* Flaw status:
  * `B603`:
    * `wazuh/framework/wazuh/core/cluster/cluster.py`: **FALSE POSITIVE**
    * `wazuh/framework/wazuh/core/common.py`: **FALSE POSITIVE**
    * `wazuh/framework/wazuh/core/configuration.py`: **FALSE POSITIVE**
    * `wazuh/framework/scripts/wazuh-logtest.py`: **FALSE POSITIVE**
    * `wazuh/framework/wazuh/core/utils.py`: **FIXED**
  * `B404`:
    * `wazuh/framework/scripts/wazuh-logtest.py`: **FALSE POSITIVE**
    * `wazuh/framework/wazuh/core/cluster/cluster.py`: **FALSE POSITIVE**
    * `wazuh/framework/wazuh/core/common.py`: **FALSE POSITIVE**
    * `wazuh/framework/wazuh/core/configuration.py`: **FALSE POSITIVE**

Under this development, the related possible code flaw is set as solved using [Code Analysis Tool](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans/code_analysis).

## Tests

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.

2021-12-22 10:20 UTC, mcarmona99 approved these changes
LGTM

2021-12-27 15:30 UTC, Rebits requested changes
GJ, but minor changes are required

2021-12-27 15:30 UTC, Rebits commented on tests/scans/code_analysis/known_flaws/known_flaws_framework.json
> +        },
The false positive `B607` id case should be added:
```suggestion
        {
            "code": "     \"\"\"\n     return set(str(check_output(['hostname', '--all-ip-addresses']).decode()).split(\" \")[:-1])\n \n",
            "filename": "framework/wazuh/core/cluster/cluster.py",
            "issue_confidence": "HIGH",
            "issue_severity": "LOW",
            "issue_text": "subprocess call - check for execution of untrusted input.",
            "line_number": 42,
            "line_range": [
                42
            ],
            "more_info": "https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html",
            "test_id": "B603",
            "test_name": "subprocess_without_shell_equals_true"
        },
        {
            "code": "     \"\"\"\n     return set(str(check_output(['hostname', '--all-ip-addresses']).decode()).split(\" \")[:-1])\n \n",
            "filename": "framework/wazuh/core/cluster/cluster.py",
            "issue_confidence": "HIGH",
            "issue_severity": "LOW",
            "issue_text": "Starting a process with a partial executable path",
            "line_number": 39,
            "line_range": [
                39
            ],
            "more_info": "https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html",
            "test_id": "B607",
            "test_name": "start_process_with_partial_path"
        },

2021-12-27 17:21 UTC, Rebits approved these changes
LGTM

2022-01-05 10:30 UTC, merged