Analysisd - add new test to check analysisd socket properties
wazuh/wazuh-qa pull request #2405
Opened 2021-12-24 12:02 UTC by fernandolojano

|Related issue|
|---|
|#1850|

## Description
closes #1850

This PR adds a new test for Analysisd requested on the issue #1850. As for now, it works properly as it's able to detect the changes of the file time and inode whenever
they change. 

This test check:
- The Inode value of the queue socket can't change after the Analysisd daemon is set in the testing configuration mode 
- The File time value of the queue socket can't change after the Analysisd daemon is set in the testing configuration mode 

## Tests
- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2021-12-27 14:07 UTC, mauromalara requested changes

2021-12-28 21:00 UTC, mauromalara requested changes

2021-12-31 22:09 UTC, mauromalara commented
|CentOS: Manager|Local|Jenkins|
|---|---|---|
|PS1|[:red_circle: ](https://github.com/wazuh/wazuh-qa/files/7797129/R1-test.queue.socket.properties.mauro.tar.gz)|[:red_circle: ](https://ci.wazuh.info/job/Test_integration/18168/)
|PS2|[:red_circle: ](https://github.com/wazuh/wazuh-qa/files/7797130/R2-test.queue.socket.properties.mauro.tar.gz)|[:red_circle: ](https://ci.wazuh.info/job/Test_integration/18173/)
|PS3|[:red_circle: ](https://github.com/wazuh/wazuh-qa/files/7797131/R3-test.queue.socket.properties.mauro.tar.gz)|[:red_circle: ](https://ci.wazuh.info/job/Test_integration/18174/)

|Note|
|---|
|It fails apparently because the bug was not fixed|
|@fernandolojano please, check the results with the core team to determine if is an error or a bug of Wazuh.|

2022-01-17 14:14 UTC, mauromalara approved these changes

2022-01-17 17:00 UTC, mauromalara requested changes
@fernandolojano please, modify the code following the PEP8 guidelines. You can follow [this](https://code.visualstudio.com/docs/python/linting) guide to doing it, take into account that you must change the `max-line-length` argument following [this guide](https://code.visualstudio.com/docs/python/linting#_pycodestyle-pep8)

2022-01-21 11:31 UTC, mauromalara submitted a review, later dismissed

2022-02-03 22:05 UTC, mauromalara commented
## 03/02/2022
### Package
| Version | Revision | Link|
|---|---|---|
|4.4.0|0.40400.20220202|[package](https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/staging/yum/wazuh-manager-4.4.0-0.40400.20220202.x86_64.rpm)


## Testing

### Analysisd

|  OS  | Local   | Jenkins | Notes |
|---|---|---|---|
| R1 | [🔴](https://github.com/wazuh/wazuh-qa/files/7998482/R1-1850-centos-manager.tar.gz) | [🔴](https://ci.wazuh.info/job/Test_integration/19984/artifact/manager_tests_Test_integration_B19984_20220203201525.txt) - [Build](https://ci.wazuh.info/job/Test_integration/19984/) | **Local failure:** The inode value for the socket  `/var/ossec/queue/sockets/queue` has changed -- **Jenkins failure:** The modification time property value for the socket `/var/ossec/queue/sockets/queue` has changed |
| R2 | [🔴](https://github.com/wazuh/wazuh-qa/files/7998483/R2-1850-centos-manager.tar.gz) | [🔴](https://ci.wazuh.info/job/Test_integration/19985/artifact/manager_tests_Test_integration_B19985_20220203201619.txt) - [Build](https://ci.wazuh.info/job/Test_integration/19985/) | Same as before |
| R3 | [🔴](https://github.com/wazuh/wazuh-qa/files/7998485/R3-1850-centos-manager.tar.gz) | [🔴](https://ci.wazuh.info/job/Test_integration/19986/artifact/manager_tests_Test_integration_B19986_20220203201651.txt) - [Build](https://ci.wazuh.info/job/Test_integration/19986/) | Same as before |

| NOTES (important) |
|---|
| @snaow it seems that the bug was not fixed. This may be a **stopper**. The test fails in both executions. In Jenkins, the `mtime` changes but locally the `inode` changes instead. The package used is the same. |

2022-02-03 22:06 UTC, mauromalara submitted a review, later dismissed

2022-02-04 20:31 UTC, jnasselle reviewed
There's no stopper and this could be validated by manual testing (`ls -li` to get inodes and `stat -c '%y'` to get modification time).
I propose a rearrangement of this test in the next branch: https://github.com/wazuh/wazuh-qa/tree/fix-1850-check-queue-socket-status-test

Hope this helps!
Nico

2022-02-21 19:42 UTC, mauromalara commented
> There's no stopper and this could be validated by manual testing (`ls -li` to get inodes and `stat -c '%y'` to get modification time). I propose a rearrangement of this test in the next branch: https://github.com/wazuh/wazuh-qa/tree/fix-1850-check-queue-socket-status-test
> 
> Jenkins: Tested using v4.2.2 staging packages Local: Tested using v4.4.0 source installation
> 
> CentOS: Manager	Local	Jenkins
> PS1	[green_circle ](https://github.com/wazuh/wazuh-qa/files/8006141/R1-test.queue.socket.properties.nico.zip)	[green_circle](https://ci.wazuh.info/job/Test_integration/20150)
> PS2	[green_circle](https://github.com/wazuh/wazuh-qa/files/8006142/R2-test.queue.socket.properties.nico.zip)	[green_circle](https://ci.wazuh.info/job/Test_integration/20151)
> PS3	[green_circle](https://github.com/wazuh/wazuh-qa/files/8006143/R3-test.queue.socket.properties.nico.zip)	[green_circle](https://ci.wazuh.info/job/Test_integration/20152)
> Hope this helps! Nico

Hi @jnasselle,

Thanks for your help, I'll check it and apply the necessary changes.

2022-02-21 22:21 UTC, mauromalara commented
# 21/02/2022
## Package
| Version | Revision | Link|
|---|---|---|
|4.4.0|0.40400.20220202|[package](https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/staging/yum/wazuh-manager-4.4.0-0.40400.20220202.x86_64.rpm)

## Testing

|CentOS: Manager|Local|Jenkins|
|---|---|---|
|PS1|[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8112345/R1-1850-centos-manager.zip)|[:green_circle:]()
|PS2|[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8112346/R2-1850-centos-manager.zip)|[:green_circle:]()
|PS3|[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8112347/R3-1850-centos-manager.zip)|[:green_circle:]()

2022-03-11 12:42 UTC, Rebits requested changes
GJ, but some changes are required

2022-03-11 12:42 UTC, Rebits commented on CHANGELOG.md
> +- Analysisd - add new test to check analysisd socket properties ([#2405](https://github.com/wazuh/wazuh-qa/pull/2405))
```suggestion
- Analysisd - add a new test to check analysisd socket properties ([#2405](https://github.com/wazuh/wazuh-qa/pull/2405))
```

2022-03-11 12:42 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/db_interface/__init__.py
> +            raise Exception('The wdb socket is not up. wazuh-db was restarted but the socket was not found')
This logic should be performed in other fixtures or functions. This logic does not fit most of the use cases of this function so it is better to handle daemons up in test fixtures.

2022-03-11 12:42 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/db_interface/__init__.py
> +        # Send the query request
```suggestion
```

2022-03-11 12:42 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/db_interface/__init__.py
> +    # Create and open the socket connection with wazuh-db socket
```suggestion
```

2022-03-11 12:42 UTC, Rebits commented on tests/integration/test_analysisd/test_queue_socket_properties/test_queue_socket_properties.py
> +
```suggestion
```

2022-03-11 12:42 UTC, Rebits commented on tests/integration/test_analysisd/test_queue_socket_properties/test_queue_socket_properties.py
> +    check_daemon_status(running_condition=True, target_daemon='wazuh-analysisd')
Move this fixture to analysisd conftest.

2022-03-11 12:42 UTC, Rebits commented on tests/integration/test_analysisd/test_queue_socket_properties/test_queue_socket_properties.py
> +                 of the queue socket file are changed.
```suggestion
    description: Check if after running the configuration test of 'wazuh-analysisd' the properties
                 of the queue socket file are changed.
```

2022-03-14 23:47 UTC, mauromalara commented
## 14/03/2022
### Package
| Version | Revision | Link|
|---|---|---|
| 4.4.0 | 0.40400.20220202 | [download](https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/staging/yum/wazuh-manager-4.4.0-0.40400.20220202.x86_64.rpm) |


## Testing

### Analysisd

|  OS  | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| R1   | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8249093/R1-centos-manager-2405.tar.gz)  |  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/23531/artifact/manager_tests_Test_integration_B23531_20220314213521.txt) - [Build](https://ci.wazuh.info/job/Test_integration/23531)   | |
| R2   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8249098/R2-centos-manager-2405.tar.gz)  |  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/23532/artifact/manager_tests_Test_integration_B23532_20220314213654.txt) - [Build](https://ci.wazuh.info/job/Test_integration/23532/)   | |
| R3   | [:green_circle:](link-to-the-report-r3)   |  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/23533/artifact/manager_tests_Test_integration_B23533_20220314213724.txt) - [Build](https://ci.wazuh.info/job/Test_integration/23533/)

2022-03-16 10:18 UTC, Rebits commented
## 16/03/2022
### Package
| Version | Revision | Link|
|---|---|---|
|4.3.0| 1| https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.3.0-1.x86_64.rpm |

## Testing

### `test_analysisd`
|  OS  | Local        | Notes
|---    |---    |---  |
| R1   | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8261127/R3-2405-analysisd-socket-properties.tar.gz)  | 
| R2   | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8261128/R2-2405-analysisd-socket-properties.tar.gz)   | 
| R3   |  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8261129/R1-2405-analysisd-socket-properties.tar.gz)   | |






* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

2022-03-17 17:22 UTC, Rebits approved these changes
LGTM

2022-03-17 17:22 UTC, merged