Cluster system tests for agent groups
wazuh/wazuh-qa pull request #2645
Opened 2022-03-08 14:21 UTC by yanazaeva

|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/2479|

## Description

This closes https://github.com/wazuh/wazuh-qa/issues/2479. The aim of this issue is to update the already existing system tests as well as create a new one to check the proper synchronization.

2022-03-09 08:35 UTC, AdriiiPRodri requested changes
We need to add tests to check the task master agent-groups get, master agent-groups send and worker agent-groups recv.

2022-03-09 08:35 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_logs_order/data/Agent-groups_sync.yml
> +  tag: 'All chunks sent.*'
```suggestion

```

2022-03-10 15:06 UTC, AdriiiPRodri requested changes

2022-03-10 15:06 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py
> +    all_workers = {'Master': LogsOrder().logs_order}
```suggestion
    master = {'Master': LogsOrder().logs_order}
```

2022-03-10 15:06 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/README.md
> +| 5 | 4s |
Check time again

2022-03-10 15:06 UTC, AdriiiPRodri commented on tests/system/test_cluster/test_agent_groups/data/add_messages.yml
> +    timeout: 60
```suggestion
```

2022-03-11 08:19 UTC, AdriiiPRodri requested changes

2022-03-11 08:19 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/README.md
> +    └── ...
This is the master README

2022-03-11 08:19 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/README.md
> +- The cluster does not skip any task.
```suggestion
- The cluster does not skip any task. The master node does not skip any cluster's task.
```

2022-03-11 08:19 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/README.md
> +        all_workers = {'Master': LogsOrder().logs_order}
```suggestion
        all_managers = {'Master': LogsOrder().logs_order}
```

2022-03-11 08:19 UTC, AdriiiPRodri commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/README.md
> +E                            - Found log: Fittttnished in 0.004s (1 chunks updated).
This log is correct?

2022-03-11 09:09 UTC, AdriiiPRodri approved these changes

2022-03-11 09:38 UTC, yanazaeva commented
The testing was done using the following branches:

|Wazuh branch| Wazuh-QA branch|
|:--:|:--:|
|[dev-10771-agent-groups-files-to-wazuh-db](https://github.com/wazuh/wazuh/tree/dev-10771-agent-groups-files-to-wazuh-db)|[feature/2479-cluster-system-tests-for-agent-groups](https://github.com/wazuh/wazuh-qa/tree/feature/2479-cluster-system-tests-for-agent-groups)|

2022-03-11 09:40 UTC, AdriiiPRodri approved these changes

2022-03-14 10:47 UTC, Selutario requested changes

2022-03-14 10:47 UTC, Selutario commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-groups_recv.yml
> +# Synchronization needed.
Update this comment

2022-03-14 10:47 UTC, Selutario commented on tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/data/Agent-groups_recv.yml
> +  tag: 'There is no data requiring synchronization in the local database.*'
This is a debug2 log

2022-03-14 16:14 UTC, juliamagan requested changes
GJ, but some changes are required

2022-03-14 16:14 UTC, juliamagan commented on tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
> +    This test is no longer in use, but it could be useful in the future.
We should delete this test if it is no longer in use. The test already exists in `4.3` if we need it in the future.

2022-03-15 11:21 UTC, juliamagan submitted a review, later dismissed
LGTM

2022-03-16 08:54 UTC, juliamagan submitted a review, later dismissed

2022-03-16 11:07 UTC, juliamagan commented
## 16/03/2022
### Testing
|Wazuh branch| Wazuh-QA branch|
|:--:|:--:|
|[dev-10771-agent-groups-files-to-wazuh-db](https://github.com/wazuh/wazuh/tree/dev-10771-agent-groups-files-to-wazuh-db)|[feature/2479-cluster-system-tests-for-agent-groups](https://github.com/wazuh/wazuh-qa/tree/feature/2479-cluster-system-tests-for-agent-groups)|

#### tests/system/test_cluster/test_agent_groups/test_agent_groups.py
||Results|
|:--:|:--:|
|R1|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8261470/R1-test-agent-groups.zip)
|R2|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8261471/R2-test-agent-groups.zip)
|R3|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8261472/R3-test-agent-groups.zip)

#### tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

#### tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

#### tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

#### tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/test_cluster_worker_logs_order.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

2022-03-25 17:50 UTC, yanazaeva commented
## 25/03/2022
### Testing
|Wazuh branch| Wazuh-QA branch|
|:--:|:--:|
|[dev-10771-agent-groups-files-to-wazuh-db](https://github.com/wazuh/wazuh/tree/dev-10771-agent-groups-files-to-wazuh-db)|[feature/2479-cluster-system-tests-for-agent-groups](https://github.com/wazuh/wazuh-qa/tree/feature/2479-cluster-system-tests-for-agent-groups)|

#### tests/system/test_cluster/test_agent_groups/test_agent_groups.py
||Results|
|:--:|:--:|
|R1|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8352707/1.zip)
|R2|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8352708/2.zip)
|R3|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8352709/3.zip)

#### tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
||Results|
|:--:|:--:|
|R1|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8352789/1.zip)
|R2|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8352790/2.zip)
|R3|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8352791/3.zip)

#### tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

#### tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

#### tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/test_cluster_worker_logs_order.py
||Results|
|:--:|:--:|
|R1|
|R2|
|R3|

2022-03-30 10:51 UTC, yanazaeva commented
## Update

We repeated the tests, with the pull mentioned above merged and with the following [artifacts](https://github.com/wazuh/wazuh-qa/files/8379792/artifacts.zip), which do not contain any restart. 

#### tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py
||Results|
|:--:|:--:|
|R1|[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8379775/1.zip)
|R2|[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8379776/2.zip)
|R3|[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8379777/3.zip)

#### tests/reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order/test_cluster_worker_logs_order.py
||Results|
|:--:|:--:|
|R1|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8379760/1.zip)
|R2|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8379761/2.zip)
|R3|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8379762/3.zip)

2022-04-06 12:06 UTC, Rebits commented
## 06/4/2022

### Testing
|Wazuh branch| Wazuh-QA branch|
|:--:|:--:|
|[dev-10771-agent-groups-files-to-wazuh-db](https://github.com/wazuh/wazuh/tree/dev-10771-agent-groups-files-to-wazuh-db)|[feature/2479-cluster-system-tests-for-agent-groups](https://github.com/wazuh/wazuh-qa/tree/feature/2479-cluster-system-tests-for-agent-groups)|

### `test_cluster_master_logs_order`

|  OS  | Local        | Notes
|---    |---     |---    |
| R1   | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8426644/R1-2645-test_cluster_master_logs_order.zip)  |  |
| R2   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8426646/R2-2645-test_cluster_master_logs_order.zip)   |  |
| R3   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8426648/R3-2645-test_cluster_master_logs_order.zip)   |   |


### test_cluster_worker_logs_order

|  OS  | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| R1   | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8426645/R1-2645-test_cluster_worker_logs_order.zip)  |  |
| R2   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8426647/R2-2645-test_cluster_worker_logs_order.zip)   |  |
| R3   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8426649/R3-2645-test_cluster_worker_logs_order.zip)   |  |
* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

2022-04-08 09:16 UTC, Rebits approved these changes

2022-04-11 16:11 UTC, merged