System Test: Module (WAZUH-DB) - The agent with state different than never_connected is added to a "group_test" group by API
wazuh/wazuh-qa pull request #2657
Opened 2022-03-09 17:14 UTC by CamiRomero

In this PR the test suite for `The agent with state different than never_connected is added to a "group_test" group by API`  is added. A total of  new test cases covering different modes and combinations of options.

<table>
  <tr>
    <th>Related issues</th>
    <th><a href="[url](https://github.com/wazuh/wazuh-qa/issues/2507)">#2508</a></th>
    <th><a href="[url](https://github.com/wazuh/wazuh/issues/10771)">#10771</a></th>
  </tr>
</table>

## Cases:

- [x] Assign agent with API:
        - The agent is active and registers with group  to the `master` node using API
        - The agent is disconnected and registers with group  to the `master` node using API
       - The agent is active and registers with group  to the `worker` node using API
       - The agent is disconnected and registers with group  to the `worker` node using API

--- 

## Configuration options
In order to run the test, first the environment located in `/test/system/provisioning/enrollment_cluster` must be enabled with:
`sudo ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch": "dev-10771-agent-groups-files-to-wazuh-db"}'`

**Local Internal Options:** No Local Internal Options used

---

---

## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8216742/R1.zip)[:large_blue_circle:][:large_blue_circle:]| 09/03/2022 |  @CamiRomero  | 

---
## Required
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is documented in wazuh-qa/docs.

2022-03-11 18:18 UTC, Deblintrake09 requested changes

2022-03-14 14:17 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
> +    print(response)
```suggestion
    response = host_manager.make_api_call('wazuh-master', method='PUT',
                                          endpoint=f'/agents/{agent_id}/group/group_test?pretty=true',
                                          token=token)
```

2022-03-14 14:33 UTC, damarisg requested changes

2022-03-14 14:33 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
> +    assert check_keys_file(test_infra_agents[0], host_manager)
It doesn't have an error message when the assert fails. Is it for some reason?

2022-03-14 15:44 UTC, damarisg requested changes

2022-03-15 18:06 UTC, Deblintrake09 approved these changes

2022-03-15 18:07 UTC, Deblintrake09 commented
## Tests Results

| Test Path | Os/Type | Ex
[R1.zip](https://github.com/wazuh/wazuh-qa/files/8256065/R1.zip)
[R2.zip](https://github.com/wazuh/wazuh-qa/files/8256067/R2.zip)
[R3.zip](https://github.com/wazuh/wazuh-qa/files/8256068/R3.zip)
ecution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8256065/R1.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8256067/R2.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8256068/R3.zip)| 15/03/2022 |  @CamiRomero  |

2022-03-15 18:25 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
> +    print(response)
@Deblintrake09

2022-03-15 19:26 UTC, damarisg requested changes

2022-03-15 19:26 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
> +            brief: Reset the wazuh log files at the start of the test. Remove all registered agents from master.
There aren't the variables(test_infra_managers, test_infra_agents, host_manager) defined as parameters of the documentation.

2022-03-16 11:33 UTC, damarisg approved these changes

2022-03-16 11:37 UTC, merged