System Test: Module (WAZUH-DB) - Agent never_connected connects (guesses a different group by default
wazuh/wazuh-qa pull request #2664
Opened 2022-03-10 17:52 UTC by CamiRomero

In this PR the test suite for `Agent never_connected connects (guesses a different group by default`  is added. A total of 4 new test cases covering different modes and combinations of options.

<table>
  <tr>
    <th>Related issues</th>
    <th><a href="[url](https://github.com/wazuh/wazuh-qa/issues/2507)">#2516</a></th>
    <th><a href="[url](https://github.com/wazuh/wazuh/issues/10771)">#10771</a></th>
  </tr>
</table>

## Cases:

- [x] guessing:
        - The guessing is activated and the agent connects with master node
        - The guessing is activated and the agent connects with worker node
        - The guessing is by default and the agent connects with master node

--- 

## Configuration options
In order to run the test, first the environment located in `/test/system/provisioning/enrollment_cluster` must be enabled with:
`sudo ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch": "dev-10771-agent-groups-files-to-wazuh-db"}'`

**Local Internal Options:** No Local Internal Options used

---

---

## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8215151/R1.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8215152/R2.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8215154/R3.zip)| 09/03/2022 |  @CamiRomero  | 

---
## Required
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is documented in wazuh-qa/docs.

2022-03-15 16:33 UTC, damarisg requested changes

2022-03-15 16:33 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +    if(int(status_guess_agent_group) == 1):
```suggestion
    if (int(status_guess_agent_group) == 1):
```

2022-03-15 16:33 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +        delete_group_of_agents(test_infra_managers[0], group_id, host_manager)
Is there any reason, because it is on `try..finally` section? 
The clean_environment method shouldn't remove all.

2022-04-11 21:26 UTC, Deblintrake09 approved these changes

2022-04-12 10:22 UTC, merged