System Test: Module (WAZUH-DB) - Agent forced to change group
wazuh/wazuh-qa pull request #2668
Opened 2022-03-11 14:35 UTC by CamiRomero

In this PR the test suite for `Agent forced to change group`  is added. A total of 3 new test cases covering different modes and combinations of options.

<table>
  <tr>
    <th>Related issues</th>
    <th><a href="[url](https://github.com/wazuh/wazuh-qa/issues/2512)">#2512</a></th>
    <th><a href="[url](https://github.com/wazuh/wazuh/issues/10771)">#10771</a></th>
  </tr>
</table>

## Cases:

- [x] Agent forced to change group:
        - The agent  registered in master node changed group
        - The agent  registered in worker node changed group

--- 

## Configuration options
In order to run the test, first the environment located in `/test/system/provisioning/enrollment_cluster` must be enabled with:
`sudo ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch": "dev-10771-agent-groups-files-to-wazuh-db"}'`

**Local Internal Options:** No Local Internal Options used

---

---

## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_agent_groups_default.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8226109/R1.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8226110/R2.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8226117/R3.zip)| 10/03/2022 |  @CamiRomero  | 

---
## Required
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is documented in wazuh-qa/docs.

2022-03-14 21:33 UTC, Deblintrake09 commented
## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_agent_groups_default.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8248620/R1.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8248622/R2.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8248623/R3.zip)| 10/03/2022 |  @CamiRomero  |

2022-03-14 21:33 UTC, Deblintrake09 approved these changes

2022-03-15 14:58 UTC, damarisg requested changes

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +@pytest.mark.parametrize("agent_host", test_infra_managers[0:2])
Why is `agent_host `not a list if it contains `test_infra_managers`?

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +def test_force_group_change(agent_host, clean_environment, test_infra_managers, test_infra_agents, host_manager):
```suggestion
def test_sync_when_forced_to_change_a_group(agent_host, clean_environment, test_infra_managers, test_infra_agents, host_manager):
```

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +    time.sleep(10)
Remove hardcoded value.

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +    the cluster, the group data is synchronized to the new node.
```suggestion
    description: Check that having a series of agents assigned with different groups, when an new node is added from the worker node, the group data is synchronized to the new node.
```

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +        - test_infra_managers
```suggestion
        - test_infra_agents
```

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +        - test_infra_managers
```suggestion
        - test_infra_agents
```

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +    the cluster, the group data is synchronized to the new node.
The description is confused and has a lot of similarities with the previous test. Please check it.

2022-03-15 14:58 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +'''
I can't see where you connect the agent with the master or with the worker according to cases 1 and 2. We need to do a sync.

2022-03-15 19:11 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +@pytest.mark.parametrize("agent_host", test_infra_managers[0:2])
@Deblintrake09

2022-03-15 19:45 UTC, Deblintrake09 commented on tests/system/test_cluster/test_agent_groups/test_agent_groups_forced_change.py
> +def test_force_group_change(agent_host, clean_environment, test_infra_managers, test_infra_agents, host_manager):
Changed

2022-03-16 11:12 UTC, damarisg approved these changes

2022-03-21 17:22 UTC, merged