System Test: Module (WAZUH-DB) -Agent registered with group Y - group data is synced in cluster
wazuh/wazuh-qa pull request #2686
Opened 2022-03-16 14:48 UTC by Deblintrake09

In this PR the test suite for `test_assign_agent_group_with_enrollment.py`  is added. A total of 1 new test cases cover that the agent enrollment process and new group assignment works as expected in a cluster environment.

<table>
  <tr>
    <th>Related issues</th>
    <th><a href="[url](https://github.com/wazuh/wazuh-qa/issues/2510)">#2510</a></th>
    <th><a href="[url](https://github.com/wazuh/wazuh/issues/10771)">#10771</a></th>
  </tr>
</table>

## Cases:

- [x] Agent forced to change group:
        - The agent  registered in `master` node with a specific group and it is synced to worker nodes

--- 

## Configuration options
In order to run the test, first the environment located in `/test/system/provisioning/basic_cluster` must be enabled with:
`sudo ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch": "dev-10771-agent-groups-files-to-wazuh-db"}'`

**Local Internal Options:** No Local Internal Options used

---

## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py  | CentOS - Manager | Local | [:large_blue_circle:][:large_blue_circle:][:large_blue_circle:]| 16/03/2022 |  @Deblintrake09   | 

---
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.

2022-03-16 15:20 UTC, damarisg requested changes

2022-03-16 15:20 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
> +"""
```suggestion
"""
```

2022-03-16 15:20 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
> +path: /tests/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py
Please, check the path.

2022-03-16 15:20 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
> +import pytest
```suggestion
import time
import pytest
```

2022-03-16 15:20 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
> +                       """
`id_group` has the same name as the group in the `enrollment_group` section. Is it possible to use this variable here?

2022-03-16 15:20 UTC, damarisg commented on tests/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py
> +    remove_cluster_agents(test_infra_managers[0], test_infra_agents, host_manager)
we only required to call it as a parameter. Remove this method defined from here.

2022-03-28 17:50 UTC, CamiRomero commented
## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8365072/R1.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8365073/R2.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8365074/R3.zip)| 28/03/2022 |  @CamiRomero    |

2022-03-28 19:42 UTC, damarisg approved these changes

2022-03-28 19:43 UTC, merged