Adapt Gcloud integration tests to logging parameter deprecation
wazuh/wazuh-qa pull request #2743
Opened 2022-03-31 06:34 UTC by noise-kngdm

|Related issue|
|---|
|Closes #2693|

## Description
In this PR we adapt the GCloud integration tests to the deprecation of the logging parameter. After the changes made in wazuh/wazuh#10334, the module stopped using a custom `logging` parameter to start using the `wazuh_modules.debug` value, as the rest of the external integrations do. 
This change has required modifying some of the regex that the `wazuh-testing` library uses to detect GCP logs, along with minor changes in most of the tests. The only test that required a more thorough refactor is the `test_logging` one, which tested that, for every logging level, the module would only receive the messages pertaining to that same logging level. Since now the module uses 'cascade' logging levels, that is, the more verbose levels contain the less verbose ones, the test needed a complete refactor, and it now tests that for lower logging levels the module won't get debug messages and that for greater ones it will get messages having the expected debug levels.

To make sure that Wazuh is restarted once the `local_internal_options.conf` file was set for the `test_logging` test, we added `package` level fixtures to set the configuration file.

## Tests
<details><summary>Integration tests execution</summary>

The GCloud tests executed using the [10334-standardize-gcp-logging](https://github.com/wazuh/wazuh/tree/feature/10334-standardize-gcp-logging) branch show the following results:

        ==================================== test session starts ====================================
        platform linux -- Python 3.6.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
        rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
        plugins: html-3.1.1, testinfra-5.0.0, metadata-1.11.0
        collected 84 items                                                                          
        
        test_gcloud/test_configuration/test_invalid.py .........................              [ 29%]
        test_gcloud/test_configuration/test_remote_configuration.py ...                       [ 33%]
        test_gcloud/test_configuration/test_schedule.py .........                             [ 44%]
        test_gcloud/test_functionality/test_day_wday.py .ssssss.ssssss.ssssss.ssssss.ssssss.  [ 86%]
        test_gcloud/test_functionality/test_interval.py ..                                    [ 89%]
        test_gcloud/test_functionality/test_logging.py ...                                    [ 92%]
        test_gcloud/test_functionality/test_max_messages.py ...                               [ 96%]
        test_gcloud/test_functionality/test_pull_on_start.py ..                               [ 98%]
        test_gcloud/test_functionality/test_rules.py .                                        [100%]
        
        ================== 54 passed, 30 skipped, 53 warnings in 588.91s (0:09:48) ==================

</details>

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.

- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2022-04-06 11:05 UTC, CarlosRS9 requested changes

2022-04-06 11:05 UTC, CarlosRS9 commented on tests/integration/test_gcloud/test_functionality/test_logging.py
> +    for nevents in range(0, 12):
```suggestion
    for _ in range(12):
```

2022-04-07 11:22 UTC, davidjiglesias approved these changes

2022-04-07 11:25 UTC, CarlosRS9 approved these changes

2022-04-08 15:45 UTC, merged