Add a test to check the multigroups shared file content added. #1852
wazuh/wazuh-qa pull request #2746
Opened 2022-03-31 21:03 UTC by mauromalara

|Related issue|
|---|
||

## Description

## Configuration options

## Logs example

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2022-04-05 10:45 UTC, Rebits requested changes
GJ but some changes are required

2022-04-05 10:45 UTC, Rebits commented on tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
> +    assert match == expected_conditions[1], f"The file is {'not' if action == 'created' else ''}in {merged_mg_file}."
```suggestion
    match_expected_line = None

    manipulate_file(action, shared_file_path)
    sleep(wait_time + elapsed_time)

    file_exists = os.path.exists(os.path.join(mg_folder_path, shared_file_name))
    if os.path.exists(merged_mg_file):
        with open(merged_mg_file, 'r') as merged_file:
            merged_file_lines = merged_file.readlines()
            match_regex = re.compile(rf"^{expected_line}$")
            match_expected_line = list(filter(match_regex.match, merged_file_lines))
    else:
        print(f"The file: {merged_mg_file} was not created.")

    expected_conditions = [True, [expected_line + '\n']] if action == 'create' else [False, []]

    assert file_exists == expected_conditions[0], f"The file was not {action}d in the multigroups directory.\n"
    assert match_expected_line == expected_conditions[1], f"The file is \
                                                          {'not' if action == 'created' else ''} in {merged_mg_file}." \

```

2022-04-06 19:41 UTC, mauromalara commented
## 06/04/2022
Tests are executed in Jenkins in 2 versions, to verify that it passes when it has to and that it fails when it has to.

# Executions

## N°1

### Package
| Version | Revision | Link|
|---|---|---|
|4.3.0|1|pre-release

### Remoted

|  Target  | Jenkins     | Notes
|---    |---    |---    |
| Manager   | [:large_blue_circle:]() - [Build]()   | - |

* * *

## N°2

### Package
| Version | Revision | Link|
|---|---|---|
|4.2.1|1|pre-release

### Remoted

|  Target  | Jenkins     | Notes
|---    |---    |---    |
| Manager   | [:large_blue_circle:]() - [Build]()   | - |

* * *

:large_blue_circle:: The tests are being executed.
:green_circle:: All tests passed successfully.
:yellow_circle:: Some tests passed with warnings.
:orange_circle:: Some errors or failures of Jenkins.
:red_circle:: Some tests failed or had errors.

2022-04-09 00:43 UTC, mauromalara commented
# 08/04/2022

## Note
The last execution **fails** because it has to. So, the results are expected.

2022-04-11 09:09 UTC, juliamagan commented on tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
> +            brief: Configure a custom environment for testing.
We need to add `metadata` and `configure_local_internal_options_module`

2022-04-11 09:10 UTC, juliamagan commented on tests/integration/test_remoted/test_multi_groups/data/test_cases/case_file_actions.yaml
> +  description: 'When a file is created in the group directory, the merged.mg file should be updated and the new file must appears inside it.'
The description doesn't match the name

2022-04-11 15:29 UTC, juliamagan requested changes

2022-04-11 15:29 UTC, juliamagan commented on tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
> +def prepare_environment(request, register_agent):
This fixture scope should be `function`

2022-04-11 15:29 UTC, juliamagan commented on tests/integration/test_remoted/test_multi_groups/test_merged_mg_file_content.py
> +def register_agent(request):
This fixture scope should be `function`

2022-04-12 15:27 UTC, mauromalara commented
## Date: 12/04/2022


## Executions

### Remoted - Manager (`#1`)

**Package**

| Version | Revision | Link|
|---|---|---|
|4.4.0|0.40400.20220407|[staging package](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.4.0-0.40400.20220407.x86_64.rpm)

|  OS  | Jenkins     | Notes
|---    |---    |---    |
| CentOS   | [:green_circle:](https://ci.wazuh.info/job/Test_integration/25041/artifact/manager_tests_Test_integration_B25041_20220412152821.txt) - [Build](https://ci.wazuh.info/job/Test_integration/25041/)   | - |

* * *

### Remoted - Manager (`#2`) <-- EXPECTED TO FAIL

**Package**

| Version | Revision | Link|
|---|---|---|
|4.4.0|0 .40400.20220407 | [staging package](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.4.0-0.40400.20220407.x86_64.rpm)

|  OS  | Jenkins     | Notes
|---    |---    |---    |
| CentOS   | [:red_circle:](https://ci.wazuh.info/job/Test_integration/25042/artifact/manager_tests_Test_integration_B25042_20220412152933.txt) - [Build](https://ci.wazuh.info/job/Test_integration/25042/)   | - |

- :large_blue_circle:: The tests are being executed.
- :green_circle:: All tests passed successfully.
- :yellow_circle:: Some tests passed with warnings.
- :orange_circle:: Some errors or failures of Jenkins.
- :red_circle:: Some tests failed or had errors.

2022-04-13 09:02 UTC, juliamagan approved these changes
LGTM

2022-04-13 11:07 UTC, jmv74211 approved these changes

2022-04-13 11:07 UTC, merged