IT Authd/Wazuh DB: Refactor for failures caused by new development of Wazuh DB
wazuh/wazuh-qa pull request #2777
Opened 2022-04-07 20:03 UTC by Deblintrake09

**# Description
In this PR there were fixes done to tests on the `authd` and `wazuhdb` modules, caused by the development done on Wazuh DB.
<table>
  <tr>
    <th>Related issues</th>
    <th><a href="[url](https://github.com/wazuh/wazuh-qa/issues/2584)">#2584</a></th>
    <th><a href="[url](https://github.com/wazuh/wazuh/issues/10771)">#10771 (Wazuh)</a></th>
  </tr>
</table>

## Work done on `authd` module (test_authd folder):

- fixed messages for `test_authd_worker.py`
- fixed messages for `test_authd.py`
- fixed messages for `test_authd_key_hahs.py`
- Refactored test_authd_agents_ctx

##  Work done on `Wazuh DB` module (test_wazuh_db.py):

- fixed messages for `global_messages` (modify responses and remove unused cases)
- fixed messages for `agent_messages` (modify responses and remove unused cases)
- fixed test_wazuh_db_range_checksum fixture
        
--- 

## Configuration options
|OS | Version | Branch | Type |
|--|--|--|--|
| Centos | 4.4.0 | dev-10771-agent-groups-files-to-wazuh-db | Manager|

**Local Internal Options:** 

> wazuh_modules.debug=2
> monitord.rotate_log=0

---

## Tests Results

## Tests
| Type | Jenkins | Local Results | Date | By |Notest|
|--|--|--|--|--|--|
| `test_wazuh_db/`  | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/24873/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/24874/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/24875/) | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8446133/R1.zip)  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8446134/R2.zip)  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8446135/R3.zip) | 2022/04/07 | @Deblintrake09  |  
| `test_authd/`  | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/24818/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/24830/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/24831/) | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8446101/R1.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8446104/R2.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8446105/R3.zip) | 2022/04/07 | @Deblintrake09  |  
---
## Required
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.

2022-04-11 12:11 UTC, CamiRomero requested changes

2022-04-11 12:11 UTC, CamiRomero commented on tests/integration/test_authd/test_authd_agents_ctx.py
> +    return response
Also, please check the function `make_api_call` in `deps/wazuh_testing/wazuh_testing/tools/system.py` as an example. We need one generic function

2022-04-12 14:58 UTC, Deblintrake09 commented on tests/integration/test_authd/test_authd.py
> -                             clean_client_keys_file_module, restart_authd, wait_for_authd_startup_module,
The function removed `restart_authd` has been removed from all authd tests. There is no need to create a new Issue.
The generic function could be applied to other tests, where wazuh or one of its daemons is restarted.

2022-04-12 17:21 UTC, CamiRomero commented on tests/integration/test_authd/test_authd.py
> -                             clean_client_keys_file_module, restart_authd, wait_for_authd_startup_module,
Yes, you are right, but in this PR only applied the changes to use `restart_wazuh_daemon` and `restart_wazuh_daemon_function` but we need to delete the functions `restart_authd` and `restart_authd_function` located in `wazuh-qa/tests/integration/test_authd/conftest.py` and we need to check in all the repository if we have other functions that can be replace with the generic function created here

2022-04-12 23:00 UTC, Deblintrake09 commented
### Update 2022/04/12

- Upload only `test_authd` results, that was the modules were changes were requested.

## Tests
| Type  | Local Results | Date | By |
|--|--|--|--|
| `test_authd/`  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8477010/R1.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8477011/R2.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8477012/R3.zip) | 2022/04/12 | @Deblintrake09  |

2022-04-12 23:01 UTC, Deblintrake09 commented on tests/integration/test_authd/test_authd_agents_ctx.py
> +    time.sleep(3)
fixed

2022-04-12 23:01 UTC, Deblintrake09 commented on tests/integration/test_authd/test_authd_agents_ctx.py
> +    return response
removed functions to `deps/wazuh_testing/api.py` file

2022-04-13 18:17 UTC, damarisg requested changes

2022-04-13 18:17 UTC, damarisg commented on tests/integration/test_authd/test_authd_key_hash.py
> +                assert response != '', 'Manager did not respond to sent message!'
```suggestion
                assert response != '', 'The manager did not respond to the sent message.'
```

2022-04-13 18:17 UTC, damarisg commented on tests/integration/test_authd/test_authd_valid_name_ip.py
> +                assert response != '', 'Manager did not respond to sent message!'
```suggestion
                assert response != '', 'The manager did not respond to the sent message.'
```

2022-04-13 19:12 UTC, Deblintrake09 commented on tests/integration/test_authd/test_authd_agents_ctx.py
> +        print(str(groups_created))
fixed

2022-04-18 14:05 UTC, damarisg approved these changes
## Configuration options
|OS | Version | Branch | Type |
|--|--|--|--|
| Centos | 4.4.0 | dev-10771-agent-groups-files-to-wazuh-db | Manager|


## Tests Results

## Tests
|Test Path | Type | Jenkins - Status  | Date | By |
|--|--|--|--|--|
| `test_wazuh_db/`| Manager | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25090/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25095/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25119/) | 2022/04/18| Seyla  |  
| `test_authd/`  |  Manager | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25093/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25092/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25120/) | 2022/04/18| Seyla  |

2022-04-18 14:06 UTC, merged