New synchronization mechanism
wazuh/wazuh-qa pull request #2799
Opened 2022-04-18 16:05 UTC by Deblintrake09

In this PR the tests related to the `max_eps` options are tested. A total of 6  test cases covering have been developed to test the max_eps function for file events and for database synchronization.

<table>
  <tr>
    <th>Related issues</th>
    <th><a href="[url](https://github.com/wazuh/wazuh-qa/issues/2316)">#2316</a></th>
  </tr>
</table>
     
--- 

## Configuration options
|OS | Version | Branch | Type |
|--|--|--|--|
| Centos | 4.4.0 | 0504fimsync | Manager & Agent|
| Windows | 4.4.0 | 0504fimsync | Agent|

**Local Internal Options:**

#### Agent
> syscheck.debug=2
> agent.debug=2
> windows.debug=2
> monitord.rotate_log=0

#### Manager
> syscheck.debug=2
> monitord.rotate_log=0
> analysisd.debug=2

---

## Tests Results
| Test Path | Os/Type | Local | Jenkins | Results | Date | By |
|--|--|--|--|--|--|--|
| test_fim/test_files/test_max_eps/  | Manager | [:green_circle:] [:green_circle:] [:green_circle:] | [:green_circle:][:green_circle:]| 18/04/2022 |  @Deblintrake09   |  
| test_fim/test_files/test_max_eps/  | Linux | [:green_circle:] [:green_circle:] [:green_circle:] | [:green_circle:][:green_circle:]| 18/04/2022 |  @Deblintrake09   |  
| test_fim/test_files/test_max_eps/  | Windows | [:green_circle:] [:green_circle:] [:green_circle:] | [:green_circle:][:green_circle:]| 18/04/2022 |  @Deblintrake09   |  

---
## Required
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is documented in wazuh-qa/docs.

2022-04-18 18:42 UTC, CamiRomero requested changes

2022-05-02 16:02 UTC, CamiRomero commented
## Tests Results
| Test Path | Os/Type | Jenkins | Date | By | Note |
|--|--|--|--|--|---|
| test_fim/test_files/test_max_eps/  | Manager | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25797/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25799/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25800/) | 28/04/2022 |  @CamiRomero    |  
| test_fim/test_files/test_max_eps/  | Agent - CentOS | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25798/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25801/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25802/) | 28/04/2022 |  @CamiRomero    |  
| test_fim/test_files/test_max_eps/  | Agent - Windows | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25855/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25860/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25861/) | 28/04/2022 |  @CamiRomero    |

2022-05-02 16:59 UTC, damarisg requested changes

2022-05-02 16:59 UTC, damarisg commented on tests/integration/test_fim/test_files/test_max_eps/data/wazuh_sync_conf_max_eps.yaml
> +  - test_sync_max_eps_scheduled
I can't find the `test_sync_max_eps_rt_wd` test. Did you forget to remove it?

2022-05-02 18:05 UTC, damarisg approved these changes
## Tests Results
| Test Path | Os/Type | Local | Jenkins | Date | By |
|--|--|--|--|--|--|
| test_fim/test_files/test_max_eps/  | Manager | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25872/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25871/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25870/) | 2022/05/02 | Seyla    | 
| test_fim/test_files/test_max_eps/  | Linux | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25877/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25882/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25881/) | 2022/05/02| Seyla |  
| test_fim/test_files/test_max_eps/  | Windows |  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25878/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25879/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25880/)| 2022/05/02 |Seyla  |

2022-05-02 18:08 UTC, merged