Change method from `GET` to `POST` in API login requests
wazuh/wazuh-qa pull request #2810
Opened 2022-04-20 14:45 UTC by mcarmona99

|Related issue|
|---|
|#2705|

## Description

This PR closes #2705.

Apart from the change listed in the related issue, I have added more changes to tests and tools using the login endpoint.

The related API tests will fail until https://github.com/wazuh/wazuh/issues/10203 is merged.

## Checks

- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.

2022-04-21 07:55 UTC, vicferpoy requested changes

2022-04-21 07:55 UTC, vicferpoy commented on deps/wazuh_testing/wazuh_testing/tools/api_simulator.py
> +                response = requests.post(f'{self.base_url}{authenticate_url}', headers=basic_auth, verify=False)
```suggestion
                response = requests.post(f"{self.base_url}{authenticate_url}", headers=basic_auth, verify=False)
```

2022-04-21 07:55 UTC, vicferpoy commented on deps/wazuh_testing/wazuh_testing/tools/key_polling_api.py
> +        response = requests.post(f'{BASE_URL}/security/user/authenticate', headers=login_headers(), verify=False)
```suggestion
        response = requests.post(f"{BASE_URL}/security/user/authenticate", headers=login_headers(), verify=False)
```

2022-04-25 06:49 UTC, vicferpoy approved these changes
LGTM

2022-05-03 15:40 UTC, damarisg approved these changes
## Tests Results
| Test Path | Os/Type | Jenkins | Date | By | 
|--|--|--|--|--|
| test_api/  | Manager | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25980/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25979/)  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/25978/) | 03/05/2022 |  Seyla

Build package: https://ci.wazuh.info/job/Packages_builder/95111/

2022-05-04 10:33 UTC, merged