2792 test scan results
wazuh/wazuh-qa pull request #2902
Opened 2022-05-17 12:05 UTC by Deblintrake09

|Related issue|
|---|
| [2809](https://github.com/wazuh/wazuh-qa/issues/2809)|
||[2899](https://github.com/wazuh/wazuh-qa/issues/2899)

## Description
add cases in the test_scan_results suite related to SUSE Linux Server and Desktop support for the Wazuh Vulnerability Detector module.

**Suite test_scan_results**

- `Test scan no agent data`: Check an alert message is shown when attempting scan on Linux agents with NVD feed only
- `Test scan provider vulnerabilities`: Check if the vulnerability alerts are reported making vulnerabilities found only by OVAL and not NVD
- `Test scan provider and nvd vulnerabilities`: Check if the vulnerability alerts are reported making vulnerabilities found by OVAL and NVD
- `Test scan vulnerability removal`: Test that it is reported when a vulnerability is deleted or a package is updated

## Configuration options

local_internal_options
> wazuh_modules.debug=2
monitord.rotate_log=0

The test will be run when the development was finished
## Tests Results
| Test Path | Os/Type | Local | Jenkins | Date | By |
|--|--|--|--|--|--|
|  test/integration/test_vulnerability_detector/test_feeds | CentOS - Manager | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8708036/R1.zip) [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8708037/R2.zip) [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8708038/R3.zip)  | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/26421/)| 2022/05/17  |  @Deblintrake09  | 

## Tests

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the Google Style for Python docstrings.

2022-05-17 19:09 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml
>  	</rpminfo_object>
Fixed

2022-05-17 19:09 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/data/feeds/suse/custom_suse_oval_feed.xml
>  	      <oval:product_name>Marcus Updateinfo to OVAL Converter</oval:product_name>
This was the name on the base Feed i worked on. Fixed

2022-05-17 19:09 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/event_monitor.py
> +                       callback=make_vuln_callback(callback, prefix), error_message=error_message)
It is correctly indented inside the file

2022-05-17 19:09 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/mocking/__init__.py
> +                 'sync_status': 'synced', 'connection_status': 'active'}
fixed. The spaces are complying to PEP8. there were spaces missing.

2022-05-17 19:09 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
> +        raise ValueError(f"Suse System parameter invalid.")
Fixed

2022-05-17 19:10 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/modules/vulnerability_detector/__init__.py
> +    """Insert suse os package to an agent.
Fixed

2022-05-17 19:10 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml
> +                  value: CUSTOM_NVD_JSON_FEED
Fixed

2022-05-17 19:10 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml
> +                  value: CUSTOM_NVD_JSON_FEED
Fixed

2022-05-17 19:10 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml
> +    nvd_feed_tag: CUSTOM_NVD_JSON_FEED
Fixed

2022-05-17 19:10 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml
> +    nvd_feed_tag: CUSTOM_NVD_JSON_FEED
Fixed

2022-05-17 19:11 UTC, Deblintrake09 commented on tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
> +    wazuh_min_version: 4.4.0
Fixed

2022-05-17 19:12 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
> +                   f"VALUES ('{dependency_id}', '{name}', '{operation}', '{operation_value}', '{target}','{installed}')"
This function was removed becayse it is not being used

2022-05-17 19:14 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/db_interface/__init__.py
> +
Removed

2022-05-17 19:15 UTC, Deblintrake09 reviewed
Applied requested changes

2022-05-17 19:15 UTC, Deblintrake09 commented on deps/wazuh_testing/wazuh_testing/db_interface/cve_db.py
> +    make_sqlite_query(CVE_DB_PATH, [pkg_deps_string])
Removed

2022-05-19 12:35 UTC, damarisg requested changes

2022-05-19 12:35 UTC, damarisg commented on tests/integration/test_vulnerability_detector/conftest.py
> +from time import sleep
If it is not used, it should be removed.

2022-05-19 12:35 UTC, damarisg commented on tests/integration/test_vulnerability_detector/conftest.py
> +from wazuh_testing import CVE_DB_PATH
If it is not used, it should be removed.

2022-05-19 13:21 UTC, damarisg approved these changes
## Tests Results
| Test Path | Os/Type | Jenkins | Date | By |
|--|--|--|--|--|
|  test/integration/test_vulnerability_detector/test_scan_results | CentOS - Manager |  [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/26543/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/26544/) [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/26545/)| 2022/05/19 | Seyla  |

2022-05-19 13:21 UTC, merged