Fix syscollector deltas IT
wazuh/wazuh-qa pull request #2921
Opened 2022-05-26 13:34 UTC by jnasselle

|Related issue|
|---|
|wazuh/wazuh#12550|

## Description

This PR aims to fix related syscollector deltas IT after the changes applied on wazuh/wazuh#12550.
Also, analysisd test that check deltas were enabled again.

## Logs example

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.
- [ ] `provision_documentation.sh` generate the docs without errors.

2022-05-26 22:34 UTC, HanesSciarrone approved these changes

2022-06-17 10:14 UTC, jmv74211 requested changes

2022-06-17 10:14 UTC, jmv74211 commented on tests/integration/test_analysisd/test_syscollector/test_syscollector_events.py
> +# @pytest.mark.skip(reason='Temporarily disabled until merge this PR https://github.com/wazuh/wazuh/pull/10843')
Remove this if it is not necessary

2022-06-29 07:54 UTC, merged

2022-06-29 07:55 UTC, jmv74211 approved these changes