dd IT to verify Active Response works with overwritten rules
wazuh/wazuh-qa pull request #2984
Opened 2022-06-09 16:13 UTC by CamiRomero

|Related issue|
|---|
| Close #2918 |

## Description

## Configuration options

## Logs example

## Tests

- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.

- [ ] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is documented in wazuh-qa/docs.

2022-08-11 12:59 UTC, damarisg requested changes
Please, resolve conflicts.

2022-08-11 13:02 UTC, damarisg requested changes
I see the `.github/workflows/scripts/linter.py` file empty. Could you apply a git pull from 4.3 on this branch?

2022-08-11 17:08 UTC, damarisg approved these changes

2022-09-02 13:55 UTC, jmv74211 commented
I have added all my requested changes in these commits:
- https://github.com/wazuh/wazuh-qa/pull/2984/commits/b5ff827b6e6239b8987eef859e63f26db880ad9f
- https://github.com/wazuh/wazuh-qa/pull/2984/commits/4e9db559b9040b4d6e981749c03eb7fa67a33703
- https://github.com/wazuh/wazuh-qa/pull/2984/commits/0d6a390edf7c7573e6d3f9743de062e60f4e5fab
- https://github.com/wazuh/wazuh-qa/pull/2984/commits/690e6ba7a21d0d33b2e0c3024b75ef1019f7653b

2022-09-02 15:24 UTC, merged