E2E Test Virustotal
wazuh/wazuh-qa pull request #3062
Opened 2022-07-04 19:40 UTC by BelenValdivia

|Related issue|
|-------------|
|             |

## Description

### Added

- Item 1
- Item n

### Updated

- Item 1
- Item n

### Deleted

- Item 1
- Item n

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @user (Developer)  |           | ⚫⚫⚫ | ⚫⚫⚫ |         |         | Nothing to highlight |
| @user (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2022-07-05 14:00 UTC, juliamagan requested changes
GJ, but some changes are required

2022-07-05 15:21 UTC, BelenValdivia commented on tests/end_to_end/test_virustotal/data/configuration/virustotal_key
> +3e4db70c621cd9dd9e3400254297eea03215987facca9931a42dcb86ffb8aa78
Done in 040f8a4a2a56e8acd37235129e33afe4959bda7c

2022-07-05 15:21 UTC, BelenValdivia commented on tests/end_to_end/test_virustotal/test_virustotal_active_response/data/playbooks/configuration.yaml
> +    - name: Change remove threat owner and permissions
Done in 040f8a4a2a56e8acd37235129e33afe4959bda7c

2022-07-05 15:21 UTC, BelenValdivia commented on tests/end_to_end/test_virustotal/test_virustotal_active_response/data/test_cases/cases_virustotal.yaml
> +- name: Remove malicious file
Done in 040f8a4a2a56e8acd37235129e33afe4959bda7c

2022-07-05 15:22 UTC, BelenValdivia commented on tests/end_to_end/test_virustotal/test_virustotal_fim/data/playbooks/configuration.yaml
> +      ignore_errors: true
Deleted command to remove folder in 040f8a4a2a56e8acd37235129e33afe4959bda7c

2022-07-07 15:36 UTC, juliamagan approved these changes

2022-07-07 15:36 UTC, juliamagan commented on tests/end_to_end/test_virustotal/test_virustotal_fim/data/playbooks/configuration.yaml
> +      ignore_errors: true
We will clean the environment in #3065

2022-07-07 15:37 UTC, merged