Enhancement - Fix test scan commit option for master branch
wazuh/wazuh-qa pull request #3157
Opened 2022-08-08 13:47 UTC by Rebits

|Related issue|
|-------------|
| closes #3154   |

## Description
This PR includes a minor fix for conftest of the scan module. 

Now commit option work as expected for master branch commits. Also, now the commit option will fail if specified commits are not the head of any branch.

### Updated
- Scan module conftest: Change commit behaviour

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @Rebits  (Developer)  |           | :no_entry_sign: :no_entry_sign: :no_entry_sign: | :black_circle:  |         |         | Nothing to highlight |
| @jmv74211  (Reviewer)   |           | :no_entry_sign: :no_entry_sign: :no_entry_sign: | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2022-08-11 13:59 UTC, Rebits commented
### Production branch  `4.4` head commit 
<details>
```
[root@ip-172-31-67-54 code_analysis]# /var/ossec/framework/python/bin/python3 -m pytest test_python_flaws.py --repo wazuh --commit 911cc80f11368ba0cef3ca0d7b30b09940b8768d --check_directories framework/,api/,wodles/ --exclude_directories test/,tests/ --confidence MEDIUM --severity LOW
========================================= test session starts ==========================================
platform linux -- Python 3.9.9, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/ec2-user/wazuh-qa/tests/scans/code_analysis
collected 1 item                                                                                       

test_python_flaws.py F                                                                           [100%]

=============================================== FAILURES ===============================================
______________________________________ test_check_security_flaws _______________________________________

clone_wazuh_repository = '/tmp/tmp7r6vzj_h'
get_test_parameters = {'directories_to_check': ['framework/', 'api/', 'wodles/'], 'directories_to_exclude': 'test/,tests/', 'min_confidence_level': 'MEDIUM', 'min_severity_level': 'LOW', ...}

    def test_check_security_flaws(clone_wazuh_repository, get_test_parameters):
        """Test whether the directory to check has python files with possible vulnerabilities or not.
    
        The test passes if there are no new vulnerabilities. The test fails in other case and generates a report.
    
        In case there is at least one vulnerability, a json file will be generated with the report. If we consider this
        result or results are false positives, we will move the json object containing each specific result to the
        `known_flaws/known_flaws_{framework|api|wodles}.json` file.
    
        Args:
            clone_wazuh_repository (fixture): Pytest fixture returning the path of the temporary directory path the
                repository cloned. This directory is removed at the end of the pytest session.
            get_test_parameters (fixture): Pytest fixture returning the a dictionary with all the test parameters.
                These parameters are the directories to check, directories to exclude, the minimum confidence level, the
                minimum severity level and the repository name.
        """
        # Wazuh is cloned from GitHub using the clone_wazuh_repository fixture
        assert clone_wazuh_repository, "Error while cloning the Wazuh repository from GitHub, " \
                                       "please check the Wazuh branch set in the parameter."
        # Change to the cloned Wazuh repository directory
        os.chdir(clone_wazuh_repository)
    
        directories_to_check = get_test_parameters['directories_to_check']
        bandit_output_list = \
            run_bandit_multiple_directories(directories_to_check,
                                            get_test_parameters['directories_to_exclude'],
                                            get_test_parameters['min_severity_level'],
                                            get_test_parameters['min_confidence_level'])
    
        flaws_already_found = {}
        for bandit_output, directory in zip(bandit_output_list, directories_to_check):
            assert not bandit_output['errors'], \
                f"\nBandit returned errors when trying to get possible vulnerabilities in the directory " \
                f"{directory}:\n{bandit_output['errors']}"
    
            bandit_result = bandit_output['results']
    
            known_flaws = update_known_flaws_in_file(known_flaws_directory=KNOWN_FLAWS_DIRECTORY,
                                                     directory=directory,
                                                     is_default_check_dir=
                                                     directory.replace('/', '') in
                                                     DEFAULT_DIRECTORIES_TO_CHECK.replace('/', '').split(','),
                                                     bandit_results=bandit_result)
    
            flaws_already_found = get_new_flaws(bandit_results=bandit_result,
                                                known_flaws=known_flaws,
                                                directory=directory,
                                                flaws_already_found=flaws_already_found,
                                                new_flaws_output_dir=TEST_PYTHON_CODE_PATH)
    
>       assert not any(
            flaws_already_found.get(directory, None) for directory in directories_to_check), \
            f"\nThe following possible vulnerabilities were found: {json.dumps(flaws_already_found, indent=4, sort_keys=True)}"
E       AssertionError: 
E         The following possible vulnerabilities were found: {
E             "api/": "Vulnerabilities found in files: api/api/alogging.py, api/api/configuration.py, api/scripts/wazuh-apid.py, check them in /home/ec2-user/wazuh-qa/tests/scans/code_analysis/new_flaws_api.json",
E             "framework/": "Vulnerabilities found in files: framework/scripts/wazuh_logtest.py, framework/wazuh/core/cluster/common.py, framework/wazuh/core/cluster/utils.py, framework/wazuh/core/configuration.py, framework/wazuh/core/syscheck.py, framework/wazuh/core/utils.py, check them in /home/ec2-user/wazuh-qa/tests/scans/code_analysis/new_flaws_framework.json",
E             "wodles/": "Vulnerabilities found in files: wodles/azure/azure-logs.py, check them in /home/ec2-user/wazuh-qa/tests/scans/code_analysis/new_flaws_wodles.json"
E         }
E       assert not True
E        +  where True = any(<generator object test_check_security_flaws.<locals>.<genexpr> at 0x7fccb33de5f0>)

/home/ec2-user/wazuh-qa/tests/scans/code_analysis/test_python_flaws.py:64: AssertionError
=========================================== warnings summary ===========================================
test_python_flaws.py::test_check_security_flaws
  invalid escape sequence \g

test_python_flaws.py::test_check_security_flaws
  invalid escape sequence \d

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================= short test summary info ========================================
FAILED test_python_flaws.py::test_check_security_flaws - AssertionError: 
==================================== 1 failed, 2 warnings in 45.94s ====================================
```
</details>


### Production branch  `master` head commit 

<details>

```
[root@ip-172-31-67-54 code_analysis]# /var/ossec/framework/python/bin/python3 -m pytest test_python_flaws.py --repo wazuh --commit f1a77b6d5c43a8ae8a99e97b1878746a3dd0a8ac --check_directories framework/,api/,wodles/ --exclude_directories test/,tests/ --confidence MEDIUM --severity LOW
========================================= test session starts ==========================================
platform linux -- Python 3.9.9, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/ec2-user/wazuh-qa/tests/scans/code_analysis
collected 1 item                                                                                       

test_python_flaws.py F                                                                           [100%]

=============================================== FAILURES ===============================================
______________________________________ test_check_security_flaws _______________________________________

clone_wazuh_repository = '/tmp/tmps9zh6zda'
get_test_parameters = {'directories_to_check': ['framework/', 'api/', 'wodles/'], 'directories_to_exclude': 'test/,tests/', 'min_confidence_level': 'MEDIUM', 'min_severity_level': 'LOW', ...}

    def test_check_security_flaws(clone_wazuh_repository, get_test_parameters):
        """Test whether the directory to check has python files with possible vulnerabilities or not.
    
        The test passes if there are no new vulnerabilities. The test fails in other case an [...]

2022-09-21 10:15 UTC, jmv74211 requested changes

2022-09-22 08:29 UTC, Rebits commented on tests/scans/code_analysis/conftest.py
> +                raise Exception("Commit should be the head of the branch")
Done in [5ad55bc](https://github.com/wazuh/wazuh-qa/pull/3157/commits/5ad55bcba1ed9c6f0a0c0aa576c8383c46dca146)

2022-09-22 08:30 UTC, jmv74211 approved these changes

2022-09-22 08:31 UTC, merged