3142 validation stage
wazuh/wazuh-qa pull request #3175
Opened 2022-08-15 23:00 UTC by mauromalara

|Related issue|
|-------------|
| #3142 |

## Description

The validation phase allows to run a general validation prior to all tests (according to the tests that were selected to run) and then run (if any) the particular validation tasks for each test.

This phase is divided into 4 steps:

Step 1: Collect the data related to the selected tests that will be executed.
Step 2: Generate a playbook containing cross-checks for specified tests.
Step 3: Run the generated playbook.
Step 4: Execute test-specific validations (if any). It will run one validation for each selected test set.

### Added

- Item 1
- Item n

### Updated

- Item 1
- Item n

### Deleted

- Item 1
- Item n

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @user (Developer)  |           | ⚫⚫⚫ | ⚫⚫⚫ |         |         | Nothing to highlight |
| @user (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2022-08-23 12:50 UTC, juliamagan requested changes
GJ, but some changes are required

2022-08-23 12:50 UTC, juliamagan commented on tests/end_to_end/roles/host_checker/tasks/check_python.yaml
> +- name: Check default Python version (Linux)
```suggestion
- name: Check default Python version (Windows)
```

2022-08-23 12:50 UTC, juliamagan commented on tests/end_to_end/test_basic_cases/test_fim/test_fim_linux/test_fim_linux.py
> +    timestamp = r'\d+\-\d+\-\w+\:\d+\:\d+\.\d+[+|-]\d+'
```suggestion
    timestamp_regex = r'\d+\-\d+\-\w+\:\d+\:\d+\.\d+[+|-]\d+'
```

2022-08-23 12:50 UTC, juliamagan commented on tests/end_to_end/test_basic_cases/test_fim/test_fim_linux/test_fim_linux.py
> +    expected_alert_json = fr'.*\{{"timestamp":"({timestamp})","rule":{{"level":{rule_level},' \
```suggestion
    expected_alert_json = fr'{{"timestamp":"({timestamp_regex})","rule":{{"level":{rule_level},' \
```

2022-08-23 12:50 UTC, juliamagan commented on tests/end_to_end/test_basic_cases/test_fim/test_fim_linux/test_fim_linux.py
> +                             fr'"{rule_description}".*"timestamp": "({timestamp})".*'
```suggestion
                             fr'"{rule_description}".*"timestamp": "({timestamp_regex})".*'
```

2022-08-23 12:50 UTC, juliamagan commented on tests/end_to_end/test_basic_cases/test_fim/test_fim_windows/test_fim_windows.py
> +    timestamp = r'\d+\-\d+\-\w+\:\d+\:\d+\.\d+[+|-]\d+'
Same here

2022-08-23 12:54 UTC, mauromalara commented
Last changes are in [`3142-validation-stage-temp`](https://github.com/wazuh/wazuh-qa/tree/3142-validation-stage-temp)

2022-08-24 11:52 UTC, mauromalara commented on tests/end_to_end/roles/host_checker/tasks/check_python.yaml
> +- name: Check default Python version (Linux)
Done in 1c4424c

2022-08-25 12:48 UTC, juliamagan requested changes
GJ, but some changes are required

2022-08-25 13:50 UTC, mauromalara commented on tests/end_to_end/README.md
> +- [netcat](https://en.wikipedia.org/wiki/Netcat)
Done in b157bd7

2022-08-25 16:44 UTC, jmv74211 requested changes

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_controller_indexer.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout)
```suggestion
  when: (os == 'linux' and 'server' in wazuh_info.stdout)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_filebeat_indexer.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout)
```suggestion
  when: (os == 'linux' and 'server' in wazuh_info.stdout)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_filebeat_indexer.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout and 'ERROR' in test_result.stdout)
```suggestion
  when: (os == 'linux' and 'server' in wazuh_info.stdout and 'ERROR' in test_result.stdout)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_os.yaml
> +  when: (os == "Windows" and os not in supported_distros)
```suggestion
  when: (os == "windows" and os not in supported_distros)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_os.yaml
> +  when: (ansible_distribution not in supported_distros and os == "Linux")
```suggestion
  when: (ansible_distribution not in supported_distros and os == "linux")
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
> +  when: (os == "Linux" and ansible_python['version']['major'] < 3)
```suggestion
  when: (os == "linux" and ansible_python['version']['major'] < 3)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
> +  when: os == 'Windows'
```suggestion
  when: os == 'windows'
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
> +  when: (os == "Windows" and version.stdout.split(" ")[1].split(".")[0] | int < 3)
```suggestion
  when: (os == "windows" and version.stdout.split(" ")[1].split(".")[0] | int < 3)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: os == 'Linux'
```suggestion
  when: os == 'linux'
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout and ansible_facts.services[item].state != 'running')
```suggestion
  when: (os == 'linux' and 'server' in wazuh_info.stdout and ansible_facts.services[item].state != 'running')
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: (os == 'Linux' and 'agent' in wazuh_info.stdout)
```suggestion
  when: (os == 'linux' and 'agent' in wazuh_info.stdout)
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: (os == 'Linux' and 'agent' in wazuh_info.stdout and ansible_facts.services[service].state != 'running')
```suggestion
  when: (os == 'linux' and 'agent' in wazuh_info.stdout and ansible_facts.services[service].state != 'running')
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/ansible_roles/service_controller/tasks/get_installation_type.yaml
> +  when: os == 'Linux'
```suggestion
  when: os == 'linux'
```

2022-08-25 16:44 UTC, jmv74211 commented on tests/end_to_end/data/validation_templates/general_validation.j2
> +        os: "{% raw %}{{ 'Windows' if ansible_os_family == 'Windows' else 'Linux' }}{% endraw %}"
```suggestion
        os: "{% raw %}{{ 'windows' if ansible_os_family == 'Windows' else 'linux' }}{% endraw %}"
```

2022-08-25 17:07 UTC, mauromalara commented on tests/end_to_end/README.md
> +When adding or modifying any test it is necesry to modify the file with the environment data, placed in `tests/end_to_end/data/env_requirements.json`
Done in 47c199b

2022-08-25 17:07 UTC, mauromalara commented on tests/end_to_end/data/validation_templates/general_validation.j2
> +        os: "{% raw %}{{ 'Windows' if ansible_os_family == 'Windows' else 'Linux' }}{% endraw %}"
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/service_controller/tasks/get_installation_type.yaml
> +  when: os == 'Linux'
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: (os == 'Linux' and 'agent' in wazuh_info.stdout and ansible_facts.services[service].state != 'running')
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: (os == 'Linux' and 'agent' in wazuh_info.stdout)
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout and ansible_facts.services[item].state != 'running')
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_wazuh_components.yaml
> +  when: os == 'Linux'
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
> +  when: (os == "Windows" and version.stdout.split(" ")[1].split(".")[0] | int < 3)
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
> +  when: os == 'Windows'
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_python.yaml
> +  when: (os == "Linux" and ansible_python['version']['major'] < 3)
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_os.yaml
> +  when: (ansible_distribution not in supported_distros and os == "Linux")
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_os.yaml
> +  when: (os == "Windows" and os not in supported_distros)
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_filebeat_indexer.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout and 'ERROR' in test_result.stdout)
Done in f44f8b1

2022-08-25 17:08 UTC, mauromalara commented on tests/end_to_end/data/ansible_roles/host_checker/tasks/check_controller_indexer.yaml
> +  when: (os == 'Linux' and 'server' in wazuh_info.stdout)
Done in f44f8b1

2022-08-25 17:13 UTC, jmv74211 approved these changes

2022-08-25 17:13 UTC, merged