2927 remove skipped fim tests 4.4
wazuh/wazuh-qa pull request #3182
Opened 2022-08-17 13:06 UTC by damarisg

|Related issue|
|-------------|
|             |

## Description

### Added

- Item 1
- Item n

### Updated

- Item 1
- Item n

### Deleted

- Item 1
- Item n

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @user (Developer)  |   test_fim/        | ⚫⚫⚫ | ⚫⚫⚫ |   Centos - Manager      |         | Nothing to highlight |
| @user (Developer)  |  test_fim/     | ⚫⚫⚫ | ⚫⚫⚫ |   Centos, Ubuntu, Solaris, MacOS - Agent|         | Nothing to highlight |
| @user (Developer)  | test_fim/     | ⚫⚫⚫ | ⚫⚫⚫ |   Windows - Agent|         | Nothing to highlight |
| @user (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2022-08-22 09:45 UTC, jmv74211 requested changes

2022-08-22 09:45 UTC, jmv74211 commented on CHANGELOG.md
> +-  FIM IT: Remove all skipped tests ([#2927](https://github.com/wazuh/wazuh-qa/issues/2927)) \- (Framework + Tests)
```suggestion
- Remove all  FIM integration skipped tests ([#2927](https://github.com/wazuh/wazuh-qa/issues/2927)) \- (Framework + Tests)
```

2022-08-22 12:56 UTC, damarisg commented on CHANGELOG.md
> +-  FIM IT: Remove all skipped tests ([#2927](https://github.com/wazuh/wazuh-qa/issues/2927)) \- (Framework + Tests)
Fixed on cff5804ec8bed93d5ba34ffa7834760df1d7cd82

2022-08-23 15:24 UTC, jmv74211 approved these changes

2022-08-23 15:24 UTC, merged