Add a test to check the analysisd socket properties
wazuh/wazuh-qa pull request #3365
Opened 2022-09-26 20:08 UTC by mauromalara

|Related issue|
|-------------|
| #3364 |

## Description

The `test_queue_socket_properties` test was developed to be merged into the master branch (at that time, it was v4.3). However, in the middle of development, the master branch moved to v4.4, so this test was never merged into v4.3 (which was the initial target version).

### Added

- `tests/integration/test_analysisd/test_queue_socket_properties/test_queue_socket_properties.py`: Test added

### Updated

- `deps/wazuh_testing/wazuh_testing/tools/__init__.py`: Added a variable for the Analysisd module
- `tests/integration/test_analysisd/conftest.py`: Imports changed, and function refactored

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @mauromalara (Developer)  | integration/test_analysisd/test_queue_socket_properties/ | ⚫⚫⚫ | [🟢](https://github.com/wazuh/wazuh-qa/files/9649315/report1.zip) [🟢](https://github.com/wazuh/wazuh-qa/files/9649316/report2.zip) [🟢](https://github.com/wazuh/wazuh-qa/files/9649317/report3.zip) |         | 5c4aa6f | Nothing to highlight |
| @user (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2022-09-26 22:19 UTC, mauromalara commented
**Note:** I have executed the entire **Analysisd** test suite to be sure that the added test does not affect it.

2022-09-28 13:40 UTC, damarisg requested changes

2022-09-28 13:40 UTC, damarisg commented on CHANGELOG.md
> +
It has the project `4.3.9` but in the documentation, you add it on `4.3.8`. 

Why you don't respect the new syntax defined? it  shouldn't be like this: 

> Add Analysisd IT - new test to check analysisd socket properties ([#2405](https://github.com/wazuh/wazuh-qa/pull/2405)) \- (Framework + Tests)

2022-09-28 13:41 UTC, damarisg commented
It was merged previously on another branches, so here we only need to change the changelog file and where to merge it. So, I only checked the changelog file. 

Could you check why reason failed Conventional commits check, please?

2022-09-28 17:40 UTC, damarisg commented on CHANGELOG.md
> +
This behavior is expected since only the branch was generated but migrated with the same changes.

2022-09-30 10:10 UTC, jmv74211 commented on tests/integration/test_analysisd/conftest.py
> +    truncate_file(LOG_FILE_PATH)
A fixture must do only one thing, it must be separate.

2022-09-30 10:11 UTC, jmv74211 commented on tests/integration/test_analysisd/conftest.py
> +    check_daemon_status(running_condition=True, target_daemon=ANALYSISD_DAEMON)
This may not be interesting, because sometimes, you want to restart analysisd to know that the configuration is wrong.

2022-10-03 15:17 UTC, jmv74211 approved these changes

2022-10-03 15:18 UTC, merged