Fix Authd IT force_options tests
wazuh/wazuh-qa pull request #3374
Opened 2022-09-28 14:22 UTC by Deblintrake09

|Related issue|
|-------------|
| #3267 |

## Description

After a change was made in a message, we had to test cases in `test_authd/test_force/test_authd_force_options.py`

Refs: wazuh/wazuh#14549

### Updated

- `test_authd_force_options.py`: Update test cases configuration an messages being checked for `force_insert` and `force_time` options

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @Deblintrake09  (Developer)  | test_authd/ |  |  | Centos8 |  | Nothing to highlight |
| @user (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |
``

2022-09-28 20:17 UTC, damarisg approved these changes

2022-09-28 20:22 UTC, damarisg commented
I need that you pay more attention when you do each commit. Last commit was linked a wrong issue.

2022-09-29 14:59 UTC, jmv74211 requested changes

2022-09-29 14:59 UTC, jmv74211 commented on CHANGELOG.md
> +- Fix Authd force_insert tests ([#3374](https://github.com/wazuh/wazuh-qa/pull/3374)) \- (Tests)
```suggestion
- Update authd force_insert tests ([#3374](https://github.com/wazuh/wazuh-qa/pull/3374)) \- (Tests)
```

2022-09-29 15:16 UTC, closed without merging