Refactor integratord `test_integratord_read_json_file_deleted`
wazuh/wazuh-qa pull request #3540
Opened 2022-10-31 18:52 UTC by fedepacher

|Related issue|
|-------------|
|    https://github.com/wazuh/wazuh-qa/issues/3298         |

## Description

This PR aims to add the development made by @mauromalara in this [PR](https://github.com/wazuh/wazuh-qa/pull/3362). I have added some minor changes to the code and made a fixture refactor.

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @fedepacher  (Developer)  |           | [🟢](https://github.com/wazuh/wazuh-qa/files/9904003/manager_html_report_Test_integration_B33408_20221031191552.zip)  [🟢](https://github.com/wazuh/wazuh-qa/files/9904004/manager_html_report_Test_integration_B33409_20221031193023.zip)  [🟢](https://github.com/wazuh/wazuh-qa/files/9904005/manager_html_report_Test_integration_B33410_20221031193035.zip) |  [🟢](https://github.com/wazuh/wazuh-qa/files/9903995/r1-3298.zip)  [🟢](https://github.com/wazuh/wazuh-qa/files/9903996/r2-3298.zip)  [🟢](https://github.com/wazuh/wazuh-qa/files/9903997/r3-3298.zip) |         |         |  |
| @Rebits  (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2022-11-22 14:45 UTC, jmv74211 requested changes

2022-11-28 19:23 UTC, fedepacher commented on tests/integration/test_integratord/conftest.py
> +    check_integratord_event(file_monitor=file_monitor, timeout=T_20,
Done in [here](https://github.com/wazuh/wazuh-qa/pull/3540/commits/cef625211244aafe84c6e5dc4cdb6410786ddb51)

2022-11-28 19:24 UTC, fedepacher commented on deps/wazuh_testing/wazuh_testing/modules/integratord/__init__.py
> +CB_SLACK_ENABLED = fr".*{INTEGRATORD_PREFIX}.*Enabling integration for: 'slack'.*"
Done in [here](https://github.com/wazuh/wazuh-qa/pull/3540/commits/cef625211244aafe84c6e5dc4cdb6410786ddb51)

2022-11-28 19:24 UTC, fedepacher commented on deps/wazuh_testing/wazuh_testing/tools/monitoring.py
> +def callback_generator(regex):
Done in [here](https://github.com/wazuh/wazuh-qa/pull/3540/commits/cef625211244aafe84c6e5dc4cdb6410786ddb51)

2023-02-03 09:05 UTC, mauromalara commented
Before merging these changes, it is necessary to merge [this PR](https://github.com/wazuh/wazuh-jenkins/pull/4023) in the "wazuh-jenkins" repository.
> More info: https://github.com/wazuh/wazuh-jenkins/issues/3838#issuecomment-1263990324

Also, it is necessary to merge [the backport to 4.5](https://github.com/wazuh/wazuh-jenkins/pull/3860) and create a backport of [this PR](https://github.com/wazuh/wazuh-jenkins/pull/4023) to `4.5`

2023-02-07 14:16 UTC, mauromalara commented on tests/integration/conftest.py
> +        "--slack-webhook-url",
PR: https://github.com/wazuh/wazuh-jenkins/pull/4023

2023-02-07 18:28 UTC, mauromalara commented
### Wazuh Jenkins dependency

This PR depends on some changes to be merged in the `wazuh-jenkins` repo in the following order:

- [ ] https://github.com/wazuh/wazuh-jenkins/pull/4689
- [ ] wazuh/wazuh-jenkins#4690
- [ ] wazuh/wazuh-jenkins#4691
- [ ] wazuh/wazuh-jenkins#4692

2023-02-08 09:33 UTC, mauromalara commented
### IT executions

|R1|R2|R3
|--|--|--
| [🟢](https://ci.wazuh.info/job/Test_integration/36390/) | [🟢](https://ci.wazuh.info/job/Test_integration/36391/) | [🟢](https://ci.wazuh.info/job/Test_integration/36392/)

2023-02-08 09:35 UTC, mauromalara commented on tests/integration/conftest.py
> +            control_service('stop', daemon=daemon)
IT Executions: https://github.com/wazuh/wazuh-qa/pull/3540#issuecomment-1422299461

2023-02-09 09:10 UTC, mauromalara commented
## Dependency

- Merge #3915

2023-05-09 14:57 UTC, juliamagan requested changes
Please update branches and launch the tests to check that everything works as expected.

2023-05-11 01:57 UTC, mauromalara commented
## Last results

| R1 | R2 | R3 |
|--------|--------|--------|
| [🟢](https://github.com/wazuh/wazuh-qa/files/11447407/Archive.2.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/11447408/Archive.3.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/11447406/Archive.zip) |

### Note ⚠️ 

This PR is blocked by https://github.com/wazuh/wazuh-qa/issues/4126 because it depends on that fix to get merged.

2023-05-12 19:22 UTC, mauromalara commented
## After merge

https://github.com/wazuh/wazuh-qa/issues/4165

2023-05-30 16:29 UTC, Rebits approved these changes
LGTM

2023-06-01 13:10 UTC, merged