Trusted Advisor integration tests
wazuh/wazuh-qa pull request #3736
Opened 2023-01-09 20:18 UTC by nico-stefani

|Related issue|
|-------------|
|      #3341     |

## Description

This PR adds tests for AWS Trusted Advisor integration

### Added

#### Tier 0
- Default configuration tests
- `remove_from_bucket` parameter tests
- `only_logs_after` parameter tests
- `path` parameter tests
- `discard_regex` parameter tests

#### Tier 1
- `only_logs_after` parameter tests
---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @nico-stefani  (Developer)  | `tests/integration/test_aws` | ⚫⚫⚫ | :green_circle: :green_circle:  | Ubuntu 22.04    |      | Nothing to highlight |
| @reviewer (Reviewer)   | | ⚫⚫⚫ |  |   |      | Nothing to highlight |

### Tier 0 results
```python

```

### Tier 1 results

```python

```

2023-01-26 20:40 UTC, nico-stefani commented on deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
> +        return buffer.getvalue()
For the reviewer, please disregard this already has been fixed in https://github.com/wazuh/wazuh-qa/pull/3699/.

2023-01-26 20:40 UTC, nico-stefani commented on deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
> +        )
For the reviewer, please disregard this already has been fixed in https://github.com/wazuh/wazuh-qa/pull/3715/.

2023-02-02 17:47 UTC, fdalmaup requested changes

2023-02-02 17:47 UTC, fdalmaup commented on tests/integration/test_aws/test_discard_regex.py
> +            'did not process the expected amout of logs'
```suggestion
            'The AWS module did not show the correct message about discard regex or ',
            'did not process the expected amount of logs'
```

2023-02-02 20:29 UTC, fdalmaup approved these changes

2023-02-02 20:30 UTC, fdalmaup commented
LGTM

2023-02-16 15:48 UTC, davidjiglesias approved these changes

2023-02-16 15:48 UTC, merged