GuardDuty integration tests
wazuh/wazuh-qa pull request #3762
Opened 2023-01-16 20:12 UTC by nico-stefani

|Related issue|
|-------------|
|      #3341     |

## Description

This PR adds tests for AWS Trusted Advisor integration

### Added

#### Tier 0
- Default configuration tests
- `remove_from_bucket` parameter tests
- `only_logs_after` parameter tests
- `path` parameter tests
- `discard_regex` parameter tests

#### Tier 1
- `only_logs_after` parameter tests
---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @nico-stefani  (Developer)  | `tests/integration/test_aws` | ⚫⚫⚫ | :green_circle: :red_circle:  | Ubuntu 22.04    |  [^1]  | Nothing to highlight |
| @reviewer (Reviewer)   | | ⚫⚫⚫ |  |   |      | Nothing to highlight |

### Tier 0 results
```python
root@ubuntu-jammy:/home/vagrant/qa/tests/integration/test_aws# pytest -k 'guardduty' --tier 0
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 24 items / 16 deselected / 8 selected

test_basic.py .                                                                                                                                                                                               [ 12%]
test_discard_regex.py .                                                                                                                                                                                       [ 25%]
test_only_logs_after.py ..                                                                                                                                                                                    [ 50%]
test_path.py ...                                                                                                                                                                                              [ 87%]
test_remove_from_bucket.py .                                                                                                                                                                                  [100%]

================================================================================================= warnings summary ==================================================================================================
../../../../../../usr/local/lib/python3.10/dist-packages/_pytest/cacheprovider.py:433
  /usr/local/lib/python3.10/dist-packages/_pytest/cacheprovider.py:433: PytestCacheWarning: cache could not write path /home/vagrant/qa/tests/integration/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../../../../../../usr/local/lib/python3.10/dist-packages/_pytest/stepwise.py:52
  /usr/local/lib/python3.10/dist-packages/_pytest/stepwise.py:52: PytestCacheWarning: cache could not write path /home/vagrant/qa/tests/integration/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================= 8 passed, 16 deselected, 2 warnings in 165.57s (0:02:45) ==============================================================================
```

### Tier 1 results

```python
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 24 items / 23 deselected / 1 selected

test_only_logs_after.py F                                                [100%]

=================================== FAILURES ===================================
------------------------------ Captured log call -------------------------------
DEBUG    wazuh_testing:cli_utils.py:23 Calling AWS module with: '[PosixPath('/var/ossec/wodles/aws/aws-s3'), '--bucket', 'wazuh-guardduty-integration-tests', '--type', 'guardduty', '--regions', 'us-east-1', '--aws_profile', 'qa', '--debug', '2']'
DEBUG    wazuh_testing:cli_utils.py:52 DEBUG: +++ Debug mode on - Level: 2
DEBUG    wazuh_testing:cli_utils.py:52 DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG    wazuh_testing:cli_utils.py:52 DEBUG: +++ Table does not exist; create
DEBUG    wazuh_testing:cli_utils.py:52 DEBUG: +++ Marker: 2023/01/16
DEBUG    wazuh_testing:cli_utils.py:52 DEBUG: ++ Skipping file with another prefix: test_prefix/2022/11/21/firehose_guardduty-1-20221121T1809Z.json
DEBUG    wazuh_testing:cli_utils.py:52 DEBUG: +++ DB Maintenance
ERROR    wazuh_testing:cli_utils.py:62 Some logs may were processed
ERROR    wazuh_testing:cli_utils.py:63 Results found: 0
ERROR    wazuh_testing:cli_utils.py:64 Results expected: 1
=========================== short test summary info ============================
FAILED test_only_logs_after.py::test_multiple_calls[guardduty_only_logs_after_multiple_calls]
================ 1 failed, 23 deselected, 3 warnings in 19.61s =================
```
[^1]: Because the module is not showing the message about no logs to process, the *tier 1* test is falling. This should be fixed in his respective issue.

2023-01-26 20:42 UTC, nico-stefani commented on deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
> +        return buffer.getvalue()
For the reviewer, please disregard this already has been fixed in https://github.com/wazuh/wazuh-qa/pull/3699/.

2023-01-31 14:11 UTC, fdalmaup requested changes
The Tier 0 test `test_discard_regex[guardduty_discard_regex]` fails with the following error message:
<details>
    
    root@ubuntu-focal:/home/vagrant/wazuh-qa/tests/integration/test_aws# pytest -k 'guardduty' --tier 0
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.8.10, pytest-5.0.0, py-1.11.0, pluggy-0.13.1
    rootdir: /home/vagrant/wazuh-qa/tests/integration, inifile: pytest.ini
    plugins: html-2.0.1, metadata-2.0.4, testinfra-5.0.0
    collected 24 items / 16 deselected / 8 selected                                                                                                                 
    
    test_basic.py .                                                                                                                                           [ 12%]
    test_discard_regex.py F                                                                                                                                   [ 25%]
    test_only_logs_after.py ..                                                                                                                                [ 50%]
    test_path.py ...                                                                                                                                          [ 87%]
    test_remove_from_bucket.py .                                                                                                                              [100%]
    
    =========================================================================== FAILURES ============================================================================
    __________________________________________________________ test_discard_regex[guardduty_discard_regex] __________________________________________________________
    
    configuration = {'metadata': {'bucket_name': 'wazuh-guardduty-integration-tests', 'bucket_type': 'guardduty', 'description': 'GuardDut...elements': [{'disabled': {'value': 'no'}}, {'bucket': {'attributes': [...], 'elements': [...]}}], 'section': 'wodle'}]}
    metadata = {'bucket_name': 'wazuh-guardduty-integration-tests', 'bucket_type': 'guardduty', 'description': 'GuardDuty discard regex configurations', 'discard_field': 'partition', ...}
    load_wazuh_basic_configuration = None, set_wazuh_configuration = None, clean_s3_cloudtrail_db = None, configure_local_internal_options_function = None
    truncate_monitored_files = None, restart_wazuh_function = None, wazuh_log_monitor = <wazuh_testing.tools.monitoring.FileMonitor object at 0x7f20a644b5e0>
    
        @pytest.mark.tier(level=0)
        @pytest.mark.parametrize('configuration, metadata', zip(configurations, configuration_metadata), ids=case_ids)
        def test_discard_regex(
            configuration, metadata, load_wazuh_basic_configuration, set_wazuh_configuration, clean_s3_cloudtrail_db,
            configure_local_internal_options_function, truncate_monitored_files, restart_wazuh_function, wazuh_log_monitor,
        ):
            """
            description: Fetch logs excluding the ones that match with the regex.
            test_phases:
                - setup:
                    - Load Wazuh light configuration.
                    - Apply ossec.conf configuration changes according to the configuration template and use case.
                    - Apply custom settings in local_internal_options.conf.
                    - Truncate wazuh logs.
                    - Restart wazuh-manager service to apply configuration changes.
                - test:
                    - Check in the ossec.log that a line has appeared calling the module with correct parameters.
                    - Check the expected number of events were forwarded to analysisd, only logs stored in the bucket and skips
                      the ones that match with regex.
                    - Check the database was created and updated accordingly.
                - teardown:
                    - Truncate wazuh logs.
                    - Restore initial configuration, both ossec.conf and local_internal_options.conf.
                    - Delete the uploaded file
            wazuh_min_version: 4.5.0
            parameters:
                - configuration:
                    type: dict
                    brief: Get configurations from the module.
                - metadata:
                    type: dict
                    brief: Get metadata from the module.
                - load_wazuh_basic_configuration:
                    type: fixture
                    brief: Load basic wazuh configuration.
                - set_wazuh_configuration:
                    type: fixture
                    brief: Apply changes to the ossec.conf configuration.
                - clean_s3_cloudtrail_db:
                    type: fixture
                    brief: Delete the DB file before and after the test execution.
                - configure_local_internal_options_function:
                    type: fixture
                    brief: Apply changes to the local_internal_options.conf configuration.
                - truncate_monitored_files:
                    type: fixture
                    brief: Truncate wazuh logs.
                - restart_wazuh_daemon_function:
                    type: fixture
                    brief: Restart the wazuh service.
                - wazuh_log_monitor:
                    type: fixture
                    brief: Return a `ossec.log` monitor.
            assertions:
                - Check in the log that the module was called with correct parameters.
                - Check the expected number of events were forwarded to analysisd.
                - Check the database was created and updated accordingly.
            input_description:
                - The `configuration_discard_regex` file provides the module configuration for this test.
                - The `cases_discard_regex` file provides the test cases.
            """
            bucket_name = metadata['bucket_name']
            bucket_type = metadata['bucket_type']
            only_logs_after = metadata['only_logs_after']
            discard_field = metadata['discard_field']
            discard_regex = metadata['discard_regex']
            found_logs = metadata['found_logs']
            skipped_logs = metadata['skipped_logs']
        
            pattern = fr'.*The "{discard_regex}" regex found a match in the "{discard_field}" field. The event will be skipped.'
        
            parameters = [
                'wodles/aws/aws-s3',
                '--bucket', bucket_name,
                '--aws_profile', 'qa',
                '--only_logs_after', only_logs_after,
                '--discard-field', discard_field,
                '--discard-regex', discard_regex,
                '--type', bucket_type,
                '--debug', '2'
            ]
        
            # Check AWS module started
            wazuh_log_monitor.start(
                timeout=global_parameters.default_timeout,
                callback=event_monitor.callback_detect_aws_module_start,
                error_message='The AWS module did not start as expected',
            ).result()
        
            # Check command was called correctly
            wazuh_log_monitor.start(
                timeout=global_parameters.default_timeout,
                callback=event_monitor.callback_detect_aws_module_called(parameters),
                error_message='The AWS module was not called with the correct parameters',
            ).result()
        
    >       wazuh_log_monitor.start(
                timeout=T_20,
                callback=event_monitor.callback_detect_event_processed_or_skipped(pattern),
                error_message=(
                    'The AWS module did not show correct message about discard regex or ',
                    'did not process the  [...]

2023-02-02 19:00 UTC, nico-stefani commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +def callback_detect_event_processed_or_skipped(pattern):
Fixed in b098d0d1c9598c76c8c0f67e8014652a683728d7

2023-02-02 19:02 UTC, nico-stefani commented
> The Tier 0 test `test_discard_regex[guardduty_discard_regex]` fails with the following error message:
> 
> Additionally, the data generated for the testing corresponds to the deprecated implementation of AWSGuardDuty (since [wazuh/wazuh#15226](https://github.com/wazuh/wazuh/pull/15226)). The tests should also address cases where native GuardDuty logs are used.

The native test cases were added in cf8b22d5ad6cde58df808d5b1d8c1c443660193c. 
Also the test `guardduty_discard_regex` was fixed in 85f86e3ae03c5b143371e7a0e9317a8502946541.

2023-02-03 12:36 UTC, fdalmaup approved these changes
LGTM!

2023-02-16 17:36 UTC, davidjiglesias approved these changes

2023-02-16 17:36 UTC, merged