WAF integration tests
wazuh/wazuh-qa pull request #3763
Opened 2023-01-16 21:55 UTC by nico-stefani

|Related issue|
|-------------|
|      #3343     |

## Description

This PR adds tests for AWS WAF integration

### Added

#### Tier 0
- Default configuration tests
- `remove_from_bucket` parameter tests
- `only_logs_after` parameter tests
- `path` parameter tests
- `discard_regex` parameter tests

#### Tier 1
- `only_logs_after` parameter tests
---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @nico-stefani  (Developer)  | `tests/integration/test_aws` | ⚫⚫⚫ | :green_circle: :green_circle:  | Ubuntu 22.04|  | Nothing to highlight |
| @reviewer (Reviewer)   | | ⚫⚫⚫ |  |   |      | Nothing to highlight |

### Tier 0 results
```python
```

### Tier 1 results

```python

```

2023-01-26 20:43 UTC, nico-stefani commented on deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
> +        return buffer.getvalue()
For the reviewer, please disregard this already has been fixed in https://github.com/wazuh/wazuh-qa/pull/3699/.

2023-02-02 14:26 UTC, fdalmaup requested changes
The Tier 0 `test_discard_regex[waf_discard_regex]` fails with the following output:
<details>

    root@ubuntu-focal:/home/vagrant/wazuh-qa/tests/integration/test_aws# pytest -vv -k 'waf' --tier 0
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.8.10, pytest-5.0.0, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3
    cachedir: .pytest_cache
    metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-137-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.0.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '2.0.1', 'metadata': '2.0.4', 'testinfra': '5.0.0'}}
    rootdir: /home/vagrant/wazuh-qa/tests/integration, inifile: pytest.ini
    plugins: html-2.0.1, metadata-2.0.4, testinfra-5.0.0
    collected 24 items / 16 deselected / 8 selected                                                                                                                 
    
    test_basic.py::test_defaults[waf_defaults] PASSED                                                                                                         [ 12%]
    test_discard_regex.py::test_discard_regex[waf_discard_regex] FAILED                                                                                       [ 25%]
    test_only_logs_after.py::test_without_only_logs_after[waf_without_only_logs_after] PASSED                                                                 [ 37%]
    test_only_logs_after.py::test_with_only_logs_after[waf_with_only_logs_after] PASSED                                                                       [ 50%]
    test_path.py::test_path[waf_path_with_data] PASSED                                                                                                        [ 62%]
    test_path.py::test_path[waf_path_without_data] PASSED                                                                                                     [ 75%]
    test_path.py::test_path[waf_inexistent_path] PASSED                                                                                                       [ 87%]
    test_remove_from_bucket.py::test_remove_from_bucket[waf_remove_from_bucket] PASSED                                                                        [100%]
    
    =========================================================================== FAILURES ============================================================================
    _____________________________________________________________ test_discard_regex[waf_discard_regex] _____________________________________________________________
    
    configuration = {'metadata': {'bucket_name': 'wazuh-waf-integration-tests', 'bucket_type': 'waf', 'description': 'WAF discard regex co...elements': [{'disabled': {'value': 'no'}}, {'bucket': {'attributes': [...], 'elements': [...]}}], 'section': 'wodle'}]}
    metadata = {'bucket_name': 'wazuh-waf-integration-tests', 'bucket_type': 'waf', 'description': 'WAF discard regex configurations', 'discard_field': 'action', ...}
    load_wazuh_basic_configuration = None, set_wazuh_configuration = None, clean_s3_cloudtrail_db = None, configure_local_internal_options_function = None
    truncate_monitored_files = None, restart_wazuh_function = None, wazuh_log_monitor = <wazuh_testing.tools.monitoring.FileMonitor object at 0x7fac62f40850>
    
        @pytest.mark.tier(level=0)
        @pytest.mark.parametrize('configuration, metadata', zip(configurations, configuration_metadata), ids=case_ids)
        def test_discard_regex(
            configuration, metadata, load_wazuh_basic_configuration, set_wazuh_configuration, clean_s3_cloudtrail_db,
            configure_local_internal_options_function, truncate_monitored_files, restart_wazuh_function, wazuh_log_monitor,
        ):
            """
            description: Fetch logs excluding the ones that match with the regex.
            test_phases:
                - setup:
                    - Load Wazuh light configuration.
                    - Apply ossec.conf configuration changes according to the configuration template and use case.
                    - Apply custom settings in local_internal_options.conf.
                    - Truncate wazuh logs.
                    - Restart wazuh-manager service to apply configuration changes.
                - test:
                    - Check in the ossec.log that a line has appeared calling the module with correct parameters.
                    - Check the expected number of events were forwarded to analysisd, only logs stored in the bucket and skips
                      the ones that match with regex.
                    - Check the database was created and updated accordingly.
                - teardown:
                    - Truncate wazuh logs.
                    - Restore initial configuration, both ossec.conf and local_internal_options.conf.
                    - Delete the uploaded file
            wazuh_min_version: 4.5.0
            parameters:
                - configuration:
                    type: dict
                    brief: Get configurations from the module.
                - metadata:
                    type: dict
                    brief: Get metadata from the module.
                - load_wazuh_basic_configuration:
                    type: fixture
                    brief: Load basic wazuh configuration.
                - set_wazuh_configuration:
                    type: fixture
                    brief: Apply changes to the ossec.conf configuration.
                - clean_s3_cloudtrail_db:
                    type: fixture
                    brief: Delete the DB file before and after the test execution.
                - configure_local_internal_options_function:
                    type: fixture
                    brief: Apply changes to the local_internal_options.conf configuration.
                - truncate_monitored_files:
                    type: fixture
                    brief: Truncate wazuh logs.
                - restart_wazuh_daemon_function:
                    type: fixture
                    brief: Restart the wazuh service.
                - wazuh_log_monitor:
                    type: fixture
                    brief: Return a `ossec.log` monitor.
            assertions:
                - Check in the log that the module was called with correct parameters.
                - Check the expected number of events were forwarded to analysisd.
                - Check the database was created and updated accordingly.
            input_description:
                - The `configuration_discard_regex` file provides the module configuration for this test.
                - The `cases_discard_regex` file provides the test cases.
            """
            bucket_name = metadata['bucket_name']
            bucket_type = metadata['bucket_type']
            only_logs_after = metadata['only_logs_after']
            discard_field = metadata['discard_field']
            discard_regex = metadata['discard_regex']
            found_logs = metadata['found_logs']
            skipped_logs = metadata['skipped_logs']
        
            pattern = fr'.*The "{discard_regex}" regex found a match in the "{discard_field}" field. The event will be skipped.'
        
            parameters = [
                'wodles/aws/aws-s3',
                '--bucket', bucket_name,
                '--aws_profile', 'qa',
                '--only_logs_after', only_logs_after,
                '--discard-field', discard_field,
                '--discard-regex', discard_regex,
                '--type', bucket_type,
                '--debug', '2'
            ]
        
            # Check AWS module started
            wazuh_log_monitor.start(
                timeout=global_parameters.default_timeout,
                callback=event_monitor.callback_detect_aws_module_start,
                error_message='The AWS module did not start as  [...]

2023-02-02 14:26 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
> +            ste: Syntetic data.
```suggestion
            str: Syntetic data.
```

2023-02-02 17:49 UTC, fdalmaup requested changes

2023-02-02 17:49 UTC, fdalmaup commented on tests/integration/test_aws/test_discard_regex.py
> +            'did not process the expected amout of logs'
```suggestion
            'The AWS module did not show the correct message about discard regex or ',
            'did not process the expected amount of logs'
```

2023-02-02 21:03 UTC, nico-stefani commented
> The Tier 0 `test_discard_regex[waf_discard_regex]` fails with the following output:

Fixed in aa453cfcb374496e6fa2264162ad3133815c73c8.

2023-02-03 12:42 UTC, fdalmaup requested changes

2023-02-03 12:42 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/data_generator.py
> +            ste: Syntetic data.
```suggestion
            str: Syntetic data.
```

2023-02-03 12:59 UTC, fdalmaup approved these changes
LGTM

2023-02-24 14:41 UTC, davidjiglesias approved these changes

2023-02-24 14:41 UTC, merged