CloudWatch integration tests
wazuh/wazuh-qa pull request #3857
Opened 2023-01-26 20:30 UTC by nico-stefani

|Related issue|
|-------------|
|      #3346    |

## Description

This PR adds tests for AWS CloudWatch integration

### Added

#### Tier 0
- Default configuration tests
- `remove_from_bucket` parameter tests
- `only_logs_after` parameter tests
- `regions` parameter tests
- `log_group` parameter tests

#### Tier 1
- `only_logs_after` parameter tests
---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @nico-stefani  (Developer)  | `tests/integration/test_aws` | ⚫⚫⚫ | :red_circle: :green_circle:  | Ubuntu 22.04|  | [^1][^2][^3] |
| @reviewer (Reviewer)   | | ⚫⚫⚫ |  |   |      | Nothing to highlight |

### Tier 0 results
```python
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 25 items / 16 deselected / 9 selected

test_basic.py .                                                          [ 11%]
test_log_groups.py FF                                                    [ 33%]
test_only_logs_after.py ..                                               [ 55%]
test_regions.py ..F                                                      [ 88%]
test_remove_from_bucket.py .                                             [100%]

=================================== FAILURES ===================================
_____________ test_log_groups[cloudwatchlogs_log_groups_with_data] _____________
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:465 The AWS module was not called with the correct parameters
ERROR    wazuh_testing:monitoring.py:466 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:468 Results expected: 1

_____________ test_log_groups[cloudwatchlogs_inexistent_log_group] _____________
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:465 The AWS module did not show correct message non-existent log group
ERROR    wazuh_testing:monitoring.py:466 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:468 Results expected: 1

____________ test_service_regions[cloudwatchlogs_inexistent_region] ____________
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:465 The AWS module did not show correct message non-existent region
ERROR    wazuh_testing:monitoring.py:466 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:468 Results expected: 1
=========================== short test summary info ============================
FAILED test_log_groups.py::test_log_groups[cloudwatchlogs_log_groups_with_data]
FAILED test_log_groups.py::test_log_groups[cloudwatchlogs_inexistent_log_group]
FAILED test_regions.py::test_service_regions[cloudwatchlogs_inexistent_region]
====== 3 failed, 6 passed, 16 deselected, 3 warnings in 198.46s (0:03:18) ======
```

### Tier 1 results

```python
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 25 items / 24 deselected / 1 selected

test_only_logs_after.py .                                                [100%]

=============================== warnings summary ===============================
../../../../../../usr/local/lib/python3.10/dist-packages/_pytest/cacheprovider.py:433
  /usr/local/lib/python3.10/dist-packages/_pytest/cacheprovider.py:433: PytestCacheWarning: cache could not write path /home/vagrant/qa/tests/integration/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../../../../../../usr/local/lib/python3.10/dist-packages/_pytest/stepwise.py:52
  /usr/local/lib/python3.10/dist-packages/_pytest/stepwise.py:52: PytestCacheWarning: cache could not write path /home/vagrant/qa/tests/integration/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================ 1 passed, 24 deselected, 2 warnings in 41.45s =================
```
[^1]: Because the module was not called with the correct parameters, the `cloudwatchlogs_log_groups_with_data` test is failing. This should be fixed in his respective issue.
[^2]: Because the module is not showing the message about the non-existent log_group, the `cloudwatchlogs_inexistent_log_group` test is failing. This should be fixed in his respective issue.
[^3]: Because the module is not showing the message about the non-existent region, the `cloudwatchlogs_inexistent_region` test is failing. This should be fixed in his respective issue.

2023-02-02 15:39 UTC, fdalmaup requested changes

2023-02-02 15:39 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/cloudwatch_utils.py
> +    """Create a log event within the given log stram and group.
```suggestion
    """Create a log event within the given log stream and group.
```

2023-02-02 15:39 UTC, fdalmaup commented on tests/integration/test_aws/conftest.py
> +    """Delete the DB file before and after the test execution"""
```suggestion
    """Delete the DB file before and after the test execution."""
```

2023-02-02 15:39 UTC, fdalmaup commented on tests/integration/test_aws/test_basic.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 15:39 UTC, fdalmaup commented on tests/integration/test_aws/test_only_logs_after.py
> +            - Check the database was created and updated accordingly
```suggestion
            - Check the database was created and updated accordingly.
```

2023-02-03 12:58 UTC, fdalmaup approved these changes
LGTM

2023-03-03 08:56 UTC, davidjiglesias approved these changes

2023-03-03 08:56 UTC, merged