Parser integration tests
wazuh/wazuh-qa pull request #3882
Opened 2023-02-01 19:47 UTC by nico-stefani

|Related issue|
|-------------|
|      #3581     |

## Description

This PR closes #3581. Adds tests for AWS parser. 

### Added

#### Tier 0
- Missing  mandatory parameter tests
- Parameters with empty value tests
- Parameters with invalid value tests
- Multiple bucket and service tags tests

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @nico-stefani  (Developer)  | `tests/integration/test_aws` | ⚫⚫⚫ | :red_circle:  | Ubuntu 22.04    |    | [^1][^2] |
| @reviewer (Reviewer)   | | ⚫⚫⚫ |  |   |      | Nothing to highlight |

### Tier 0 results
```python
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/vagrant/qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 26 items

test_parser.py .....FFFF.FFF.F.FFF..FFF..                                [100%]

=================================== FAILURES ===================================
=========================== short test summary info ============================
FAILED test_parser.py::test_empty_values_in_bucket[parser_empty_only_logs_after_in_bucket]
FAILED test_parser.py::test_empty_values_in_bucket[parser_empty_regions_in_bucket]
FAILED test_parser.py::test_empty_values_in_bucket[parser_empty_path_in_bucket]
FAILED test_parser.py::test_empty_values_in_bucket[parser_empty_path_suffix_in_bucket]
FAILED test_parser.py::test_empty_values_in_service[parser_empty_log_groups_in_service]
FAILED test_parser.py::test_empty_values_in_service[parser_empty_only_logs_after_in_service]
FAILED test_parser.py::test_empty_values_in_service[parser_empty_regions_in_service]
FAILED test_parser.py::test_invalid_values_in_bucket[parser_invalid_name_in_bucket]
FAILED test_parser.py::test_invalid_values_in_bucket[parser_invalid_regions_in_bucket]
FAILED test_parser.py::test_invalid_values_in_bucket[parser_invalid_path_in_bucket]
FAILED test_parser.py::test_invalid_values_in_bucket[parser_invalid_path_suffix_in_bucket]
FAILED test_parser.py::test_invalid_values_in_service[parser_invalid_log_groups_in_service]
FAILED test_parser.py::test_invalid_values_in_service[parser_invalid_only_logs_after_in_service]
FAILED test_parser.py::test_invalid_values_in_service[parser_invalid_regions_in_service]
============ 14 failed, 12 passed, 3 warnings in 288.12s (0:04:48) =============
```

[^1]: Because the module is not showing the message about empty value, some of the `test_parser.py::test_empty_values_in_[bucket|service]` tests are falling. This should be fixed in his respective issue.
[^2]: Because the module is not showing the message about invalid value, some of the `test_parser.py::test_invalid_values_in_[bucket|service]` tests are falling. This should be fixed in his respective issue.

2023-02-02 20:23 UTC, fdalmaup requested changes

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/conftest.py
> +    """Restart all Wazuh daemons"""
```suggestion
    """Restart all Wazuh daemons."""
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +            brief: Return a `ossec.log` monitor
```suggestion
            brief: Return a `ossec.log` monitor.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +        - Check in the log that the module display the message about invalid value.
```suggestion
        - Check in the log that the module displays the message about an invalid value.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +        - Check in the log that the module display the message about invalid value.
```suggestion
        - Check in the log that the module displays the message about an invalid value.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +        - Check in the log that the module display the message about empty value.
```suggestion
        - Check in the log that the module displays the message about an empty value.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +        - Check in the log that the module display the message about empty value.
```suggestion
        - Check in the log that the module displays the message about an empty value.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +         - Check in the log that the module display the message about missing attribute.
```suggestion
        - Check in the log that the module displays the message about missing attributes.
```

2023-02-02 20:23 UTC, fdalmaup commented on tests/integration/test_aws/test_parser.py
> +         - Check in the log that the module display the message about missing attribute.
```suggestion
        - Check in the log that the module displays the message about missing attributes.
```

2023-02-02 20:23 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +        Optional[str]: Line if it match.
```suggestion
    """Detect if the AWS module displays an error about missing type.

    Args:
        line (str): Line to match.

    Returns:
        Optional[str]: Line if it matches.
```

2023-02-02 20:23 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +        Optional[str]: Line if it match.
```suggestion
    """Detect if the AWS module displays a warning about legacy config.

    Args:
        line (str): Line to match.

    Returns:
        Optional[str]: Line if it matches.
```

2023-02-02 20:23 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +        Optional[str]: Line if it match.
```suggestion
    """Detect if the AWS module displays a warning.

    Args:
        line (str): Line to match.

    Returns:
        Optional[str]: Line if it matches.
```

2023-02-02 20:23 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +        Optional[str]: Line if it match.
```suggestion
    """Detect if the AWS module was called.

    Args:
        line (str): Line to match.

    Returns:
        Optional[str]: Line if it matches.
```

2023-02-02 20:23 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +        Optional[str]: Line if it match.
```suggestion
    """Detect if the AWS module displays a message about an empty value.

    Args:
        line (str): Line to match.

    Returns:
        Optional[str]: Line if it matches.
```

2023-02-02 20:23 UTC, fdalmaup commented on deps/wazuh_testing/wazuh_testing/modules/aws/event_monitor.py
> +        Optional[str]: Line if it match.
```suggestion
    """Detect if the AWS module displays a message about an invalid value.

    Args:
        line (str): Line to match.

    Returns:
        Optional[str]: Line if it matches.
```

2023-02-03 14:20 UTC, fdalmaup approved these changes
LGTM

2023-03-08 11:21 UTC, davidjiglesias approved these changes

2023-03-08 11:21 UTC, merged