AWS integration tests readme
wazuh/wazuh-qa pull request #3892
Opened 2023-02-03 19:06 UTC by nico-stefani

|Related issue|
|#3348|
|             |

## Description

This PR adds the README for the AWS integration tests. Closes #3348.

### Added

- Main README.md for `tests/integration/test_aws/`

### Updated

- Add reference for AWS tests in `tests/integration/README.md`

2023-02-06 14:08 UTC, fdalmaup requested changes

2023-02-06 14:08 UTC, fdalmaup commented on tests/integration/test_aws/README.md
> +- credentials: Set the credentials at `$HOME/.aws/credentials` with the content:
```suggestion
- **credentials**
    Set the credentials at `$HOME/.aws/credentials` (being `HOME` the home directory of the user who runs the tests, more information [here](https://documentation.wazuh.com/current/amazon/services/prerequisites/credentials.html#profiles)) with the content:
```

2023-02-06 15:11 UTC, fdalmaup approved these changes
LGTM

2023-03-17 11:44 UTC, davidjiglesias approved these changes

2023-03-17 11:47 UTC, merged