Add multigroups tests cases for `test_assign_groups_guess`
wazuh/wazuh-qa pull request #3979
Opened 2023-02-23 13:51 UTC by juliamagan

|Related issue|
|-------------|
|     #3913        |

## Description

### Added

- Added `test_guess_multigroups`

### Updated

- Updated `remove_cluster_agents`: accept agent ids

---

## Testing performed

| Tester             | Test path | Jenkins | Local   | Commit | Notes                |
|--------------------|-----------|---------|--------|--------|----------------------|
| @juliamagan (Developer)  |    `system/test_cluster/test_agent_groups/test_assign_groups_guess.py`       | :no_entry_sign: :no_entry_sign: :no_entry_sign:  | ⚫⚫⚫ |        | Nothing to highlight |
| @user (Reviewer)   |           | :no_entry_sign: :no_entry_sign: :no_entry_sign: | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |           | Nothing to highlight |

2023-02-23 16:09 UTC, jmv74211 requested changes

2023-02-23 16:09 UTC, jmv74211 commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +        agent2_ip, agent2_id, agent2_name, ag2_manager_ip = register_agent(test_infra_agents[1], target_node,
This is not scalable

2023-02-24 14:12 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +        agent2_ip, agent2_id, agent2_name, ag2_manager_ip = register_agent(test_infra_agents[1], target_node,
Done in 67da75d

2023-02-24 14:12 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +        host_manager.add_block_to_file(host, path=f"{WAZUH_PATH}/etc/local_internal_options.conf",
Done in 67da75d

2023-03-01 10:52 UTC, jmv74211 requested changes

2023-03-01 10:52 UTC, jmv74211 commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +def modify_internal_options(status_guess_agent_group):
```suggestion
def modify_local_internal_options(status_guess_agent_group):
```

2023-03-01 10:52 UTC, jmv74211 commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
>      # Restart managers
Update this comment

2023-03-03 12:02 UTC, juliamagan commented on deps/wazuh_testing/wazuh_testing/tools/system.py
> +    def configure_internal_options(self, local_internal_options: dict):
Done in bdad304

2023-03-03 12:02 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
> +def modify_internal_options(status_guess_agent_group):
Done in bdad304

2023-03-03 12:03 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_assign_groups_guess.py
>      # Restart managers
Done in ccaa8e3

2023-03-07 08:51 UTC, jmv74211 approved these changes

2023-03-07 08:52 UTC, merged