Enhance FIM IT test_ambiguous_confs suite
wazuh/wazuh-qa pull request #4004
Opened 2023-03-07 17:39 UTC by Deblintrake09

|Related issue|
|-------------|
| #3591     |

## Description

This Issue aims to update the `test_fim/test_files/test_ambiguous_confs` IT suite to the new framework standard.

### Updated

- test_fim/test_files/test_ambiguous_confs/test_whodata_prevails_o
- Item n

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @Deblintrake09  (Developer)  |           | ⚫⚫⚫ | ⚫⚫⚫ |         |         | Nothing to highlight |
| @damarisg  (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2023-03-13 16:11 UTC, damarisg requested changes

2023-03-14 12:51 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/test_ambiguous_whodata_thread.py
> +            print("PRINT DIsABLED")
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-03-14 12:52 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/test_ambiguous_whodata_thread.py
> +        print("PRINT ENABLED")
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-03-14 12:52 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/data/test_cases/cases_ignore_works_over_restrict.yaml
> +    WHODATA: 'yes'
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-03-14 12:52 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/data/test_cases/cases_ignore_works_over_restrict.yaml
> +    WHODATA: 'yes'
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-03-14 12:52 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/data/test_cases/cases_whodata_prevails_over_realtime.yaml
> +  description: Check Whodata thread is enabled and is used with realtime enabled or disabled on same tag
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-03-14 12:52 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/data/test_cases/cases_whodata_prevails_over_realtime.yaml
> +  description: Check Whodata thread is enabled and is used with realtime enabled or disabled on same tag
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-03-14 12:52 UTC, Deblintrake09 commented on tests/integration/test_fim/test_files/test_ambiguous_confs/data/test_cases/cases_ignore_works_over_restrict.yaml
> +    WHODATA: 'yes'
Done in https://github.com/wazuh/wazuh-qa/pull/4004/commits/a5f0fdf882902e0866bdfefc9ce2ec871f5fa5fb

2023-04-26 12:33 UTC, closed without merging

2023-04-26 12:33 UTC, Deblintrake09 commented
Closed. Branch recreated in #4121