Add system tests for groups deletion
wazuh/wazuh-qa pull request #4057
Opened 2023-03-28 14:01 UTC by juliamagan

|Related issue|
|-------------|
|   #3912           |

## Description

Add a test that checks if groups are deleted correctly.

### Added

- Added `test_remove_group.py`
- Added `cases_remove_group.yaml`
- Added `remove_group_messages.yaml`
- Added `get_group_id()`
---

## Testing performed

| Tester             | Test path | Jenkins | Local   | Commit | Notes                |
|--------------------|-----------|---------|--------|--------|----------------------|
| @juliamagan  (Developer)  |    `tests/system/test_cluster/test_agent_groups/test_remove_group.py`       | :no_entry_sign: :no_entry_sign: :no_entry_sign: | ⚫⚫⚫ |               | Nothing to highlight |
| @user (Reviewer)   |           | :no_entry_sign: :no_entry_sign: :no_entry_sign: | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |               | Nothing to highlight |

2023-03-30 09:03 UTC, Rebits requested changes
Great job! Some changes are required

2023-03-30 10:05 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_remove_group.py
> +    # Check group is deleted or not if exepceted in agent table in every node
Done in a64da1c

2023-03-30 10:11 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_remove_group.py
> +import wazuh_testing as fw
Done in 7a8ee99

2023-03-30 10:16 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_remove_group.py
> +    """Fixture to create a group and assign an agent during the setup."""
Done in 4c28ae1

2023-03-30 10:19 UTC, juliamagan commented on tests/system/test_cluster/test_agent_groups/test_remove_group.py
> +
Done in 79b5ac1

2023-04-04 11:16 UTC, Rebits requested changes

2023-04-04 11:19 UTC, Rebits commented
### Report :green_circle: 

**Commit**: 04f636f49a79b654c3f3345824794f500e967a36

[report.zip](https://github.com/wazuh/wazuh-qa/files/11147846/report.zip)


> **Note**:
> Only new developed test was tested, it does not ensure correct integration in the system suite

2023-04-13 10:28 UTC, juliamagan commented on tests/system/__init__.py
> +        host_manager.run_command(host, f"/var/ossec/bin/agent_groups -q -r -g {id_group}")
Done in 174821d

2023-04-13 10:28 UTC, juliamagan commented on tests/system/__init__.py
>      # Delete group
Done in 91adbe7

2023-04-13 14:36 UTC, Rebits approved these changes
LGTM

2023-04-13 14:42 UTC, merged