Updated database version ` test_agent_database_version`  test
wazuh/wazuh-qa pull request #4128
Opened 2023-04-26 16:16 UTC by BelenValdivia

|Related issue|
|-------------|
|  https://github.com/wazuh/wazuh-qa/issues/4125           |

## Description

We need to update the Wazuh db test due to a schema upgrade to version 11

### Updated

- Database version from 10 to 11

---

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @BelenValdivia  (Developer)  |           | ⚫⚫⚫ | ⚫⚫⚫ |         |         | Nothing to highlight |
| @damarisg  (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2023-04-27 11:42 UTC, BelenValdivia commented
Changelog and Code analysis checks are skipping. I tried to re-run them.

2023-04-28 16:13 UTC, damarisg approved these changes

2023-05-02 07:18 UTC, juliamagan requested changes

2023-05-02 07:18 UTC, juliamagan commented on CHANGELOG.md
> +- Update schema database version ([#4128](https://github.com/wazuh/wazuh-qa/pull/4128)) \- (Tests)
This line should be at the top of the section.

2023-05-02 13:47 UTC, BelenValdivia commented
Merge together with https://github.com/wazuh/wazuh/pull/16065

2023-05-04 09:53 UTC, juliamagan approved these changes
LGTM

2023-07-10 13:59 UTC, merged