Move 4.5.0 `CHANGELOG.md` changes to 4.6.0
wazuh/wazuh-qa pull request #4331
Opened 2023-07-20 11:17 UTC by jnasselle

|Related issue|
|-------------|
|#4330|

## Description

This issue aims to move 4.5.0 changes to 4.6.0

2023-07-20 14:42 UTC, Rebits requested changes
These changes also belong to 4.6.0?
 
- New 'SCA' test suite and framework. ([#3566](https://github.com/wazuh/wazuh-qa/pull/3566)) \- (Framework + Tests)
- Add integration tests for AWS module. ([#3911](https://github.com/wazuh/wazuh-qa/pull/3911)) \- (Framework + Tests + Documentation)
- Add tests for msu patches with no associated CVE . ([#4009](https://github.com/wazuh/wazuh-qa/pull/4009)) \- (Framework + Tests)
@@ -33,6 +20,8 @@ Release report: TBD
- Add new tests for logcollector 'ignore' and 'restrict' options ([#3582](https://github.com/wazuh/wazuh-qa/pull/3582)) \- (Tests)
- Add 'Force reconnect' feature to agent_simulator tool. ([#3111](https://github.com/wazuh/wazuh-qa/pull/3111)) \- (Tools)
- Add new module to support migration tool. ([#3837](https://github.com/wazuh/wazuh-qa/pull/3837))

2023-07-20 16:24 UTC, jnasselle commented
> These changes also belong to 4.6.0?

Changes were based on the file content before bumping it to 4.6.0 https://github.com/wazuh/wazuh-qa/pull/4245

> 
> * New 'SCA' test suite and framework. ([#3566](https://github.com/wazuh/wazuh-qa/pull/3566)) - (Framework + Tests)
- Issue on project 4.6.0 https://github.com/wazuh/wazuh-qa/issues/3505
- Commit available since 4.6.0
```
git branch -r --contains 9106814210ee8e308e80c02eff68401a17f5c262
  origin/17388-aws-services-discard-regex-its
  origin/3278-correct_merged_file_generation
  origin/3709-shutdown_messagev2
  origin/3786-location-wildcards
  origin/3963-whodata-buffer
  origin/4.6.0
  origin/4.7.0
  origin/4055-aws-asl-integration-tests
  origin/4188-fix-openssl-errors
  origin/4282-update-framework-known-flaws
  origin/4290-changelog-tmp
  origin/5106-gcp-it-on-agents
  origin/HEAD -> origin/master
  origin/fix/4330-changelog-from-4.5.0-to-4.6.0
  origin/master
```
> * Add integration tests for AWS module. ([#3911](https://github.com/wazuh/wazuh-qa/pull/3911)) - (Framework + Tests + Documentation)
 - Issue on project 4.6.0 https://github.com/wazuh/wazuh-qa/issues/3333
- Commit available since 4.6.0
```
git branch -r --contains 87a6bde0d391f1b483d0edf8d4615afbf5869f6e
  origin/16204_remove_group_column
  origin/17388-aws-services-discard-regex-its
  origin/3278-correct_merged_file_generation
  origin/3709-shutdown_messagev2
  origin/3786-location-wildcards
  origin/3963-whodata-buffer
  origin/4.6.0
  origin/4.7.0
  origin/4055-aws-asl-integration-tests
  origin/4159-migration-example
  origin/4159-refactor-callbacks-and-event-monitor
  origin/4179-logcollector-windows
  origin/4188-fix-openssl-errors
  origin/4282-update-framework-known-flaws
  origin/4290-changelog-tmp
  origin/5106-gcp-it-on-agents
  origin/HEAD -> origin/master
  origin/fix/4330-changelog-from-4.5.0-to-4.6.0
  origin/framework-vulnerability-scan
  origin/master
  origin/wazuh-j
```
> * Add tests for msu patches with no associated CVE . ([#4009](https://github.com/wazuh/wazuh-qa/pull/4009)) - (Framework + Tests)
 - Issue on project 4.6.0 https://github.com/wazuh/wazuh-qa/issues/3361
- Commit available since 4.6.0
```
git branch -r --contains c440043df03aa7032247ea83b20627a657f9c05d
  origin/16204_remove_group_column
  origin/17388-aws-services-discard-regex-its
  origin/3278-correct_merged_file_generation
  origin/3709-shutdown_messagev2
  origin/3786-location-wildcards
  origin/3963-whodata-buffer
  origin/4.6.0
  origin/4.7.0
  origin/4055-aws-asl-integration-tests
  origin/4159-migration-example
  origin/4159-refactor-callbacks-and-event-monitor
  origin/4179-logcollector-windows
  origin/4188-fix-openssl-errors
  origin/4282-update-framework-known-flaws
  origin/4290-changelog-tmp
  origin/5106-gcp-it-on-agents
  origin/HEAD -> origin/master
  origin/fix/4330-changelog-from-4.5.0-to-4.6.0
  origin/framework-vulnerability-scan
  origin/master
  origin/wazuh-j
```
> * Add new tests for logcollector 'ignore' and 'restrict' options ([#3582](https://github.com/wazuh/wazuh-qa/pull/3582)) - (Tests)
 - Issue on project 4.6.0 https://github.com/wazuh/wazuh-qa/issues/3480
- Commit available since 4.6.0
```
git branch -r --contains 68863812b95d6b421e37a2aaec3567addb1f7c1c
  origin/16204_remove_group_column
  origin/17388-aws-services-discard-regex-its
  origin/3278-correct_merged_file_generation
  origin/3709-shutdown_message
  origin/3709-shutdown_messagev2
  origin/3786-location-wildcards
  origin/3953-group_sync_status
  origin/3953-group_sync_statusV2
  origin/3963-whodata-buffer
  origin/3982-githubaction-sca
  origin/4.6.0
  origin/4.7.0
  origin/4005-slack-options-test
  origin/4045-vdt-updated-package-still-vulnerable
  origin/4055-aws-asl-integration-tests
  origin/4159-migration-example
  origin/4159-refactor-callbacks-and-event-monitor
  origin/4179-logcollector-windows
  origin/4188-fix-openssl-errors
  origin/4282-update-framework-known-flaws
  origin/4290-changelog-tmp
  origin/5106-gcp-it-on-agents
  origin/HEAD -> origin/master
  origin/dependabot/pip/cryptography-39.0.1
  origin/fix/4330-changelog-from-4.5.0-to-4.6.0
  origin/framework-vulnerability-scan
  origin/master
  origin/master-merge-4.5
  origin/scripts_performance_footprint
  origin/wazuh-j
```
> * Add 'Force reconnect' feature to agent_simulator tool. ([#3111](https://github.com/wazuh/wazuh-qa/pull/3111)) - (Tools)
 - Issue on project 4.6.0 https://github.com/wazuh/wazuh-qa/issues/3093
- Commit available since 4.6.0
```
git branch -r --contains 83024e2ab873bd756339fb26f786cfbe3ec15b8e
  origin/16204_remove_group_column
  origin/17388-aws-services-discard-regex-its
  origin/2796-provisioning-tool-master
  origin/2993-one-agent-manager
  origin/3218-logcollector-refactor-test
  origin/3218-logcollector-refactor-test-aux
  origin/3269-multigroup-performance
  origin/3278-correct_merged_file_generation
  origin/3282-feed-content-cases-fix-master
  origin/3306-vulnerability-detector-refactor
  origin/3308-validate-content-retrieval-module
  origin/3309-vd-refactor-scan
  origin/3335-cloudtrail-integration-tests
  origin/3405-test-fim
  origin/3428-test-gcloud
  origin/3456-e2e-tests-vuln-detector
  origin/3470-engine-testing-module
  origin/3474-engine-input-tests
  origin/3491-vd-data-integrity
  origin/3492-portability-test-vd
  origin/3493-e2e-performance
  origin/3495-api-test-dev
  origin/3592-fim-audit-refactor
  origin/3709-shutdown_message
  origin/3709-shutdown_messagev2
  origin/3780-start-api-tests
  origin/3786-location-wildcards
  origin/3953-group_sync_status
  origin/3953-group_sync_statusV2
  origin/3963-whodata-buffer
  origin/3982-githubaction-sca
  origin/4.6.0
  origin/4.7.0
  origin/4005-slack-options-test
```
> * Add new module to support migration tool. ([#3837](https://github.com/wazuh/wazuh-qa/pull/3837))
 - Issue on project 4.6.0 https://github.com/wazuh/wazuh-qa/issues/3835
- Commit available since 4.6.0
```
git branch -r --contains 0ec80883154cd2d810855dcfb7898e5b278f272a
  origin/16204_remove_group_column
  origin/17388-aws-services-discard-regex-its
  origin/3278-correct_merged_file_generation
  origin/3709-shutdown_message
  origin/3709-shutdown_messagev2
  origin/3786-location-wildcards
  origin/3953-group_sync_status
  origin/3953-group_sync_statusV2
  origin/3963-whodata-buffer
  origin/3982-githubaction-sca
  origin/4.6.0
  origin/4.7.0
  origin/4005-slack-options-test
  origin/4045-vdt-updated-package-still-vulnerable
  origin/4055-aws-asl-integration-tests
  origin/4159-migration-example
  origin/4159-refactor-callbacks-and-event-monitor
  origin/4179-logcollector-windows
  origin/4188-fix-openssl-errors
  origin/4282-update-framework-known-flaws
  origin/4290-changelog-tmp
  origin/5106-gcp-it-on-agents
  origin/HEAD -> origin/master
  origin/fix/4330-changelog-from-4.5.0-to-4.6.0
  origin/framework-vulnerability-scan
  origin/master
  origin/master-merge-4.5
  origin/scripts_performance_footprint
  origin/wazuh-j
```

2023-07-20 16:28 UTC, Rebits approved these changes
LGTM

2023-07-21 14:49 UTC, rauldpm approved these changes

2023-07-21 14:51 UTC, merged