Security flaws check improvements
wazuh/wazuh-qa pull request #4393
Opened 2023-08-03 18:45 UTC by nico-stefani

|Related issue|
|-------------|
|   #4283  |

## Description

This PR closes #4283. Adds some fixes and improvements for the `test_python_flaws.py`.

I was not able to find the reason for the warnings because these are not present in the `tests_python_flaws.py` and neither is present the line number of the warning in the report. 
So I decided that we can continue using the `--disable-warnings` option since this is not a major issue.

### Updated

- Update readme replacing `branch` with `reference`.
- Fix the default value for the `reference` option.
- Fix the format value of directories to exclude default.

---

## Testing performed

```
(wqa310) ➜  wazuh-qa git:(4283-fix-security-flaws-check) ✗ pytest tests/scans/code_analysis/test_python_flaws.py
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.2.0
rootdir: /home/nstefani/git/wazuh-qa/tests, configfile: pytest.ini
plugins: html-3.1.1, metadata-3.0.0, testinfra-5.0.0
collected 1 item

tests/scans/code_analysis/test_python_flaws.py .                                                                                                                                                              [100%]

================================================================================================= warnings summary ==================================================================================================
scans/code_analysis/test_python_flaws.py::test_check_security_flaws
  invalid escape sequence '\w'

scans/code_analysis/test_python_flaws.py::test_check_security_flaws
  invalid escape sequence '\g'

scans/code_analysis/test_python_flaws.py::test_check_security_flaws
  invalid escape sequence '\d'

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================================== 1 passed, 3 warnings in 8.69s ===========================================================================================
```

2023-08-04 13:31 UTC, fdalmaup submitted a review, later dismissed
LGTM!

2023-08-18 10:34 UTC, Selutario requested changes

2023-08-18 10:34 UTC, Selutario commented on tests/scans/code_analysis/README.md
> +The test also updates the known_flaws files automatically. If we have a look to a known_flaws file, we will see that each flaw dictionary contains information like the line number or range. This info
```suggestion
The test also updates the known_flaws files automatically. If we have a look at a known_flaws file, we will see that each flaw dictionary contains information like the line number or range. This information is the one updated by the test. The test also removes flaws from the known_flaws file if they don't appear in the Bandit output.
```

2023-08-18 10:36 UTC, Selutario reviewed
Also, could you change the base branch to 4.5.2?

2023-08-18 19:53 UTC, nico-stefani commented
I close this and we continue in #4439

2023-08-18 19:53 UTC, closed without merging