Update login API calls request method
wazuh/wazuh-qa pull request #4492
Opened 2023-09-04 16:09 UTC by GGP1

|Related issue|
|-------------|
|     Closes https://github.com/wazuh/wazuh-qa/issues/4412        |

## Description

Changes the request method used to call the `/security/user/authenticate` endpoint to **POST**. The `GET` method not longer works since it has been deleted in the related issue.

### Updated

- tests/integration/test_api/test_config/test_logs/test_api_logs_formats.py
- tests/integration/test_api/test_config/test_request_timeout/test_request_timeout.py

### Tests

<details><summary>API IT tier 0,1</summary>

```console

```

</details>

2023-09-05 19:16 UTC, fdalmaup requested changes
LGTM, although the branch should point to the next upcoming patch version.

2023-09-05 20:30 UTC, fdalmaup submitted a review, later dismissed
LGTM

2023-09-15 08:55 UTC, Selutario requested changes
Changes LGTM, just fix the conflicts.

2023-09-18 14:10 UTC, Selutario approved these changes

2023-09-19 10:01 UTC, juliamagan approved these changes
LGTM

2023-09-19 10:06 UTC, merged