fix: Update the migration tool's system tests to match the new log file structure
wazuh/wazuh-qa pull request #4618
Opened 2023-10-12 11:56 UTC by kevin-mcm

|Related issue|
|-------------|
|  Closes #4616 |

## Description

This PR aims to update the `migration_tool`'s log file to align with the new log file structure

### Updated

- `MODULE_VARIABLE` from `migration.log` to `temp_configuration_file.log`
---

## Testing performed

### System tests work correctly

```shell
> python3 -m pytest -vvv tests/end_to_end/ --html=e2e-report.html --self-contained-html
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.15.0-86-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.3.0'}, 'Plugins': {'html': '3.1.1', 'testinfra': '5.0.0', 'metadata': '3.0.0'}}
rootdir: /home/server/intelligence-platform/qa, configfile: pytest.ini
plugins: html-3.1.1, testinfra-5.0.0, metadata-3.0.0
collected 22 items

tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py::test_invalid_inputs[EMPTY_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py PASSED                  [  4%]
tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py::test_invalid_inputs[NOT_SUPPORTED_FORMAT_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py PASSED   [  9%]
tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py::test_invalid_inputs[INVALID_JSON_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py PASSED           [ 13%]
tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py::test_invalid_inputs[INVALID_XML_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py PASSED            [ 18%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[ALAS1_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED                  [ 22%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[ALAS2_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED                  [ 27%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[ALAS2022_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED               [ 31%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[ALAS2023_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED               [ 36%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[ARCH_LINUX_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED             [ 40%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[DEBIAN_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED                 [ 45%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[NVD_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED                    [ 50%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[REDHAT_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED                 [ 54%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[SUSE_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED                   [ 59%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[ALMALINUX_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED              [ 63%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_complete_migration[CANONICAL_FEED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED              [ 68%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_insertion_and_update_delta[ARCH_VULNERABILITY_ADDED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED [ 72%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_insertion_and_update_delta[ARCH_VULNERABILITY_UPDATED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED [ 77%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_delta_schema[ARCH_DELTA_INSERT_SCHEMA_VALIDATION] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED [ 81%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_delta_schema[ARCH_DELTA_UPDATE_SCHEMA_VALIDATION] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED [ 86%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_delta_schema[ARCH_DELTA_DELETE_SCHEMA_VALIDATION] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED [ 90%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_elimination_delta[ARCH_VULNERABILITY_REMOVED] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED   [ 95%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py::test_skip_migration[SKIP_MIGRATION_PROCESS] <- ../../../../source/qa/tests/end_to_end/test_feed_ingestion/test_valid_inputs.py PASSED          [100%]

--------------------------------------------------------------- generated html file: file:///home/server/intelligence-platform/qa/e2e-report.html ---------------------------------------------------------------
======================================================================================== 22 passed in 112.52s (0:01:52) =========================================================================================
```

### System Tests Pipeline (Docker) works correctly

```shell
> python3 qa/system_tests_launcher.py
SYSTEM-TESTS-LAUNCHER: [INFO] Creating the output folder at: /tmp/system_tests_results
SYSTEM-TESTS-LAUNCHER: [INFO] Building Docker image.
SYSTEM-TESTS-LAUNCHER: [INFO] Docker image built successfully.
SYSTEM-TESTS-LAUNCHER: [INFO] Running container that contains the pipeline script to be executed.
SYSTEM-TESTS-LAUNCHER: [INFO] Parameters for the pipeline: --env dev
SYSTEM-TESTS-LAUNCHER: [INFO] Removing the build directory in order to build the system from scratch.
SYSTEM-TESTS-LAUNCHER: [INFO] The '/home/server/intelligence-platform/build' directory was removed.
->Step: SERVICES: Starting the services required by the tool.
->Step: SERVICES: Starting service -> mysql_migration_tool
->Step: SERVICES: The service mysql_migration_tool is running correctly.
->Step: BUILD: The build process began.
->Step: BUILD: The `build` folder has been created successfully.
->Step: BUILD: The tool has been compiled successfully.
->Step: BUILD: The executables and libraries have been built successfully.
->Step: INSTALLATION: Installing the built tool.
->Step: INSTALLATION: The tool was installed successfully.
->Step: TESTS: Running tests.
->Step: TESTS: The tests have passed. Results: 22 passed in 145.08s (0:02:25)
SYSTEM-TESTS-LAUNCHER: [INFO] Pipeline execution finished. Results in: /tmp/system_tests_results
SYSTEM-TESTS-LAUNCHER: [INFO] Removing container.
SYSTEM-TESTS-LAUNCHER: [INFO] The Docker container called `intelligence-system-tests` was removed.
```

2023-10-12 13:54 UTC, tsarquis88 requested changes

2023-10-12 13:54 UTC, tsarquis88 commented on CHANGELOG.md
> +- Update the migration tool's system tests to match the new log file structure([#4618](https://github.com/wazuh/wazuh-qa/pull/4618)) \- (Tests)
Missing space
```suggestion
- Update the migration tool's system tests to match the new log file structure ([#4618](https://github.com/wazuh/wazuh-qa/pull/4618)) \- (Tests)
```

2023-10-12 16:02 UTC, sebasfalcone approved these changes
LGTM!

2023-10-12 16:08 UTC, tsarquis88 approved these changes

2023-10-17 16:18 UTC, jftuduri approved these changes

2023-10-17 19:50 UTC, Damian-Mangold approved these changes
LGTM !

## Before
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /source/qa, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.0.0, html-3.1.1
collected 22 items

tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/main.py", line 347, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 111, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 130, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 221, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 130, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "/source/qa/tests/end_to_end/conftest.py", line 87, in pytest_runtest_makereport
INTERNALERROR>     with open(file_path, mode='r') as file:
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/var/wazuh/output/logs/migration.log'

============================ no tests ran in 3.08s =============================

```

## After
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /source/qa, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.0.0, html-3.1.1
collected 22 items

tests/end_to_end/test_feed_ingestion/test_invalid_inputs.py ....         [ 18%]
tests/end_to_end/test_feed_ingestion/test_valid_inputs.py .............. [ 81%]
....                                                                     [100%]

--------- generated html file: file:///output/system_tests_report.html ---------
======================== 22 passed in 104.91s (0:01:44) ========================

```

2023-10-17 22:16 UTC, merged