Fix test_file_checker in check_mtime case
wazuh/wazuh-qa pull request #4873
Opened 2024-01-18 15:16 UTC by jotacarma90

…a false negative

|Related issue|
|-------------|
|https://github.com/wazuh/wazuh-qa/issues/4839|

## Description

This PR is to fix some false negative cases that were coming up in the test_file_checkers.

This test configures a Wazuh directory with check_all=no and check_mtime=yes so only the timestamp will be taken into account to see if there have been changes in the file. And if it coincides that the added and the modified happen in the same second (same timestamp), the modification event is not detected and that's why the test fails. Damn xDDDD

To solve it I have included a wait of one second after the creation of the file for the case of the check_mtime. This way we make sure that the timestamp of the event is different and we get correctly the alert.

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @user (Developer)  |           | ⚫⚫⚫ | ⚫⚫⚫ |         |         | Nothing to highlight |
| @user (Reviewer)   |           | ⚫⚫⚫ | :no_entry_sign: :no_entry_sign: :no_entry_sign:  |        |         | Nothing to highlight |

2024-01-19 13:12 UTC, juliamagan requested changes

2024-01-19 13:12 UTC, juliamagan commented on tests/integration/test_fim/test_files/test_file_checks/test_file_checkers.py
Why not simply add a sleep inside the function that modifies the files?

2024-01-19 16:40 UTC, juliamagan approved these changes
The `regular_file_cud` function does too many things, it is practically the whole test. The best solution would be to refactor this function to be able to split the different tasks, but this would affect most of the FIM tests, and knowing that these tests will be deprecated in the future and worked on by the core team to implement them in GitHub Actions, we can accept this solution.

2024-01-22 12:15 UTC, lchico commented on tests/integration/test_fim/test_files/test_file_checks/test_file_checkers.py
> +        regular_file_cud(file_path, wazuh_log_monitor, min_timeout=global_parameters.default_timeout,
Could you please add a comment explaining briefly why we are doing this?

2024-01-22 12:18 UTC, lchico requested changes
I left a comment, It would be helpful to have a comment in the code explaining why we are doing this.

2024-01-22 12:34 UTC, lchico submitted a review, later dismissed
LGTM!

2024-01-22 14:04 UTC, lchico approved these changes
LGTM

2024-01-24 15:20 UTC, MarcelKemp approved these changes

2024-01-24 15:49 UTC, juliamagan approved these changes

2024-01-24 15:53 UTC, merged