Fix typo in the comment.
wazuh/wazuh-qa pull request #4896
Opened 2024-01-31 18:03 UTC by damarisg

# Description

Change verions to versions. 

---

2024-02-01 17:31 UTC, QU3B1M submitted a review, later dismissed
LGTM!

2024-02-02 08:38 UTC, davidjiglesias requested changes

2024-02-02 08:38 UTC, davidjiglesias commented on tests/system/provisioning/manager_agent/vars/configurations.yml
> +agent1_user: "ossec" #Only valid for agents versions<4.2.5
```suggestion
agent1_user: "ossec" #Only valid for agents version<4.2.5
```

2024-02-02 08:38 UTC, davidjiglesias commented on tests/system/provisioning/manager_agent/vars/configurations.yml
> +agent3_user: "root" #Only valid for agents versions=>4.2.5
```suggestion
agent3_user: "root" #Only valid for agents version=>4.2.5
```

2024-02-02 14:46 UTC, damarisg commented on tests/system/provisioning/manager_agent/vars/configurations.yml
> +agent3_user: "root" #Only valid for agents versions=>4.2.5
Applied on https://github.com/wazuh/wazuh-qa/pull/4896/commits/47318b62d529af075bbbf52e63648cc6199aec62

2024-02-05 08:18 UTC, merged