Adding workflow as library function
wazuh/wazuh-qa pull request #4918
Opened 2024-02-06 19:08 UTC by pro-akim

# Description

Adding setup file and changing directories in order to create Workflow as a library option

---

## Testing performed

```
(workflow_test) akim@akim-PC:~/Desktop/venvs$ pip3 list
Package    Version
---------- -------
pip        22.0.2
setuptools 59.6.0

(workflow_test) akim@akim-PC:~/Desktop/wazuh-qa/deployability/deps$ pip3 install .
Processing /home/akim/Desktop/wazuh-qa/deployability/deps
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for workflow, since package 'wheel' is not installed.
Installing collected packages: workflow
  Running setup.py install for workflow ... done
Successfully installed workflow-1.0

(testing_wf) akim@akim-PC:~/Desktop/wazuh-qa/deployability/deps$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from workflow_engine import schema_validator
>>> from workflow_engine import task
>>> from workflow_engine import utils
>>> from workflow_engine import workflow_processor

(workflow_test) akim@akim-PC:~/Desktop/wazuh-qa/deployability$ tree /home/akim/Desktop/venvs/workflow_test/lib/python3.10/site-packages/workflow
/home/akim/Desktop/venvs/workflow_test/lib/python3.10/site-packages/workflow
├── examples
│   ├── dtt1-agents-poc.yaml
│   ├── dtt1-agents.yaml
│   └── dtt1-managers.yaml
├── __init__.py
├── models.py
├── __pycache__
│   ├── __init__.cpython-310.pyc
│   ├── models.cpython-310.pyc
│   ├── schema_validator.cpython-310.pyc
│   ├── task.cpython-310.pyc
│   ├── utils.cpython-310.pyc
│   └── workflow_processor.cpython-310.pyc
├── README.md
├── schemas
│   └── schema_v1.json
├── schema_validator.py
├── task.py
├── utils.py
└── workflow_processor.py

3 directories, 17 files
```

Path of playbooks were added inside of each module and relative path were fixed.

2024-02-06 19:17 UTC, fcaffieri requested changes
We need to remove the deployability/deps/build files and the deployability/deps/workflow.egg-info

2024-02-07 12:11 UTC, QU3B1M requested changes

2024-02-07 12:12 UTC, QU3B1M commented
I think the tests shouldn't be included in the installable, but the test `playbooks` and `Tester` class should. Maybe what's inside the subdir `test/` could be moved outside, so the modules is the library code and the tests are something else apart. With this approach we must update the `test.yaml `to accept a full path of the tests, this way, the Tester module could run any test suite. I dont know if what I'm saying makes sense to you @fcaffieri @pro-akim

2024-02-07 12:33 UTC, pro-akim commented
## Update
To do https://github.com/wazuh/wazuh-qa/pull/4918#discussion_r1481373797, more directories should be changed.
I will discuss those points to make sure what will be the new final structure.

2024-02-07 13:43 UTC, pro-akim commented
## Update
Directory changes done for launchers in https://github.com/wazuh/wazuh-qa/pull/4918/commits/d0338b5a3dc364c76a68fac46587eabf0e5c5457

Tests structure will be worked in a future issue.

2024-02-07 17:27 UTC, pro-akim commented
## Update
This issue will be closed and the work will continue in https://github.com/wazuh/wazuh-qa/pull/4918

2024-02-07 17:27 UTC, closed without merging