Enhancement/4940 dtt1 provision multiple dependencies inventories
wazuh/wazuh-qa pull request #4946
Opened 2024-02-08 19:15 UTC by QU3B1M

# Description

TODO

---

## Testing performed

TODO

2024-02-19 11:46 UTC, pro-akim requested changes
## Review Notes
Small changes requested

2024-02-21 12:10 UTC, pro-akim approved these changes
## Review Notes
Some conflicts are present.

2024-02-21 12:32 UTC, pro-akim commented
## Review Notes

LGTM, conflicts were solved.

2024-02-21 12:51 UTC, fcaffieri approved these changes

2024-02-21 12:52 UTC, merged