Fix data visualization script graphics generation
wazuh/wazuh-qa pull request #5021
Opened 2024-02-23 16:06 UTC by GGP1

# Description

Fixes some errors from the data visualization script during the cluster, analysisd and remoted statistics graphics generation.

## Testing performed

| Validation | Jenkins | Local  | OS  | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|
|     Graphs are generated      | ⚫⚫ | [executions](https://github.com/wazuh/wazuh-qa/issues/4975#issuecomment-1961589067) |    Pop_OS     |         | Nothing to highlight |

2024-02-28 15:32 UTC, nico-stefani approved these changes
LGTM

2024-02-29 10:56 UTC, Selutario requested changes
Looks good! Just an additional request: please, add a [changelog](https://github.com/wazuh/wazuh-qa/blob/fix/4975-data-visualization-script/CHANGELOG.md) entry for these changes.

Edit: it seems two minor changes are also needed for the linter check to pass:
- https://github.com/wazuh/wazuh-qa/actions/runs/8021908993/job/21915066467?pr=5021

2024-02-29 12:34 UTC, Selutario submitted a review, later dismissed

2024-02-29 18:16 UTC, rauldpm approved these changes

2024-02-29 18:45 UTC, rauldpm requested changes
Please add a CI build

2024-03-07 15:30 UTC, rauldpm approved these changes

2024-03-07 15:33 UTC, merged