Fix test_group_sync_status system test
wazuh/wazuh-qa pull request #5134
Opened 2024-03-21 12:46 UTC by Rebits

# Description

This PR fixes `test_group_sync_status` system test

---

## Testing performed

| Validation | Jenkins | Local  | OS  | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|
|           | ⚫⚫ | ⚫⚫ |         |         | Nothing to highlight |

2024-03-22 09:11 UTC, rafabailon submitted a review, later dismissed
LGTM

2024-03-22 16:22 UTC, juliamagan requested changes
GJ, but the changelog entry is missing. In addition, we need to test this environment on different instance types until the results are stable.

2024-04-04 06:22 UTC, juliamagan approved these changes

2024-04-04 07:15 UTC, davidjiglesias approved these changes

2024-04-04 07:15 UTC, merged