Improvements in error handling and some validations
wazuh/wazuh-qa pull request #5138
Opened 2024-03-21 18:32 UTC by c-bordon

Close https://github.com/wazuh/wazuh-qa/issues/4901

This PR seeks to improve error handling and some validations carried out on the tags applied to the AWS instances.

At the same time, some name definitions are corrected in the construction of the instance and the private keys used to access them, a random number is added to avoid coincidence in the keys and duplication.

The possibility of overwriting private keys is eliminated as this can be somewhat risky.

Tests:

replaced exit(1) to raise: https://github.com/wazuh/wazuh-qa/issues/4901#issuecomment-2013147356

Improving the error message when selecting an unavailable machine: https://github.com/wazuh/wazuh-qa/issues/4901#issuecomment-2013149707

Removing issue label as mandatory and improving ssh key naming: https://github.com/wazuh/wazuh-qa/issues/4901#issuecomment-2013158145

Termination date options: https://github.com/wazuh/wazuh-qa/issues/4901#issuecomment-2013233824

2024-03-21 19:21 UTC, QU3B1M approved these changes
LGTM!

2024-03-21 21:10 UTC, fcaffieri requested changes

2024-03-21 21:10 UTC, fcaffieri commented on deployability/modules/allocation/generic/provider.py
> +                    return size_list[size]
We could incorporate a raise if the size is not found, just as it is in _get_os_specs

2024-03-22 12:30 UTC, fcaffieri commented on deployability/modules/allocation/generic/provider.py
> +                    return size_list[size]
This was validated in models.py
```
class InputPayload(BaseModel):
    size: Literal['micro', 'small', 'medium', 'large', None] = None
```

2024-03-22 12:30 UTC, fcaffieri approved these changes

2024-03-25 12:19 UTC, teddytpc1 approved these changes

2024-03-25 12:22 UTC, merged