Add `alert.json` to VD E2E test report
wazuh/wazuh-qa pull request #5147
Opened 2024-03-25 15:43 UTC by MARCOSD4

# Description

This PR aims to add the `alert.json` file to Vulnerability Detection E2E test report as well as the ossec.log and the test logs are attached. This will be useful since when the test indicates that the alert has not been found, we will be able to check if the alert has been triggered or not. For this purpose, a new function has been added to obtain the alerts from the `alert.json` file of the managers and the function in charge of collecting this information has been modified.

## Testing performed

2024-04-01 12:52 UTC, juliamagan requested changes
GJ, but remember to add the changelog entry.

2024-04-01 13:50 UTC, MARCOSD4 commented
Changelog updated in https://github.com/wazuh/wazuh-qa/pull/5147/commits/ec40e06cff5179c20008d5ccb5afd4dc0b3fcb8a

2024-04-01 14:22 UTC, MARCOSD4 commented
Changelog updated in https://github.com/wazuh/wazuh-qa/pull/5147/commits/380a64151ef8257f01f59c04df9fb3121f9d01ad

2024-04-02 07:44 UTC, MARCOSD4 commented on deps/wazuh_testing/wazuh_testing/end_to_end/logs.py
> +      Default is 'all'.
Fixed in https://github.com/wazuh/wazuh-qa/pull/5147/commits/99be98778053d80f263205bc05e9fb9fe46b0ccc

2024-04-02 07:44 UTC, MARCOSD4 commented on deps/wazuh_testing/wazuh_testing/end_to_end/logs.py
> +def get_hosts_alerts(host_manager: HostManager, host_group: str = 'all') -> Dict[str, str]:
Fixed in https://github.com/wazuh/wazuh-qa/pull/5147/commits/99be98778053d80f263205bc05e9fb9fe46b0ccc

2024-04-02 07:44 UTC, MARCOSD4 commented on deps/wazuh_testing/wazuh_testing/end_to_end/logs.py
> +      Default is 'all'.
Fixed in https://github.com/wazuh/wazuh-qa/pull/5147/commits/99be98778053d80f263205bc05e9fb9fe46b0ccc

2024-04-02 07:44 UTC, MARCOSD4 commented on tests/end_to_end/test_vulnerability_detector/conftest.py
> +        if host.startswith("manager"):
Fixed in https://github.com/wazuh/wazuh-qa/pull/5147/commits/99be98778053d80f263205bc05e9fb9fe46b0ccc

2024-04-03 07:51 UTC, juliamagan approved these changes

2024-04-04 07:42 UTC, Rebits approved these changes
LGTM

2024-04-04 07:45 UTC, merged