Filter alerts and logs by timestamp
wazuh/wazuh-qa pull request #5157
Opened 2024-03-27 10:09 UTC by juliamagan

# Description

---

## Testing performed

|OS|Package used|
|--|--|
|||

| Validation | Jenkins | Local  | OS  | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|
|           | ⚫⚫ | ⚫⚫ |         |         | Nothing to highlight |

2024-04-03 09:49 UTC, rafabailon approved these changes
LGTM

2024-04-04 13:48 UTC, Rebits requested changes
Great job! Some minor changes are requested

2024-04-04 13:48 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/end_to_end/remote_operations_handler.py
> +                current_datetime = datetime.now(timezone.utc).isoformat()[:-6]
Add a comment about why `[:-6]`

2024-04-04 15:18 UTC, juliamagan commented on deps/wazuh_testing/wazuh_testing/end_to_end/remote_operations_handler.py
> +                current_datetime = datetime.now(timezone.utc).isoformat()[:-6]
Done in c0e9601

2024-04-05 08:35 UTC, Rebits commented on deps/wazuh_testing/wazuh_testing/end_to_end/remote_operations_handler.py
> +                current_datetime = datetime.now(timezone.utc).isoformat()[:-6]
LGTM

2024-04-05 08:57 UTC, merged