Merge Test module into DTT1
wazuh/wazuh-qa pull request #5165
Opened 2024-03-27 20:14 UTC by QU3B1M

# Description

This PR applies all the different changes made in the test module to the main Epic branch.

2024-03-27 21:49 UTC, fcaffieri approved these changes

2024-04-01 10:40 UTC, pro-akim commented
## Update
 
Test PART I
- linux-ubuntu-20.04-amd64
- linux-ubuntu-22.04-amd64
- linux-oracle-9-amd64
- linux-amazon-2-amd64


MANAGER :green_circle:

```bash
 python3  modules/testing/main.py --wazuh-revision '40714' --wazuh-version '4.7.3' --component 'manager' --tests 'install,restart,stop,uninstall' --targets '{"wazuh-1":"/tmp/dtt1-poc/manager-linux-ubuntu-20.04-amd64/inventory.yml"}' --targets '{"wazuh-2":"/tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/inventory.yml"}' --targets '{"wazuh-3":"/tmp/dtt1-poc/manager-linux-oracle-9-amd64/inventory.yml"}' --targets '{"wazuh-4":"/tmp/dtt1-poc/manager-linux-amazon-2-amd64/inventory.yml"}' --live 'True'
```



<details><summary>AWS :green_circle:</summary>
[2024-04-01 11:52:02,400] [INFO] [Testing]: No Firewall to disable on ubuntu-20.04
[2024-04-01 11:52:04,977] [INFO] [Testing]: No Firewall to disable on ubuntu-22.04
[2024-04-01 11:52:05,115] [INFO] [Testing]: No Firewall to disable on oracle-9
[2024-04-01 11:52:07,822] [INFO] [Testing]: No Firewall to disable on amazon-2
[2024-04-01 11:53:17,353] [INFO] [Testing]: File permissions modified to be handled
[2024-04-01 11:53:22,682] [INFO] [Testing]: File copied from ubuntu-20.04 (44.204.20.36) to /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers/wazuh-install-files.tar
[2024-04-01 11:53:25,652] [INFO] [Testing]: Sending file from /home/ubuntu/wazuh-install-files.tar to ubuntu-22.04 (44.211.225.194)
[2024-04-01 11:53:29,944] [INFO] [Testing]: File permissions were restablished
[2024-04-01 11:53:29,945] [INFO] [Testing]: The file wazuh-install-files.tar deleted in /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers
[2024-04-01 11:53:38,447] [INFO] [Testing]: File permissions modified to be handled
[2024-04-01 11:53:43,917] [INFO] [Testing]: File copied from ubuntu-20.04 (44.204.20.36) to /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers/wazuh-install-files.tar
[2024-04-01 11:53:46,846] [INFO] [Testing]: Sending file from /home/ubuntu/wazuh-install-files.tar to oracle-9 (18.207.187.21)
[2024-04-01 11:53:51,452] [INFO] [Testing]: File permissions were restablished
[2024-04-01 11:53:51,454] [INFO] [Testing]: The file wazuh-install-files.tar deleted in /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers
[2024-04-01 11:54:00,281] [INFO] [Testing]: File permissions modified to be handled
[2024-04-01 11:54:05,689] [INFO] [Testing]: File copied from ubuntu-20.04 (44.204.20.36) to /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers/wazuh-install-files.tar
[2024-04-01 11:54:08,763] [INFO] [Testing]: Sending file from /home/ubuntu/wazuh-install-files.tar to amazon-2 (3.93.152.205)
[2024-04-01 11:54:13,573] [INFO] [Testing]: File permissions were restablished
[2024-04-01 11:54:13,574] [INFO] [Testing]: The file wazuh-install-files.tar deleted in /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers
[2024-04-01 11:54:18,180] [INFO] [Testing]: Generating Snapshot for Checkfile in ubuntu-20.04
[2024-04-01 11:54:30,475] [INFO] [Testing]: Installing Manager in ubuntu-20.04
[2024-04-01 11:55:48,190] [INFO] [Testing]: Generating Snapshot for Checkfile in ubuntu-20.04
[2024-04-01 11:55:59,255] [INFO] [Testing]: Applying filters in checkfiles in ubuntu-20.04
[2024-04-01 11:55:59,256] [INFO] [Testing]: Pre and post install checkfile comparison in ubuntu-20.04: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 11:56:01,316] [INFO] [Testing]: Generating Snapshot for Checkfile in ubuntu-22.04
[2024-04-01 11:56:13,793] [INFO] [Testing]: Installing Manager in ubuntu-22.04
[2024-04-01 11:57:34,690] [INFO] [Testing]: Generating Snapshot for Checkfile in ubuntu-22.04
[2024-04-01 11:57:45,829] [INFO] [Testing]: Applying filters in checkfiles in ubuntu-22.04
[2024-04-01 11:57:45,830] [INFO] [Testing]: Pre and post install checkfile comparison in ubuntu-22.04: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 11:57:48,208] [INFO] [Testing]: Generating Snapshot for Checkfile in oracle-9
[2024-04-01 11:58:00,066] [INFO] [Testing]: Installing Manager in oracle-9
[2024-04-01 11:59:11,253] [INFO] [Testing]: Generating Snapshot for Checkfile in oracle-9
[2024-04-01 11:59:21,047] [INFO] [Testing]: Applying filters in checkfiles in oracle-9
[2024-04-01 11:59:21,048] [INFO] [Testing]: Pre and post install checkfile comparison in oracle-9: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 11:59:23,542] [INFO] [Testing]: Generating Snapshot for Checkfile in amazon-2
[2024-04-01 11:59:34,708] [INFO] [Testing]: Installing Manager in amazon-2
[2024-04-01 12:00:26,929] [INFO] [Testing]: Generating Snapshot for Checkfile in amazon-2
[2024-04-01 12:00:36,386] [INFO] [Testing]: Applying filters in checkfiles in amazon-2
[2024-04-01 12:00:36,387] [INFO] [Testing]: Pre and post install checkfile comparison in amazon-2: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 12:00:36,387] [INFO] [Testing]: Getting status of ubuntu-20.04
[2024-04-01 12:00:41,162] [INFO] [Testing]: Getting status of ubuntu-22.04
[2024-04-01 12:00:45,771] [INFO] [Testing]: Getting status of oracle-9
[2024-04-01 12:00:50,316] [INFO] [Testing]: Getting status of amazon-2
[2024-04-01 12:01:28,070] [INFO] [Testing]: Cluster configured in: ubuntu-20.04
[2024-04-01 12:02:00,626] [INFO] [Testing]: Cluster configured in: ubuntu-22.04
[2024-04-01 12:02:29,608] [INFO] [Testing]: Cluster configured in: oracle-9
[2024-04-01 12:02:59,509] [INFO] [Testing]: Cluster configured in: amazon-2
[2024-04-01 12:03:02,176] [INFO] [Testing]: Getting status of ubuntu-20.04
[2024-04-01 12:03:04,423] [INFO] [Testing]: Getting status of ubuntu-22.04
[2024-04-01 12:03:06,675] [INFO] [Testing]: Getting status of oracle-9
[2024-04-01 12:03:09,031] [INFO] [Testing]: Getting status of amazon-2
[2024-04-01 12:05:00,985] [INFO] [Testing]: Restarting wazuh-manager in ubuntu-22.04
[2024-04-01 12:05:20,003] [INFO] [Testing]: Restarting wazuh-manager in oracle-9
[2024-04-01 12:05:34,745] [INFO] [Testing]: Restarting wazuh-manager in amazon-2
[2024-04-01 12:05:51,029] [INFO] [Testing]: Getting status of ubuntu-20.04
[2024-04-01 12:05:53,385] [INFO] [Testing]: Getting status of ubuntu-22.04
[2024-04-01 12:05:55,535] [INFO] [Testing]: Getting status of oracle-9
[2024-04-01 12:05:57,832] [INFO] [Testing]: Getting status of amazon-2
[2024-04-01 12:06:06,314] [INFO] [Testing]: Stopping wazuh-manager in ubuntu-22.04
[2024-04-01 12:06:11,715] [INFO] [Testing]: Stopping wazuh-manager in oracle-9
[2024-04-01 12:06:16,733] [INFO] [Testing]: Stopping wazuh-manager in amazon-2
[2024-04-01 12:06:22,673] [INFO] [Testing]: Getting status of ubuntu-20.04
[2024-04-01 12:06:24,890] [INFO] [Testing]: Getting status of amazon-2
[2024-04-01 12:06:27,177] [INFO] [Testing]: Getting status of amazon-2
[2024-04-01 12:06:29,532] [INFO] [Testing]: Getting status of amazon-2
[2024-04-01 12:06:31,787] [INFO] [Testing]: Restarting wazuh-manager in ubuntu-22.04
[2024-04-01 12:06:47,555] [INFO] [Testing]: Restarting wazuh-manager in oracle-9
[2024-04-01 12:06:59,331] [INFO] [Testing]: Restarting wazuh-manager in amazon-2
[2024-04-01 12:07:19,405] [INFO] [Testing]: Getting status of ubuntu-20.04
[2024-04-01 12:07:21,656] [INFO] [Testing]:  [...]

2024-04-01 12:18 UTC, pro-akim commented
## Update

Test PART II 

- linux-redhat-7-amd64
- linux-redhat-8-amd64
- linux-redhat-9-amd64
- linux-centos-7-amd64


MANAGER :green_circle: 

```bash
 python3  modules/testing/main.py --wazuh-revision '40714' --wazuh-version '4.7.3' --component 'manager' --tests 'install,restart,stop,uninstall' --targets '{"wazuh-1":"/tmp/dtt1-poc/manager-linux-redhat-7-amd64/inventory.yml"}' --targets '{"wazuh-2":"/tmp/dtt1-poc/manager-linux-redhat-8-amd64/inventory.yml"}' --targets '{"wazuh-3":"/tmp/dtt1-poc/manager-linux-redhat-9-amd64/inventory.yml"}' --targets '{"wazuh-4":"/tmp/dtt1-poc/manager-linux-centos-7-amd64/inventory.yml"}' --live 'True'
```



<details><summary>AWS :green_circle: </summary>


```bash
[2024-04-01 14:05:18,889] [INFO] [Testing]: No Firewall to disable on redhat-7
[2024-04-01 14:05:21,140] [INFO] [Testing]: No Firewall to disable on redhat-8
[2024-04-01 14:05:23,495] [INFO] [Testing]: No Firewall to disable on redhat-9
[2024-04-01 14:05:25,850] [INFO] [Testing]: No Firewall to disable on centos-7
[2024-04-01 14:06:04,154] [INFO] [Testing]: Installing Manager in redhat-7
[2024-04-01 14:07:18,898] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-8
[2024-04-01 14:07:43,771] [INFO] [Testing]: Installing Agent in redhat-8
[2024-04-01 14:08:29,762] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-8
[2024-04-01 14:08:38,061] [INFO] [Testing]: Applying filters in checkfiles in redhat-8
[2024-04-01 14:08:38,061] [INFO] [Testing]: Pre and post install checkfile comparison in redhat-8: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 14:08:40,348] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-9
[2024-04-01 14:08:57,103] [INFO] [Testing]: Installing Agent in redhat-9
[2024-04-01 14:09:24,891] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-9
[2024-04-01 14:09:34,752] [INFO] [Testing]: Applying filters in checkfiles in redhat-9
[2024-04-01 14:09:34,874] [INFO] [Testing]: Pre and post install checkfile comparison in redhat-9: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 14:09:37,244] [INFO] [Testing]: Generating Snapshot for Checkfile in centos-7
[2024-04-01 14:09:54,140] [INFO] [Testing]: Installing Agent in centos-7
[2024-04-01 14:10:21,685] [INFO] [Testing]: Generating Snapshot for Checkfile in centos-7
[2024-04-01 14:10:31,315] [INFO] [Testing]: Applying filters in checkfiles in centos-7
[2024-04-01 14:10:31,316] [INFO] [Testing]: Pre and post install checkfile comparison in centos-7: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 14:10:37,461] [INFO] [Testing]: Getting status of redhat-8
[2024-04-01 14:10:39,264] [INFO] [Testing]: Getting status of redhat-9
[2024-04-01 14:10:41,552] [INFO] [Testing]: Getting status of centos-7
[2024-04-01 14:11:37,676] [INFO] [Testing]: Getting status of redhat-8
[2024-04-01 14:11:40,024] [INFO] [Testing]: Getting status of redhat-9
[2024-04-01 14:11:42,380] [INFO] [Testing]: Getting status of centos-7
[2024-04-01 14:12:31,080] [INFO] [Testing]: Restarting wazuh-agent in redhat-8
[2024-04-01 14:12:38,700] [INFO] [Testing]: Restarting wazuh-agent in redhat-9
[2024-04-01 14:12:47,097] [INFO] [Testing]: Restarting wazuh-agent in centos-7
[2024-04-01 14:12:56,828] [INFO] [Testing]: Getting status of redhat-8
[2024-04-01 14:12:58,513] [INFO] [Testing]: Getting status of redhat-9
[2024-04-01 14:13:00,870] [INFO] [Testing]: Getting status of centos-7
[2024-04-01 14:13:37,376] [INFO] [Testing]: Stopping wazuh-agent in redhat-8
[2024-04-01 14:13:40,449] [INFO] [Testing]: Stopping wazuh-agent in redhat-9
[2024-04-01 14:13:43,417] [INFO] [Testing]: Stopping wazuh-agent in centos-7
[2024-04-01 14:13:46,694] [INFO] [Testing]: Getting status of redhat-8
[2024-04-01 14:13:51,606] [INFO] [Testing]: Getting status of redhat-9
[2024-04-01 14:13:56,731] [INFO] [Testing]: Getting status of centos-7
[2024-04-01 14:14:01,852] [INFO] [Testing]: Restarting wazuh-agent in redhat-8
[2024-04-01 14:14:08,198] [INFO] [Testing]: Restarting wazuh-agent in redhat-9
[2024-04-01 14:14:15,378] [INFO] [Testing]: Restarting wazuh-agent in centos-7
[2024-04-01 14:14:45,779] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-8
[2024-04-01 14:14:55,568] [INFO] [Testing]: Uninstalling Agent in redhat-8
[2024-04-01 14:15:24,396] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-8
[2024-04-01 14:15:32,600] [INFO] [Testing]: Applying filters in checkfiles in redhat-8
[2024-04-01 14:15:32,601] [INFO] [Testing]: Pre and post uninstall checkfile comparison in redhat-8: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 14:15:34,828] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-9
[2024-04-01 14:15:46,400] [INFO] [Testing]: Uninstalling Agent in redhat-9
[2024-04-01 14:16:03,437] [INFO] [Testing]: Generating Snapshot for Checkfile in redhat-9
[2024-04-01 14:16:12,833] [INFO] [Testing]: Applying filters in checkfiles in redhat-9
[2024-04-01 14:16:12,833] [INFO] [Testing]: Pre and post uninstall checkfile comparison in redhat-9: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}
[2024-04-01 14:16:14,765] [INFO] [Testing]: Generating Snapshot for Checkfile in centos-7
[2024-04-01 14:16:26,951] [INFO] [Testing]: Uninstalling Agent in centos-7
[2024-04-01 14:16:48,247] [INFO] [Testing]: Generating Snapshot for Checkfile in centos-7
[2024-04-01 14:16:58,119] [INFO] [Testing]: Applying filters in checkfiles in centos-7
[2024-04-01 14:16:58,119] [INFO] [Testing]: Pre and post uninstall checkfile comparison in centos-7: {'/boot': {'added': [], 'removed': [], 'modified': []}, '/usr/bin': {'added': [], 'removed': [], 'modified': []}, '/root': {'added': [], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}


```
</details>


<details><summary>VAGRANT :green_circle: </summary>

```bash

[2024-04-01 12:47:21,603] [INFO] [Testing]: Firewall disabled on redhat-7
[2024-04-01 12:47:25,348] [INFO] [Testing]: Firewall disabled on redhat-8
[2024-04-01 12:47:27,142] [INFO] [Testing]: Firewall disabled on redhat-9
[2024-04-01 12:47:27,636] [INFO] [Testing]: No Firewall to disable on centos-7
[2024-04-01 12:47:50,706] [INFO] [Testing]: File permissions modified to be handled
[2024-04-01 12:47:51,907] [INFO] [Testing]: File copied from redhat-7 (192.168.57.2) to /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers/wazuh-install-files.tar
[2024-04-01 12:47:52,232] [INFO] [Testing]: Sending file from /home/vagrant/wazuh-install-files.tar to redhat-8 (192.168.57.3)
[2024-04-01 12:47:53,299] [INFO] [Testing]: File permissions were restablished
[2024-04-01 12:47:53,300] [INFO] [Testing]: The file wazuh-install-files.tar deleted in /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers
[2024-04-01 12:47:55,754] [INFO] [Testing]: File permissions modified to be handled
[2024-04-01 12:47:56,720] [INFO] [Testing]: File copied from redhat-7 (192.168.57.2) to /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/helpers/wazuh-install-files.tar
[2024-04-01 12:47:57,060] [INFO] [Testing]:  [...]

2024-04-01 13:06 UTC, rauldpm approved these changes

2024-04-01 13:11 UTC, rauldpm requested changes
Approved but this PR needs changes from https://github.com/wazuh/wazuh-qa/pull/5005

2024-04-01 17:11 UTC, rauldpm approved these changes

2024-04-01 17:11 UTC, merged