Add OS Info when Simulating Packages
wazuh/wazuh-qa pull request #5224
Opened 2024-04-16 08:39 UTC by rafabailon

# Description

When using `simulate-agents` to generate Syscollector packages, you have to also send the OS info. If it is not sent, vulnerabilities are not generated and errors such as

```console
wazuh-modulesd:vulnerability-scanner: WARNING: Discarded event: Empty response from Wazuh-DB
```

To avoid this, when package events (and only packages) are generated, an osinfo event is also added to send the necessary OS information.

## Testing Performed

| OS | Package Used | Version | Result |
| --- | --- | --- | --- |
| Ubuntu 22.04 | Manager | 4.8.0 | :black_circle: |

The tests have been passed locally. To test the changes you have to use the `simulate-agents` with the following command `simulate-agents -a XXX.XX.X.XX -n 1 -m syscollector -w 20 -s 10 -t 60 -o debian10 -v 4.8.0 --debug` and check that no errors appear and all expected messages are generated.

2024-04-16 09:57 UTC, rafabailon commented
## Test

<details>
  <summary>Agent Simulator 🟢 </summary>
  <br/>

```console
root@ubuntu2204:/home/vagrant# simulate-agents -a 172.16.1.13 -n 1 -m syscollector -s 5 -t 12 -o debian10 -v 4.8.0  --debug
DEBUG:root:Registration - 1-bpcFltYPL7Ud8wR0-debian10(021) in 172.16.1.13
DEBUG:root:Keep alive message = #!-Linux |agent-debian10 |4.9.0-12-amd64 |#1 SMP Debian 4.9.210-1 (2020-01-20) |x86_64 [Debian GNU/Linux|debian: 10 (buster)] - Wazuh v4.8.0 / ab73af41699f13fdd81903b5f23d8d00
d6e3ac3e75ca0319af3e7c262776f331 merged.mg
#"_agent_ip":10.0.2.15

INFO:P8185:{'keepalive': {'status': 'enabled', 'frequency': 10.0}, 'fim': {'status': 'disabled', 'eps': 0}, 'fim_integrity': {'status': 'disabled', 'eps': 0}, 'syscollector': {'status': 'enabled', 'frequency': 60, 'eps': 5}, 'rootcheck': {'status': 'disabled', 'frequency': 60.0, 'eps': 0}, 'sca': {'status': 'disabled', 'frequency': 60, 'eps': 0}, 'hostinfo': {'status': 'disabled', 'eps': 0}, 'winevt': {'status': 'disabled', 'eps': 0}, 'logcollector': {'status': 'disabled', 'eps': 0}, 'receive_messages': {'status': 'enabled'}}
INFO:P8185:Waiting 0 seconds before sending EPS and keep-alive events
INFO:P8185:Starting 1 agents.
DEBUG:root:Starting - 1-bpcFltYPL7Ud8wR0-debian10(021)(debian10) - keepalive
DEBUG:root:Starting - 1-bpcFltYPL7Ud8wR0-debian10(021)(debian10) - syscollector
DEBUG:root:Starting - 1-bpcFltYPL7Ud8wR0-debian10(021)(debian10) - receive_messages
DEBUG:root:Startup - 1-bpcFltYPL7Ud8wR0-debian10(021)
DEBUG:root:KeepAlive - 1-bpcFltYPL7Ud8wR0-debian10(021)
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_osinfo", "data": {"checksum":"1634140017886803554","architecture":"x86_64","hostname":"1-bpcFltYPL7Ud8wR0-debian10","os_codename":"focal","os_major":"20","os_minor":"04","os_name":"Ubuntu","os_platform":"ubuntu","os_patch":"6","os_release":"sp1","os_version":"20.04.6LTS(FocalFossa)","os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/2011:24:58","sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_packages", "data": {"architecture":"","checksum":"LJVKW66TGN","description":"","format":"","groups":"editors","install_time":"2024/04/16 00:00:00","item_id":"GOJOKI0JO8","location":"","multiarch":"null","name":"bsd_os","priority":"optional","scan_time":"2023/12/1915:32:25","size":"11","source":"","vendor":"bsdi","version":"3.1"}, "operation": "INSERTED"}
DEBUG:root:Syscollector Event  - d:syscollector:{"type": "dbsync_packages", "data": {"architecture":"","checksum":"4KBI6XU15Q","description":"","format":"","groups":"editors","install_time":"2024/04/16 00:00:00","item_id":"ZPZ0QGFUIE","location":"","multiarch":"null","name":"freebsd","priority":"optional","scan_ [...]

2024-04-16 10:02 UTC, rafabailon commented
## Notes

When using the `simulate-agents` command, if the value of `-s` is too low (less than 5 according to my tests), only events of type `osinfo` are sent. This also happens if we add `--syscollector-event-types "osinfo packages"` to the command so it is a behavior that already occurred.

2024-04-17 16:01 UTC, Rebits requested changes
Originally, GeneratorSyscollector was not intended to produce vulnerability detector alerts, which makes it challenging to organically incorporate an option to send only one "osinfo" message and package types while directing the rest of the events.

However, this approach introduces several issues that compromise the consistency of the class.

For these reasons, I propose the creation of a new class, GeneratorVulnerabilityEvents, to handle package logic. This separation would leave only basic, non-real package data for GeneratorSyscollector.

This approach allows us to maintain the logic of GeneratorSyscollector, emphasizing syscollector message queue stress without generating actual vulnerable packages.

The new GeneratorVulnerabilityEvents would accept various parameters, such as the number of vulnerable packages per agent, types of events (inserted or deleted), custom package lists, etc.

Implementing specific event generation would disrupt the current logic of the agent simulator, originally designed to saturate manager queues with specific messages without considering whether they trigger alerts. Additionally, this class would deviate from the logic of including only event generators that the agent can execute (sysccheck, logcollector, etc.).
 
However, designing and creating a new simulator for generating specific alerts would incur significant costs at this time. Therefore, I recommend continuing with the creation of the proposed class for now.

2024-04-18 14:58 UTC, rafabailon commented
## Update

I have created a new PR to track the development https://github.com/wazuh/wazuh-qa/pull/5265

2024-04-18 14:58 UTC, closed without merging