Tests start before feeds are updated
wazuh/wazuh-qa pull request #5227
Opened 2024-04-16 12:19 UTC by santipadilla

|Related issue|
|-------------|
|    #5173         |

## Description

This PR changes the function that waits for the feed to finish. We achieve this by changing the log that tells us that the feed has finished and increasing the timeout.

2024-04-17 13:34 UTC, Rebits requested changes
GJ, minor change is required

2024-04-17 13:34 UTC, Rebits commented on CHANGELOG.md
> +- Change in the wait until the VD feed is completed ([#5227](https://github.com/wazuh/wazuh-qa/pull/5227)) \- (Tests)
```suggestion
- Change Vulnerability Detection feed updated waiter ([#5227](https://github.com/wazuh/wazuh-qa/pull/5227)) \- (Tests)
```

2024-04-17 16:03 UTC, Rebits approved these changes
LGTM

2024-04-17 17:54 UTC, Rebits requested changes
It seems after testing, that `INFO: Feed update process completed` log does not always appear in the manager.
When feeds are already downloaded, this log does not appear. This makes it impossible to test in an already prepared environment.

2024-04-30 08:32 UTC, Rebits approved these changes
LGTM

2024-04-30 11:24 UTC, juliamagan approved these changes

2024-04-30 11:24 UTC, merged