macOs test added
wazuh/wazuh-qa pull request #5264
Opened 2024-04-18 14:09 UTC by pro-akim

Adding features for macOs agent testing

2024-04-25 14:49 UTC, mhamra requested changes
@pro-akim
Please check the suggested changes.

2024-04-25 14:49 UTC, mhamra commented on deployability/modules/testing/tests/test_agent/test_stop.py
> +        assert 'inactive' in GeneralComponentActions.get_component_status(agent_params, 'wazuh-agent') or 'not running' in GeneralComponentActions.get_component_status(agent_params, 'wazuh-agent'), l
I don't recommend to call `logger.error` in assert statements. The second argument is the message assigned to the AssertionError exception. If you use `logger.error`, the return will be None, which will be the exception's message. Here's an example of what is the problem:

```
>>> import logging
>>> logger = logging.getLogger()
>>> assert False, logger.error('Error Message')
Error Message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: None
>>> assert False, 'Error Message'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: Error Message
```

Is it required to log the error? Pytest shows all the failures in the output report.

2024-04-25 17:26 UTC, mhamra commented
### UPDATE
I've run the test `deployability/modules/workflow_engine/examples/agent/vagrant/test-agent-complete-macOs.yaml`.

In the first run, the workflow file successfully allocated and provisioned the manager but failed to allocate the macOS agent.

After investigating the issue, I've found that the allocator modules require the installation of the `sshpass` command. After installing this utility, I've eliminated the manager's allocation and provisioning tasks from the workflow to reuse the existing AWS manager instance.

The macOS agent was allocated ok, and the testing task passed without failures.

<details><summary>workflow.log</summary>

```
[2024-04-25 13:01:43,119] [DEBUG] [87206] [MainThread] [workflow_engine]: Validating input file: modules/workflow_engine/examples/agent/vagrant/test-agent-complete-macOs.yaml
[2024-04-25 13:01:43,119] [DEBUG] [87206] [MainThread] [workflow_engine]: Loading schema file: /home/marcelo/.pyenv/versions/dtt-test/lib/python3.10/site-packages/workflow_engine/schemas/schema_v1.json
[2024-04-25 13:01:43,120] [DEBUG] [87206] [MainThread] [workflow_engine]: Loading yaml file: modules/workflow_engine/examples/agent/vagrant/test-agent-complete-macOs.yaml
[2024-04-25 13:01:43,143] [DEBUG] [87206] [MainThread] [workflow_engine]: Loading workflow file: modules/workflow_engine/examples/agent/vagrant/test-agent-complete-macOs.yaml
[2024-04-25 13:01:43,151] [DEBUG] [87206] [MainThread] [workflow_engine]: Process workflow.
[2024-04-25 13:01:43,151] [INFO] [87206] [MainThread] [workflow_engine]: Executing DAG tasks.
[2024-04-25 13:01:43,152] [INFO] [87206] [MainThread] [workflow_engine]: Executing tasks in parallel.
[2024-04-25 13:01:43,152] [INFO] [87206] [ThreadPoolExecutor-0_0] [workflow_engine]: [allocate-manager-linux-ubuntu-22.04-amd64] Starting task.
[2024-04-25 13:01:43,152] [DEBUG] [87206] [ThreadPoolExecutor-0_0] [workflow_engine]: Running task "allocate-manager-linux-ubuntu-22.04-amd64" with arguments: ['modules/allocation/main.py', '--action=create', '--provider=aws', '--size=large', '--composite-name=linux-ubuntu-22.04-amd64', '--inventory-output=/tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/inventory.yaml', '--track-output=/tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/track.yaml', '--label-termination-date=1d', '--label-team=qa']
[2024-04-25 13:01:43,968] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-04-25 13:01:44,057] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-04-25 13:01:44,057] [DEBUG] ALLOCATOR: Generating new key pair
[2024-04-25 13:01:44,057] [DEBUG] ALLOCATOR: Creating base directory: /tmp/wazuh-qa/AWS-E1AD3A41-E8AE-406F-BC70-C07DE933C635
[2024-04-25 13:02:03,530] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-E1AD3A41-E8AE-406F-BC70-C07DE933C635 directory to /tmp/wazuh-qa/i-0a94a947030293148
[2024-04-25 13:02:03,538] [INFO] ALLOCATOR: Instance i-0a94a947030293148 created.
[2024-04-25 13:02:05,424] [INFO] ALLOCATOR: Instance i-0a94a947030293148 started.
[2024-04-25 13:02:05,882] [INFO] ALLOCATOR: Inventory file generated at /tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/inventory.yaml
[2024-04-25 13:02:06,188] [WARNING] ALLOCATOR: Error on attempt 1 of 30: [Errno None] Unable to connect to port 2200 on 54.161.239.193
[2024-04-25 13:02:37,727] [INFO] ALLOCATOR: SSH connection successful.
[2024-04-25 13:02:37,729] [INFO] ALLOCATOR: Track file generated at /tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/track.yaml
[2024-04-25 13:02:37,837] [DEBUG] [87206] [ThreadPoolExecutor-0_0] [workflow_engine]: Finished task "allocate-manager-linux-ubuntu-22.04-amd64" execution with result:
[32m[2024-04-25 13:01:43] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa[0m
[37m[2024-04-25 13:01:44] [DEBUG] ALLOCATOR: No config provided. Generating from payload[0m
[37m[2024-04-25 13:01:44] [DEBUG] ALLOCATOR: Generating new key pair[0m
[37m[2024-04-25 13:01:44] [DEBUG] ALLOCATOR: Creating base directory: /tmp/wazuh-qa/AWS-E1AD3A41-E8AE-406F-BC70-C07DE933C635[0m
[37m[2024-04-25 13:02:03] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-E1AD3A41-E8AE-406F-BC70-C07DE933C635 directory to /tmp/wazuh-qa/i-0a94a947030293148[0m
[32m[2024-04-25 13:02:03] [INFO] ALLOCATOR: Instance i-0a94a947030293148 created.[0m
[32m[2024-04-25 13:02:05] [INFO] ALLOCATOR: Instance i-0a94a947030293148 started.[0m
[32m[2024-04-25 13:02:05] [INFO] ALLOCATOR: Inventory file generated at /tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/inventory.yaml[0m
[33m[2024-04-25 13:02:06] [WARNING] ALLOCATOR: Error on attempt 1 of 30: [Errno None] Unable to connect to port 2200 on 54.161.239.193[0m
[32m[2024-04-25 13:02:37] [INFO] ALLOCATOR: SSH connection successful.[0m
[32m[2024-04-25 13:02:37] [INFO] ALLOCATOR: Track file generated at /tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/track.yaml[0m

[2024-04-25 13:02:37,847] [INFO] [87206] [ThreadPoolExecutor-0_0] [workflow_engine]: [allocate-manager-linux-ubuntu-22.04-amd64] Finished task in 54.70 seconds.
[2024-04-25 13:02:37,863] [INFO] [87206] [ThreadPoolExecutor-0_0] [workflow_engine]: [provision-manager-linux-ubuntu-22.04-amd64] Starting task.
[2024-04-25 13:02:37,868] [DEBUG] [87206] [ThreadPoolExecutor-0_0] [workflow_engine]: Running task "provision-manager-linux-ubuntu-22.04-amd64" with arguments: ['modules/provision/main.py', '--inventory=/tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/inventory.yaml', "--install={'component': 'wazuh-manager', 'type': 'assistant', 'version': '4.7.3', 'live': True}"]
[2024-04-25 13:02:38,231] [DEBUG] PROVISIONER: Setting dependencies: {} for wazuh-manager component.
[2024-04-25 13:02:38,232] [INFO] PROVISIONER: Initiating provisionment.
[2024-04-25 13:02:38,232] [DEBUG] PROVISIONER: Running action install for components: [ComponentInfo(component='wazuh-manager', type='assistant', version='4.7.3', dependencies=None, live=True)]
[2024-04-25 13:02:38,232] [INFO] PROVISIONER: Provisioning "wazuh-manager"...
[2024-04-25 13:02:38,232] [DEBUG] PROVISIONER: Get OS family for ec2-54-161-239-193.compute-1.amazonaws.com.
[2024-04-25 13:02:38,232] [DEBUG] PROVISIONER: Using inventory: {'all': {'hosts': {'ec2-54-161-239-193.compute-1.amazonaws.com': {'ansible_port': 2200, 'ansible_user': 'ubuntu', 'ansible_ssh_private_key_file': '/tmp/wazuh-qa/i-0a94a947030293148/ubuntu-22.04-amd64-key-7243'}}}}
[2024-04-25 13:02:38,232] [DEBUG] PROVISIONER: Running playbook: {'hosts': 'ec2-54-161-239-193.compute-1.amazonaws.com', 'become': True, 'gather_facts': True, 'tasks': [{'name': 'Capture ansible_os_family', 'set_fact': {'ansible_os_family': "{{ ansible_facts['distribution_file_variety'] }}", 'cacheable': 'yes'}}]}
[2024-04-25 13:02:47,754] [DEBUG] PROVISIONER: Playbook {'hosts': 'ec2-54-161-239-193.compute-1.amazonaws.com', 'become': True, 'gather_facts': True, 'tasks': [{'name': 'Capture ansible_os_family', 'set_fact': {'ansible_os_family': "{{ ansible_facts['distribution_file_variety'] }}", 'cacheable': 'yes'}}]} finished with status {'skipped': {}, 'ok': {'ec2-54-161-239-193.compute-1.amazonaws.com': 2}, 'dark': {}, 'failures': {}, 'ignored': {}, 'rescued': {}, 'processed': {'ec2-54-161-239-193.compute-1.amazonaws.com': 1}, 'changed': {}}
[2024-04-25 13:02:47,755] [DEBUG] PROVISIONER: OS family: Debian.
[2024-04-25 13:02:47,755] [DEBUG] PROVISIONER: Render playbook with vars: {'component': 'wazuh-manager', 'version': '4.7.3', 'live': True, 'type': 'assistant', 'dependencies': None, 'templates_path': '/home/marcelo/wazuh/wazuh-qa/deployability/modules/provision/playbooks/wazuh/assistant/install', 'templates_order': ['download.j2', 'install.j2'], 'ansible_os_family': 'Debian'}.
[2024-04-25 13:02:47,755] [DEBUG] PROVISIONER: Templates found: ['download.j2', 'install.j2']
[2024-04-25 13:02:47,759] [DEBUG] PROVISIONER: Rendering template download.j2
[2024-04-25 13:02:47,761] [DEBUG] PROVISIONER: Rendering template install.j2
[2024-04-25 13:02:47,761] [DEBUG] PROVISIONER: [{'name': 'Install the required packages', 'shell': '\nsudo  [...]

2024-04-25 21:47 UTC, mhamra approved these changes
After a meeting with @pro-akim, we discussed the requested changes and arrived at the following decisions:
- Exception blocks in `deployability/modules/testing/tests/helpers/generic.py`
  Many tests are using the `HostInformation.get_os_type` method. The current implementation reads the track file. A better solution is to open the YAML file, convert it into a dictionary or an object, and reimplement the function to access the object instead of the file. We'll create a new issue to implement this procedure.

- assertions and log
  - We will replace the calls to `logger.error` with a string message in all the `assert` statements.
  We must define whether to send an error message to the log when the assert conditions are false. Pytest tests send the errors to the final report; the test doesn't need to duplicate the report.
  - We will create a new enhancement-type issue to implement the above bullets.

2024-04-26 13:51 UTC, pro-akim reviewed
The requested changes will be addressed in deferred issues as points of improvement

2024-04-26 13:55 UTC, rauldpm requested changes

2024-04-26 13:55 UTC, rauldpm commented on deployability/modules/workflow_engine/examples/agent/aws/test-agent-complete-macOs.yaml
> +  manager-os: linux-ubuntu-22.04-amd64
Remove or uncomment the Ventura and Sonoma lines

2024-04-26 13:55 UTC, rauldpm commented on deployability/modules/workflow_engine/examples/agent/vagrant/test-agent-complete-macOs.yaml
> +  manager-os: linux-ubuntu-22.04-amd64
Remove or uncomment the Ventura 13 comment

2024-04-26 15:08 UTC, pro-akim commented on deployability/modules/workflow_engine/examples/agent/aws/test-agent-complete-macOs.yaml
> +  manager-os: linux-ubuntu-22.04-amd64
The comments were left intentionally so that the user does not run multiple high-cost instances, and please note to always contact the @dev-devops-team.

2024-04-26 15:10 UTC, pro-akim commented on deployability/modules/workflow_engine/examples/agent/vagrant/test-agent-complete-macOs.yaml
> +  manager-os: linux-ubuntu-22.04-amd64
The comments were left intentionally so that the user does not run several operating systems in parallel because these have limited availability and the same must be communicated to @dev-devops-team.

2024-04-26 16:32 UTC, rauldpm approved these changes

2024-04-26 16:32 UTC, merged