Fix task dependencies
wazuh/wazuh-qa pull request #5308
Opened 2024-04-29 13:33 UTC by mhamra

# Description
Related issue: #5240 

This PR fixes the task dependencies on workflow example files.

2024-04-29 15:49 UTC, mhamra commented
### UPDATE
I've run the modified workflow file for the AWS provider and I obtained the following log file:

[workflow.log](https://github.com/wazuh/wazuh-qa/files/15151652/workflow.log)

2024-04-30 10:52 UTC, rauldpm requested changes
The provided log has errors, please review and justify them

https://github.com/wazuh/wazuh-qa/pull/5308#issuecomment-2083086894

Add a log for each YAML file

2024-04-30 12:20 UTC, mhamra commented
### EXPLANATION OF THE ERRORS IN THE LOG FILE

The `workflow.log` file includes errors because previous runs of the `workflow_engine` are in the same file. Please dismiss the first 55 lines of the log file and start reading from line 56,

This line should be the first line to take care of:
```
[2024-04-29 10:43:37,247] [INFO] [881354] [MainThread] [workflow_engine]: Executing DAG tasks.
```

2024-05-02 18:07 UTC, mhamra commented
### UPDATE
I've run this vagrant workflow file. By commenting on some lines, I've reduced the number of virtual machines to reduce the total run time.

<details><summary>dtt1-managers-poc-vagrant.yaml</summary>

```
version: 0.1
description: This workflow is used to test manager deployment for DDT1 PoC
variables:
  manager-os:
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-22.04-amd64
    - linux-centos-7-amd64
    # - linux-oracle-9-amd64
    # - linux-amazon-2-amd64
    # - linux-redhat-7-amd64
    # - linux-redhat-8-amd64
    # - linux-redhat-9-amd64
    # - linux-centos-8-amd64
    # - linux-debian-10-amd64
    # - linux-debian-11-amd64
    # - linux-debian-12-amd64
  infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager}"
          - inventory-output: "{working-dir}/manager-{manager}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager}/track.yaml"
    on-error: "abort-all"
    foreach:
      - variable: manager-os
        as: manager

  # Generic manager test task
  - task: "run-manager-tests"
    description: "Run tests install for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-linux-centos-7-amd64/inventory.yaml"
            - wazuh-2: "{working-dir}/manager-linux-ubuntu-20.04-amd64/inventory.yaml"
            - wazuh-3: "{working-dir}/manager-linux-ubuntu-22.04-amd64/inventory.yaml"
            # - wazuh-4: "{working-dir}/manager-linux-oracle-9-amd64/inventory.yaml"
            # - wazuh-5: "{working-dir}/manager-linux-amazon-2-amd64/inventory.yaml"
            # - wazuh-6: "{working-dir}/manager-linux-redhat-7-amd64/inventory.yaml"
            # - wazuh-7: "{working-dir}/manager-linux-redhat-8-amd64/inventory.yaml"
            # - wazuh-8: "{working-dir}/manager-linux-redhat-9-amd64/inventory.yaml"
            # - wazuh-9: "{working-dir}/manager-linux-centos-8-amd64/inventory.yaml"
            # - wazuh-10: "{working-dir}/manager-linux-debian-10-amd64/inventory.yaml"
            # - wazuh-11: "{working-dir}/manager-linux-debian-11-amd64/inventory.yaml"
            # - wazuh-12: "{working-dir}/manager-linux-debian-12-amd64/inventory.yaml"
          - tests: "install,restart,stop,uninstall"
          - component: "manager"
          - wazuh-version: "4.7.3"
          - wazuh-revision: "40714"
          - live: "True"
    depends-on:
      - "allocate-manager-linux-ubuntu-20.04-amd64"
      - "allocate-manager-linux-ubuntu-22.04-amd64"
      - "allocate-manager-linux-centos-7-amd64"
      # - "allocate-manager-linux-amazon-2-amd64"
      # - "allocate-manager-linux-redhat-7-amd64"
      # - "allocate-manager-linux-redhat-8-amd64"
      # - "allocate-manager-linux-redhat-9-amd64"
      # - "allocate-manager-linux-centos-8-amd64"
      # - "allocate-manager-linux-debian-10-amd64"
      # - "allocate-manager-linux-debian-11-amd64"
      # - "allocate-manager-linux-debian-12-amd64"
      # - "allocate-manager-linux-oracle-9-amd64"

```
</details>

2024-05-03 13:20 UTC, pro-akim approved these changes
## Review Notes
LGTM

2024-05-03 13:23 UTC, rauldpm approved these changes

2024-05-03 13:23 UTC, merged