Force instance name to be defined in vagrant deploy
wazuh/wazuh-qa pull request #5342
Opened 2024-05-06 18:08 UTC by c-bordon

Close https://github.com/wazuh/wazuh-qa/issues/5311

The PR aims to validate the configuration of an instance name in vagrant, either with the `--instance-name` or `--label-issue` parameter

Tests:

**Vagrant local:** https://github.com/wazuh/wazuh-qa/issues/5311#issuecomment-2096534037
**Issue format validation:** https://github.com/wazuh/wazuh-qa/issues/5311#issuecomment-2096536806
**AWS:** https://github.com/wazuh/wazuh-qa/issues/5311#issuecomment-2096546798
**Vagrant macOS ARM:** https://github.com/wazuh/wazuh-qa/issues/5311#issuecomment-2096577791
**Instance dir concurrency:** https://github.com/wazuh/wazuh-qa/issues/5311#issuecomment-2096606306

2024-05-06 19:35 UTC, teddytpc1 approved these changes

2024-05-06 19:38 UTC, teddytpc1 approved these changes

2024-05-07 15:29 UTC, pro-akim requested changes
## Review Notes
To facilitate debugging in case of failure, add a log message at:

2024-05-07 15:29 UTC, pro-akim commented on deployability/modules/allocation/vagrant/provider.py
> +                raise ValueError(f"The issue label was not provided or is of incorrect format, example: https://github.com/wazuh/<repository>/issues/<issue-number>")
## Review Notes
Please add log error message in order to debug easily

2024-05-07 15:29 UTC, pro-akim commented on deployability/modules/allocation/vagrant/provider.py
> +                raise ValueError(f"Instance directory {host_instance_dir} already exists on remote host. Check if it is possible to delete the directory on the remote host.")
## Review Notes
Please add log error message in order to debug easily

2024-05-07 15:30 UTC, pro-akim approved these changes
## Review Notes
LGTM

2024-05-07 17:42 UTC, merged