Skip truncate test change agent manager
wazuh/wazuh-qa pull request #5355
Opened 2024-05-09 12:40 UTC by santipadilla

|Related issue|
|-------------|
|    #5345         |

## Description

This PR skip truncating logs from `test_change_agent_manager` case.

2024-05-09 14:59 UTC, rafabailon approved these changes
LGTM

2024-05-10 09:36 UTC, juliamagan requested changes

2024-05-10 09:36 UTC, juliamagan commented on tests/end_to_end/test_vulnerability_detector/conftest.py
I don't think this is the best approach. It may be necessary that the logs are truncated, what we must avoid is that they are not truncated too much. For example, the affected test uses two fixtures to truncate the logs.

2024-05-13 15:00 UTC, Rebits approved these changes
LGTM

2024-05-13 15:03 UTC, santipadilla commented on tests/end_to_end/test_vulnerability_detector/conftest.py
Fixed here: https://github.com/wazuh/wazuh-qa/pull/5355/commits/d99ede4bfa859316019fa7a820932d448ab8e8f5

2024-05-13 15:22 UTC, juliamagan approved these changes

2024-05-13 15:22 UTC, merged