Update wazuh_template_branch to 4.8.1
wazuh/wazuh-qa pull request #5499
Opened 2024-06-14 09:18 UTC by Rebits

# Description

This PR update wazuh_template_branch to 4.8.1

## Testing performed

Build:

2024-06-17 08:51 UTC, santipadilla approved these changes

2024-06-18 15:17 UTC, juliamagan requested changes

2024-06-18 15:17 UTC, juliamagan commented on provisioning/roles/wazuh/ansible-filebeat-oss/defaults/main.yml
Checking the repository we could see that there are more files with the hardcoded version, for example, `provisioning/roles/wazuh/ansible-wazuh-agent/defaults/main.yml`:


https://github.com/wazuh/wazuh-qa/blob/77da068720e4eaadb9ccd98884d1fc470f8f7275/provisioning/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L3


In addition, this is not maintainable, we must check if this version is essential (in the same playbook in the installation by sources is v4.4.4) and if it is, look for a way to parameterize it, if not, we will have to take into account these files every time we make a version bump.

2024-06-18 17:19 UTC, Rebits commented on provisioning/roles/wazuh/ansible-filebeat-oss/defaults/main.yml
These values are default and not currently used in provisioning.

The inclusion of some playbooks from a wazuh-ansible repository for provisioning the E2E VD environment was a condition accepted. This has resulted in non-maintainable code. However, refactoring is not planned as we intend to migrate to new tools in the future.

I suggest replacing all hardcoded values in each version bump

2024-06-19 10:53 UTC, Rebits commented on provisioning/roles/wazuh/ansible-filebeat-oss/defaults/main.yml
Proposed changes will be carried on https://github.com/wazuh/wazuh-qa/issues/5509

2024-06-19 14:12 UTC, juliamagan approved these changes

2024-06-19 14:12 UTC, merged