Fix unexpected warnings in E2E vulnerability detection tests
wazuh/wazuh-qa pull request #5711
Opened 2024-09-03 16:31 UTC by Rebits

# Description

As specify in [Unexpected errors and warnings in the vulnerability detection E2E tests](https://github.com/wazuh/wazuh-qa/issues/5698), E2E vulnerability detection tests fail due to unexpected errors in the environment for the initial scan tests. These errors are expected in the test environment due to the removal and register of the same agents.
This PR includes some changes to avoid the tests fails due to these expected warnings and errors 

# Changes
- Include a timeout to prevent connection errors
- Check only errors and critical messages

## Testing performed

**Build**:

2024-09-04 10:26 UTC, jseg380 submitted a review, later dismissed
LGTM

2024-09-09 08:29 UTC, juliamagan requested changes
GJ! Just a few minor changes.

2024-09-09 08:29 UTC, juliamagan commented on CHANGELOG.md
> +- Fix unexpected warnings in E2E vulnerability detection tests ([#5711](https://github.com/wazuh/wazuh-qa/pull/5711/)) \- (Tests)
```suggestion
- Fix unexpected warnings in E2E vulnerability detection tests ([#5711](https://github.com/wazuh/wazuh-qa/pull/5711)) \- (Framework + Tests)
```

2024-09-16 10:13 UTC, Rebits commented on CHANGELOG.md
> +- Fix unexpected warnings in E2E vulnerability detection tests ([#5711](https://github.com/wazuh/wazuh-qa/pull/5711/)) \- (Tests)
Done in 916d90363fab

2024-09-19 11:09 UTC, juliamagan approved these changes

2024-09-19 11:09 UTC, merged