Revert active-response test changes
wazuh/wazuh-qa pull request #5734
Opened 2024-09-10 14:51 UTC by GGP1

# Description

Reverts the changes from https://github.com/wazuh/wazuh-qa/pull/4657.

## Testing performed

|OS|Package used|
|--|--|
| Debian 10 | 4.9.0-1 |

| Validation | Jenkins | Local  | OS  | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|
|    [Build](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/707)       | 🟢 ⚫ | ⚫⚫ |         |         | Nothing to highlight |

2024-09-11 07:49 UTC, javiersanchz approved these changes, later dismissed
LGTM !

2024-09-12 14:20 UTC, nico-stefani commented
LGTM!

2024-09-12 14:25 UTC, nico-stefani approved these changes, later dismissed
LGTM

2024-09-13 09:17 UTC, juliamagan requested changes
GJ! Just a minor change.

2024-09-13 09:17 UTC, juliamagan commented on CHANGELOG.md
> -- Add new behaviour for endpoints marked as xfail in api_endpoints_performance test ([#4657](https://github.com/wazuh/wazuh-qa/pull/4657)) \ (Tests)
We should add a `Deleted` entry in the 4.9.1 changelog, not delete it from 4.8.0, because in 4.8.0 the change is still there.

2024-09-13 13:57 UTC, juliamagan approved these changes

2024-09-13 13:57 UTC, merged