Modify VD E2E tests to use package feed
wazuh/wazuh-qa pull request #5739
Opened 2024-09-13 07:36 UTC by santipadilla

### Closing/Related Issue

Closes #5700

### Description

Modify VD E2E tests to use packet feed instead of CTI feed.

## Tasks

- [x] Test that the suggested change works as expected.
- [x] If it works, implement this change to E2E.

2024-09-13 08:27 UTC, rafabailon approved these changes, later dismissed
LGTM

2024-09-17 09:32 UTC, juliamagan requested changes
Now that the feed is going to fail to download, we must take these logs into account so that the tests are not marked as failed. For example in [this build](https://ci.wazuh.info/job/Test_e2e_system/379/), we can see that test X has failed because the following logs appear, which should be expected:

```json
"manager1": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": [
            "2024/09/12 12:41:57 wazuh-modulesd:content-updater[82704] offlineDownloader.hpp:90 at operator()(): WARNING: Error '-1' when downloading file: Couldn't connect to server."
        ]
    }
```

However, this is a WARNING level log, and they were disabled in https://github.com/wazuh/wazuh-qa/issues/5699. Please, update your base branch and execute the tests again.

2024-09-17 11:53 UTC, santipadilla commented
- What you say will be fixed in https://github.com/wazuh/wazuh-qa/issues/5698, which has not yet been merged.
- Also, this known issue: https://github.com/wazuh/wazuh-qa/issues/5715 appears.
- Changelog updated.

2024-09-17 13:55 UTC, juliamagan approved these changes

2024-09-17 13:55 UTC, merged