Changed wazuh-agent service start from install test to registration test
wazuh/wazuh-qa pull request #5762
Opened 2024-09-20 18:36 UTC by hossam1522

# Description

This pull request is based on https://github.com/wazuh/wazuh-qa/issues/5741. As said in https://github.com/wazuh/wazuh-qa/issues/5741#issuecomment-2364003587, the service cannot be started in the installation test because there is no manager IP assigned. Therefore, the solution is to start the service in the registration test, after adding the manager IP to the agent configuration.

After doing that and running the test, you can see in the logs that the message reported in the issue no longer appears:
- [agent.log](https://github.com/user-attachments/files/17079223/agent.log)

---

## Testing performed

| Validation | Jenkins | Local  | OS  | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|
|           | ⚫⚫ | :green_circle: :green_circle: |     Ubuntu 24.04    |    https://github.com/wazuh/wazuh-qa/commit/5584a69747aa5f1b01210855e43f3c2d37149b1d     | Nothing to highlight |

2024-09-23 13:44 UTC, rauldpm requested changes
The changes affect Windows and macOS systems, please run a complete agent tier

2024-09-24 16:47 UTC, hossam1522 commented
A complete agent tier test was executed correctly:

Log:
- [jobflow.log](https://github.com/user-attachments/files/17117842/jobflow.log)

Template:
- [template.txt](https://github.com/user-attachments/files/17117859/template.txt)

2024-09-26 16:59 UTC, joaquinsgi requested changes
Gj! But it is necessary to update the CHANGELOG.md

2024-09-26 17:17 UTC, joaquinsgi approved these changes, later dismissed

2024-09-27 14:56 UTC, juliamagan requested changes
GJ! Please, solve the conflicts.

2024-09-30 15:18 UTC, juliamagan requested changes
Reviewing the test, I am a bit concerned about the implementation of this one:

1. It was failing to start but was not reported as failed.
2. The install starts the agent without registering it, which is why it fails. But also, it then checks for stopped, so it wouldn't make sense for it to start it, or for the check to be stopped.
3. The state check is too wide, it should check that the status is correct for all valid statuses, it would even be expected statuses instead of valid statuses.
4. The registration function is modified, which is not used by this test and this modification could affect where it is being used, since restart has been changed by start, and if the agent is already started, it is not going to be registered.


Please, let's take a quick look at this test, see what status is expected, see why the error is not being handled well and make the necessary modifications.

2024-10-04 17:58 UTC, hossam1522 commented
Everything related to starting the agent and checking its status has been removed from the installation function since, as no manager has been registered, it will fail to start causing the log reported in this issue. However, even if it fails in that part, the test does not report any failure and passes as valid, which should not happen and for which the following issue has been opened: 

- https://github.com/wazuh/wazuh-qa/issues/5802

It has been considered most logical to start the agent after registering a manager. For this reason, the `restart` in the registration function has been modified by a `start`, because previously it was not possible to start the agent because there was no associated manager.

As this has been modified for Linux and MacOS only (The change that was made in the Windows test was tested on https://github.com/wazuh/wazuh-qa/pull/5762#issuecomment-2371816242), a build has been run to demonstrate that both the installation test and the registration test work perfectly and that the erroneous log reported in the issue no longer appears.

- Log: [jobflow.log](https://github.com/user-attachments/files/17262162/jobflow.log)

- Template: [template-5741.txt](https://github.com/user-attachments/files/17262170/template-5741.txt)

2024-10-07 15:25 UTC, rauldpm approved these changes, later dismissed

2024-10-08 14:40 UTC, juliamagan requested changes

2024-10-08 14:40 UTC, juliamagan commented on CHANGELOG.md
> +
```suggestion
```

2024-10-08 14:44 UTC, juliamagan requested changes

2024-10-08 14:44 UTC, juliamagan commented on CHANGELOG.md
> +- Fix failed to disable wazuh-manager.service ([#5775])(https://github.com/wazuh/wazuh-qa/pull/5775)) \- (Tests)
```suggestion
- Fix failed to disable wazuh-manager.service ([#5775](https://github.com/wazuh/wazuh-qa/pull/5775)) \- (Tests)
```

2024-10-08 14:46 UTC, juliamagan approved these changes

2024-10-08 14:46 UTC, merged