Tests remove session
wazuh/wazuh-qa pull request #854
Opened 2020-09-04 11:12 UTC by JcabreraC

Hello team,

This PR adds tests for remove session on demand in `Wazuh-logtest`. We implement tests that send remove session messages to logtest (writing the wazuh-logtest unix socket) and check error, warning or success message is expected.

Closes #848 

# Tests checks

- [x] Proven that tests **pass** when they have to pass
- [x] Proven that tests **fail** when they have to fail
- [x] Tested and passed in Jenkins.

# Results

- When the expected behavior occurs:

```

```

Best regards,
Juan Cabrera

2020-09-08 01:14 UTC, juliancnn approved these changes

2020-09-09 11:39 UTC, jnasselle requested changes
I forgot to mention that also adding "Remove invalid boolean token" will gave us 100% coverage about token data types

2020-09-09 11:39 UTC, jnasselle commented on tests/integration/test_logtest/test_remove_session/data/remove_session.yaml
> +  name: "Remove invalid token type"
I think "Remove invalid numeric token" define better the test case

2020-09-09 11:39 UTC, jnasselle commented on tests/integration/test_logtest/test_remove_session/data/remove_session.yaml
> +  name: "Remove null token"
I think "Remove invalid empty json object token" define better the test case ( based on JSON Data types)

2020-09-09 11:39 UTC, jnasselle commented on tests/integration/test_logtest/test_remove_session/data/remove_session.yaml
> +  name: "Remove invalid token"
I think "Remove invalid json object token" define better the test case ( based on JSON Data types)

2020-09-09 11:39 UTC, jnasselle commented on tests/integration/test_logtest/test_remove_session/data/remove_session.yaml
> +  name: "Remove invalid token list"
I think "Remove invalid array token" define better the test case ( based on JSON Data types)

2020-09-09 12:15 UTC, jnasselle approved these changes

2020-09-09 12:15 UTC, merged