Registry integration test: Test tags
wazuh/wazuh-qa pull request #909
Opened 2020-10-21 10:09 UTC by antoniomanuelfr

Hello team,

This PR aims to add a new integration test in order to check that the `tag`  option is working correctly.

Closes #896

# Tests logic
- The test will configure some keys using the tag option and it will create values in both keys.
- When the events are generated, it checks that the events have the `tag` field and it's content is the same as the configured.

# Tests checks

- [ ] Proven that tests **pass** when they have to pass
- [ ] Proven that tests **fail** when they have to fail
- [ ] Proven that tests have the expected behavior in **RPM and DEB**
- [ ] Checked that **all vulnerability detector tests work correctly** (my changes don't break anything)
- [ ] Tested and passed in Jenkins. Build URL: `<YOUR_JENKINS_BUILD_URL>`

Best regards.

2020-10-27 16:28 UTC, jesusjimsa requested changes
I have requested some style changes. I will run the tests tomorrow to confirm they work correctly and send a new revision if there is something wrong.

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
> +
There are too many blank lines before `registry_value_cud`, remove one of them.
```suggestion
```

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
> +                    )
These lines are under-indented.
```suggestion
                       time_travel=get_configuration['metadata']['fim_mode'] == 'scheduled',
                       min_timeout=global_parameters.default_timeout,
                       triggers_event=True,
                       validators_after_cud=[tag_validator]
                       )
```

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
>  from wazuh_testing.tools import PREFIX
`PREFIX` is imported but unused.
```suggestion
```

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
> +from wazuh_testing.fim import LOG_FILE_PATH, registry_value_cud, generate_params, delete_registry, registry_parser
`delete_registry` and `registry_parser` are imported but unused.
```suggestion
from wazuh_testing.fim import LOG_FILE_PATH, registry_value_cud, generate_params
```

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
> +test_regs = [ os.path.join(key, sub_key), os.path.join(key, sub_key_2)]
Remove whitespace after `[`.
```suggestion
test_regs = [os.path.join(key, sub_key), os.path.join(key, sub_key_2)]
```

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
> +conf_params = {'WINDOWS_REGISTRY_1':reg1, 'WINDOWS_REGISTRY_2':reg2}
Missing whitespace after `:`.
```suggestion
conf_params = {'WINDOWS_REGISTRY_1': reg1, 'WINDOWS_REGISTRY_2': reg2}
```

2020-10-27 16:28 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_tags/test_registry_tags.py
>  # Fixtures
There should be two blank lines before a function declaration.
```suggestion
# Fixtures

```

2020-10-28 12:18 UTC, jesusjimsa approved these changes
LGTM!

2020-10-30 10:53 UTC, bah07 approved these changes
LGTM!

2020-10-30 10:53 UTC, merged