Registry integration test: Ignore
wazuh/wazuh-qa pull request #917
Opened 2020-10-26 11:40 UTC by antoniomanuelfr

Hello team,
This PR aims to add a new test for the Windows registry integration test.
Closes #782

# Tests logic
 ### First case
- Monitor two keys: One with `arch="64bit` and another with `arch="both"` and using the `registry_ignore` option (using the path to the ignored key and using the regex option) to ignore certain keys
- It creates keys and check that all the events are generated if te key is not ignored. In case that the key is ignored, the test checks that the message `Ignoring 'key' 'HKEY_........` appears.
### Second case
- Monitor two keys: One with `arch="64bit` and another with `arch="both"` and using the `registry_ignore_value` option (using the path of the value and the regex option) to ignore certain values.
- It creates values and check that all the events are generated if the value is not ignored. In case that the value is ignored, the test checks that the meesage `Ignoring 'value' 'HKEY_........` appears.
# Tests checks

- [X] Proven that tests **pass** when they have to pass
- [ ] Tested and passed in Jenkins. Build URL: `<YOUR_JENKINS_BUILD_URL>`

## Windows

- When the expected behavior occurs:

```
python -m pytest -vv test_ignore\
============================= test session starts 
metadata: {'Python': '3.7.3', 'Platform': 'Windows-7-6.1.7601-SP1'}
collected 36 items

[  2%] test_ignore_registry.py PASSED
[  5%] test_ignore_registry.py PASSED
[  8%] test_ignore_registry.py PASSED
[ 11%] test_ignore_registry.py PASSED
[ 13%] test_ignore_registry.py PASSED
[ 16%] test_ignore_registry.py PASSED
[ 19%] test_ignore_registry.py PASSED
[ 22%] test_ignore_registry.py PASSED
[ 25%] test_ignore_registry.py SKIPPED
[ 27%] test_ignore_registry.py SKIPPED
[ 30%] test_ignore_registry.py SKIPPED
[ 33%] test_ignore_registry.py SKIPPED
[ 36%] test_ignore_registry.py SKIPPED
[ 38%] test_ignore_registry.py SKIPPED
[ 41%] test_ignore_registry.py SKIPPED
[ 44%] test_ignore_registry.py SKIPPED
[ 47%] test_ignore_registry.py SKIPPED
[ 50%] test_ignore_registry.py SKIPPED
[ 52%] test_ignore_registry.py SKIPPED
[ 55%] test_ignore_registry.py SKIPPED
[ 58%] test_ignore_registry.py SKIPPED
[ 61%] test_ignore_registry.py SKIPPED
[ 63%] test_ignore_registry.py SKIPPED
[ 66%] test_ignore_registry.py SKIPPED
[ 69%] test_ignore_registry.py SKIPPED
[ 72%] test_ignore_registry.py SKIPPED
[ 75%] test_ignore_registry.py PASSED
[ 77%] test_ignore_registry.py PASSED
[ 80%] test_ignore_registry.py PASSED
[ 83%] test_ignore_registry.py PASSED
[ 86%] test_ignore_registry.py PASSED
[ 88%] test_ignore_registry.py PASSED
[ 91%] test_ignore_registry.py PASSED
[ 94%] test_ignore_registry.py PASSED
[ 97%] test_ignore_registry.py PASSED
[100%]
============== 18 passed, 18 skipped in 37.11s ===================
```
Best regards.

2020-10-28 15:33 UTC, jesusjimsa requested changes
This test is failing.
[test_registry.zip](https://github.com/wazuh/wazuh-qa/files/5452998/test_registry.zip)

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        KEY_WOW64_32KEY, KEY_WOW64_64KEY, generate_params, callback_detect_event, check_time_travel, modify_registry_value
`delete_registry` is imported but unused. Also, line 12 exceeds 120 characters.
```suggestion
from wazuh_testing.fim import LOG_FILE_PATH, callback_ignore, create_registry, registry_parser, KEY_WOW64_32KEY, \
    KEY_WOW64_64KEY, generate_params, callback_detect_event, check_time_travel, modify_registry_value
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
>  from wazuh_testing.tools.time import TimeMachine
`TimeMachine` is imported but unused.
```suggestion
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +               'REGISTRY_IGNORE_2' : os.path.join(reg2, ignore_key),
Whitespace before `:`.
https://www.flake8rules.com/rules/E203.html
```suggestion
               'REGISTRY_IGNORE_2': os.path.join(reg2, ignore_key),
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +               'VALUE_IGNORE_REGEX' : ignore_value_regex
Whitespace before :.
```suggestion
               'VALUE_IGNORE_1': os.path.join(reg1, ignore_value),
               'VALUE_IGNORE_2': os.path.join(reg2, ignore_value),
               'VALUE_IGNORE_REGEX': ignore_value_regex
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                         get_configuration, configure_environment, restart_syscheckd, wait_for_fim_start):
This line is under-indented.
```suggestion
                             get_configuration, configure_environment, restart_syscheckd, wait_for_fim_start):
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +def test_ignore_registry_key(root_key, registry, subkey, arch, triggers_event, tags_to_apply,
These parameters are not documented.

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                                    accum_results=2).result()
These lines are under-indented.
```suggestion
                                        callback=callback_detect_event,
                                        error_message='Did not receive expected '
                                                      '"Sending FIM event: ..." event',
                                        accum_results=2).result()
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        assert event[1]['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', f'Parent key arch not equal.'
None of these error messages are using the format option, please remove it. By removing the `f`, line 103 will not exceed 120 characters.
Also, please capitalize the error message in line 99.
```suggestion
        assert event[0]['data']['type'] == 'added', 'Wrong event type.'
        assert event[0]['data']['path'] == os.path.join(root_key, registry, subkey), 'Wrong key path.'
        assert event[0]['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', 'Wrong key arch.'

        assert event[1]['data']['type'] == 'modified', 'Parent key event type not equal'
        assert event[1]['data']['path'] == os.path.join(root_key, registry), 'Wrong parent key path.'
        assert event[1]['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', 'Parent key arch not equal.'
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                                                   callback=callback_ignore).result()
This line is over-indented.
```suggestion
                                                  callback=callback_ignore).result()
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        while True: # Look for the ignore event of the created key
Please, have at least two spaces before an inline comment: https://www.flake8rules.com/rules/E261.html
```suggestion
        while True:  # Look for the ignore event of the created key
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                            accum_results=1).result()
These lines are under-indented.
```suggestion
                                        callback=callback_detect_event,
                                        error_message='Did not receive expected '
                                                      '"Sending FIM event: ..." event',
                                        accum_results=1).result()
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        assert event['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', f'Parent key arch not equal.'
None of these error messages is using the format option, please remove the `f`.
```suggestion
        assert event['data']['type'] == 'modified', 'Parent key event type not equal'
        assert event['data']['path'] == os.path.join(root_key, registry), 'Wrong parent key path.'
        assert event['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', 'Parent key arch not equal.'
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +def test_ignore_registry_value(root_key, registry, arch, value, triggers_event, tags_to_apply,
These parameters are not documented.

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                         get_configuration, configure_environment, restart_syscheckd, wait_for_fim_start):
This line is under-indented.
```suggestion
                               get_configuration, configure_environment, restart_syscheckd, wait_for_fim_start):
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                                accum_results=2 if triggers_event else 1).result()
These lines are under-indented.
```suggestion
                                    callback=callback_detect_event,
                                    error_message='Did not receive expected '
                                                  '"Sending FIM event: ..." event',
                                    accum_results=2 if triggers_event else 1).result()
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +
Please, remove this blank line.
```suggestion
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        assert event[1]['data']['value_name'] == value, f'Wrong value name'
None of these error messages are using the format option, please remove it. By removing the f, line 167 will not exceed 120 characters.
Also, please capitalize the error message in line 171.
```suggestion
        assert event[0]['data']['type'] == 'modified', 'Parent key event type not equal'
        assert event[0]['data']['path'] == os.path.join(root_key, registry), 'Wrong parent key path.'
        assert event[0]['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', 'Parent key arch not equal.'

        assert event[1]['data']['type'] == 'added', 'Wrong event type.'
        assert event[1]['data']['path'] == os.path.join(root_key, registry), 'Wrong value path.'
        assert event[1]['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', 'Wrong key arch.'
        assert event[1]['data']['value_name'] == value, 'Wrong value name'
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +
Please, remove this blank line.
```suggestion
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        assert event['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', f'Parent key arch not equal.'
None of these error messages are using the format option, please remove it.
```suggestion
        assert event['data']['type'] == 'modified', 'Parent key event type not equal'
        assert event['data']['path'] == os.path.join(root_key, registry), 'Wrong parent key path.'
        assert event['data']['arch'] == '[x32]' if arch == KEY_WOW64_32KEY else '[x64]', 'Parent key arch not equal.'
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +        while True: # Look for the ignore event of the created value
Please, have at least two spaces before an inline comment.
```suggestion
        while True:  # Look for the ignore event of the created value
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +                                                   callback=callback_ignore).result()
This line is under-indented.
```suggestion
                                                    callback=callback_ignore).result()
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
`sys` and `timedelta` are imported but unused.

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/test_ignore_registry.py
> +               'WINDOWS_REGISTRY_2':reg2,
Missing whitespace after `:`.
```suggestion
conf_params = {'WINDOWS_REGISTRY_1': reg1,
               'WINDOWS_REGISTRY_2': reg2,
```

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/data/wazuh_registry_ignore_conf.yaml
> +                - arch: '64bit'
Why adding the same regex for both architectures and for 64 bit alone?

2020-10-28 15:33 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_ignore/data/wazuh_registry_ignore_conf.yaml
> +                - arch: '64bit'
Why adding the same regex for both architectures and for 64 bit alone?

2020-10-30 09:16 UTC, jesusjimsa approved these changes
LGTM!

2020-10-30 11:01 UTC, bah07 approved these changes
LGTM!

2020-10-30 11:01 UTC, merged