Add registry integration tests for multiple registries
wazuh/wazuh-qa pull request #918
Opened 2020-10-27 10:09 UTC by jesusjimsa

| Related issue |
| ------------- |
| #893              |

## Description

This pull request adds tests for multiple registries and multiple keys.

### Multiple keys

This test creates a configuration with `70` registry keys in a single entry. Only 64 of them can be monitred in the same `windows_registry` tag so the remaining registry keys will be discarded (these are check). After checking the discarded registry keys, the test will create/modify/delete a registry key and a registry value in every monitored key and check that the events raised are correct.

### Multiple entries

This test creates a configuration with `64` registry keys in different entries. All of them can be monitred by FIM. After creating the configuration, the test will create/modify/delete a registry key and a registry value in every monitored key and check that the events raised are correct.

## Results

[test_registry.zip](https://github.com/wazuh/wazuh-qa/files/5444443/test_registry.zip)

<img width="420" alt="Captura de pantalla 2020-10-27 a las 9 59 26" src="https://user-images.githubusercontent.com/16068600/97286184-1a669680-183b-11eb-9213-e31710514f3f.png">

This pull request closes #893.

2020-10-28 08:39 UTC, antoniomanuelfr requested changes

2020-10-28 08:39 UTC, antoniomanuelfr commented on tests/integration/test_fim/test_registry/test_multiple_registries/common.py
> +                func(key_handle, 'test_value', win32con.REG_SZ, content)
```suggestion
                func(key_handle, 'test_value', REG_SZ, content)
```

2020-10-28 08:39 UTC, antoniomanuelfr commented on tests/integration/test_fim/test_registry/test_multiple_registries/common.py
> +            win32api.RegCloseKey(key_handle)
```suggestion
            RegCloseKey(key_handle)
```

2020-10-28 08:39 UTC, antoniomanuelfr commented on tests/integration/test_fim/test_registry/test_multiple_registries/common.py
> +import win32con
Instead of importing the entire library, import only the used variables
```suggestion
from win32con import REG_SZ
```

2020-10-28 08:39 UTC, antoniomanuelfr commented on tests/integration/test_fim/test_registry/test_multiple_registries/common.py
> +import win32api
Same as before
```suggestion
from win32api import RegCloseKey
```

2020-10-28 12:11 UTC, antoniomanuelfr approved these changes
LGTM!

2020-10-30 10:43 UTC, bah07 approved these changes
LGTM!

2020-10-30 10:44 UTC, merged