Registry integration test: Recursion level
wazuh/wazuh-qa pull request #919
Opened 2020-10-27 12:49 UTC by antoniomanuelfr

Hello team,

This PR aims to add a new test for the windows registry integration tests
Closes #895

# Tests logic
This test has only one case: 
- The test will monitor some keys with different recursion level. Then it creates values in the lower levels and in the last levels and check that the alerts are generated.
- After that, the test creates keys with a higher recursion level and checks that no events are generated in these keys

# Tests checks

- [X] Proven that tests **pass** when they have to pass
- [X] Proven that tests **fail** when they have to fail
- [ ] Tested and passed in Jenkins. Build URL: `<YOUR_JENKINS_BUILD_URL>`

## Windows

- When the expected behavior occurs:

```
python -m pytest -vvx test_recursion_level\
=================================== test session starts ============
metadata: {'Python': '3.7.3', 'Platform': 'Windows-7-6.1.7601-SP1',
collected 4 items

test_recursion_level_registry.py PASSED [ 25%]
test_recursion_level_registry.py PASSED [ 50%]
test_recursion_level_registry.py PASSED [ 75%]
test_recursion_level_registry.py PASSED [100%]

=========================================== 4 passed in 173.19s (0:02:53) ==============

```
Best regards.

2020-10-30 09:58 UTC, jesusjimsa requested changes
The last case is failing for me.
[recursion2.zip](https://github.com/wazuh/wazuh-qa/files/5464349/recursion2.zip)

2020-10-30 09:58 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_recursion_level/test_recursion_level_registry.py
>  import os
Please, add one blank line between the comment and the first import.
```suggestion

import os
```

2020-10-30 09:58 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_recursion_level/test_recursion_level_registry.py
> +}
This closing bracket does not match visual indentation.
```suggestion
               }
```

2020-10-30 09:58 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_recursion_level/test_recursion_level_registry.py
> +@pytest.mark.parametrize('root_key, registry, arch, edge_limit, ignored_levels', [
Please, add two blank lines before a function declaration.
```suggestion

@pytest.mark.parametrize('root_key, registry, arch, edge_limit, ignored_levels', [
```

2020-10-30 09:58 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_recursion_level/test_recursion_level_registry.py
> +        for level in range (recursion_level):
Remove the whitespace before the `(`.
```suggestion
        for level in range(recursion_level):
```

2020-10-30 09:58 UTC, jesusjimsa commented on tests/integration/test_fim/test_registry/test_recursion_level/data/wazuh_recursion_windows_registry.yaml
> +        - recursion_level: LEVEL_3
You are creating the registry keys with a 64 bit architecture, but the configuration does not set the architecture, being 32 bit by default. This causes the test to fail. Add an `arch` attribute to fix this.

2020-11-11 09:52 UTC, jesusjimsa requested changes
The test keeps failing in Windows.
[test_recursion.zip](https://github.com/wazuh/wazuh-qa/files/5523247/test_recursion.zip)

2020-11-17 11:15 UTC, jesusjimsa approved these changes
LGTM!

2020-11-17 15:18 UTC, Molter73 approved these changes
LGTM!

2020-11-17 15:23 UTC, merged