Added test_timezone_changes to test_fim
wazuh/wazuh-qa pull request #960
Opened 2020-12-02 07:50 UTC by jotacarma90

Hello team,

Closes https://github.com/wazuh/wazuh/issues/4167

This PR add to integration test, test_fim, a test to check that a timezone change do not generate modified event in files.

2020-12-03 08:26 UTC, antoniomanuelfr approved these changes
LGTM

2020-12-04 09:56 UTC, Molter73 requested changes

2020-12-04 09:56 UTC, Molter73 commented on tests/integration/test_fim/test_timezone_changes/test_timezone_changes.py
> +    os.system('tzutil /s "Egypt Standard Time"')
`tzutil` is a Windows specific command but this test is not marked to run in Windows only. If we can find a command that works in a similar manner in *nix systems, we can make this test general for all of our supported systems.

2020-12-04 17:45 UTC, Molter73 approved these changes
LGTM!

2020-12-11 15:52 UTC, merged