Add test to check alerts when the file limit is reached.
wazuh/wazuh-qa pull request #961
Opened 2020-12-02 12:39 UTC by antoniomanuelfr

Hello team,

This PR aims to add a new test that checks that alerts are correctly triggered when the file limit is reached.

# Tests logic

- The test enables the file_limit option and creates files inside that folder (monitored with realtime and whodata) until the limit is reached.
- The test removes a file that is not in the DB and checks that no alert is triggered.
- The test removed a file that is inserted in the DB and checks that the alert is triggered.

# Tests checks

- [X] Proven that tests **pass** when they have to pass
- [X] Proven that tests **fail** when they have to fail
- [X] Proven that tests have the expected behavior in **RPM and DEB**
- [ ] Tested and passed in Jenkins. Build URL: `<YOUR_JENKINS_BUILD_URL>`

Best regards.

2020-12-09 12:11 UTC, jesusjimsa requested changes

2020-12-09 13:59 UTC, jesusjimsa submitted a review, later dismissed
LGTM!

2020-12-17 14:56 UTC, jotacarma90 approved these changes

2021-01-07 12:00 UTC, Molter73 approved these changes
LGTM!

2021-01-13 17:11 UTC, merged