Add test_max_fps for FIM.
wazuh/wazuh-qa pull request #963
Opened 2020-12-04 15:38 UTC by antoniomanuelfr

Hello team,

This PR aims to add a new integration test that checks that the FIM scan sleeps when reached 
the maximum files per second

Closes https://github.com/wazuh/wazuh/issues/5645

# Tests logic

- The test will create a number of files and set a low `max_fps`. Then it will wait that the debug message appears.
- In the second case it will check that if the option is disabled (setting `max_fps` to 0) the debug messages doesn't appear.

# Tests checks

- [X] Proven that tests **pass** when they have to pass
- [X] Proven that tests **fail** when they have to fail
- [ ] Tested and passed in Jenkins. Build URL: `<YOUR_JENKINS_BUILD_URL>`

## RPM manager

```
[root@centosmanager integration]# python3 -m pytest test_fim/test_max_fps/
=========================================================== test session starts ============================================================
platform linux -- Python 3.6.8, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: metadata-1.11.0, html-2.0.1, testinfra-5.0.0
collected 2 items                                                                                                                          

test_fim/test_max_fps/test_max_fps.py ..                                                                                             [100%]

```

Best regards.

2020-12-09 14:53 UTC, jesusjimsa requested changes

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +from wazuh_testing.tools.configuration import load_wazuh_configurations, check_apply_test
`check_apply_test ` is imported but unused.

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +from wazuh_testing import global_parameters
Add a blank line to separate system imports from `wazuh_testing` imports.

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +    return match is not None
This callback should be in _fim.py_.

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +p, m = generate_params(extra_params=conf_params, modes=['scheduled', 'scheduled'])
`scheduled` twice?

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +
Remove this section if there are no parameters.

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +    msg = r'.*Maximum number of files read per second reached, sleeping.$'
The `$` is not needed here. Also, the original message ends in `.` so the last `.` can be substituted with `\.` here.

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +        create_file(REGULAR, test_directories[0], f'test_{int(round(time() * 10 ** 6))}', content='')
You can have here any number, there is no need to calculate this big number to add it to the file name. You can just use `i` from the `for` loop.

2020-12-09 14:53 UTC, jesusjimsa commented on tests/integration/test_fim/test_max_fps/test_max_fps.py
> +            pass
You need to add a case for when the `max_fps` value is not `0`. In this case, if there is a `TimeoutError`, the test should fail.
As it is now the test will always pass.

2020-12-10 15:56 UTC, jesusjimsa requested changes
The test failed in my computer: 
[report_max_fps.zip](https://github.com/wazuh/wazuh-qa/files/5673959/report_max_fps.zip)

2020-12-11 07:20 UTC, antoniomanuelfr commented
> The test failed in my computer:
> [report_max_fps.zip](https://github.com/wazuh/wazuh-qa/files/5673959/report_max_fps.zip)
Hi, the test was failing due to a typo in the main branch that has been fixed.
Could you check it again?

2020-12-11 08:32 UTC, jesusjimsa submitted a review, later dismissed
LGTM!

2020-12-11 16:04 UTC, Molter73 approved these changes
LGTM!

2021-01-21 17:43 UTC, Molter73 submitted a review, later dismissed

2021-02-02 15:27 UTC, antoniomanuelfr commented
After the last modifications in https://github.com/wazuh/wazuh/pull/6830 (this commit adapts the function that checks the `max_files_per_second` option https://github.com/wazuh/wazuh/pull/6830/commits/d12ff228b9c6326b8495bc73e552fa96959e490b to work with all FIM modes) the integration test was modified to adapt to the new behavior.

This is the report of this test only with the latest changes:
[Uploading report.zip…]()

2021-02-03 16:18 UTC, Molter73 approved these changes
LGTM!

2021-02-08 10:03 UTC, BraulioV requested changes

2021-02-08 10:03 UTC, BraulioV commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
> +# Copyright (C) 2015-2020, Wazuh Inc.
```suggestion
# Copyright (C) 2015-2021, Wazuh Inc.
```

2021-02-08 10:03 UTC, BraulioV commented on tests/integration/test_fim/test_files/test_max_files_per_second/test_max_files_per_second.py
> +            raise TimeoutError
```suggestion
    except TimeoutError as e:
        if get_configuration['metadata']['max_files_per_sec'] == 0:
            pass
        else:
            raise e
```

2021-02-08 10:38 UTC, BraulioV approved these changes

2021-02-15 10:15 UTC, merged